### ISSUE TITLE
InSingle 生成的sql不正确

### ISSUE THREAD

**Issue by alanpeng66** [sunkaixuan/SqlSugar#100]
使用的是sqlsugar core

code:
_db.Queryable<Crm_logobooking_L>().InSingle(id);

sql:
 SELECT [Logoid],[Dwid],[Dwname],[Tel],[Mail],[Conn],[Empid],[Rgdt],[Startdt],[Enddt],[Href],[Border],[Bordercolor],[Borderlinestyle],[Filename],[Img],[Imgtype],[Orderid],[Status],[Showtype] FROM [ran_web].[dbo].[crm_logobooking_L]  WHERE [Logoid] IN (@InPara0)

我希望的是
 SELECT [Logoid],[Dwid],[Dwname],[Tel],[Mail],[Conn],[Empid],[Rgdt],[Startdt],[Enddt],[Href],[Border],[Bordercolor],[Borderlinestyle],[Filename],[Img],[Imgtype],[Orderid],[Status],[Showtype] FROM [ran_web].[dbo].[crm_logobooking_L]  WHERE [Logoid] = @InPara0

**Comment by sunkaixuan** [comment]
那就用single(it=>it.id=1)

**Comment by alanpeng66** [comment]
> 那就用single(it=>it.id=1)

感谢你解决我的问题。 
官方文档上的描述与此不同，可能会对其它人产生影响。

**Comment by sunkaixuan** [comment]
没有影响 SQL执行计划底层是一样的。性能没区别
