### ISSUE TITLE
全局过滤器在异步下无效

### ISSUE THREAD

**Issue by navyblue9** [sunkaixuan/SqlSugar#101]
ToListAsync() 全局过滤器 
`db.QueryFilter
             .Add(new SqlFilterItem()//单表全局过滤器
             {
                 FilterValue = filterDb =>
                 {
                     return new SqlFilterResult() { Sql = " isDelete=0" };
                 },
                 IsJoinQuery = false 
             })`
不生效

**Comment by sunkaixuan** [comment]
节后上班前会同步到GIT HUB 和NEWUGET
