### ISSUE TITLE
关于随机查询

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#102]
目前想要通过sqlsugar实现随机查询有两种方法
1、直接随机查询的sql语句
2、OrderBy("NEWID()")  

对于不想看到项目里出现SQL语句的强迫症
能不能或考不考虑整个内置的随机函数
比如 db.Queryable<Model>().Random(N).ToList()    N:随机条数

**Comment by sunkaixuan** [comment]
db.Queryable<Student>().OrderBy(it => SqlFunc.GetRandom()).ToList() 节后上班前会更新到  GITHUB
