### ISSUE TITLE
插入对象，忽略非数据列

### ISSUE THREAD

**Issue by gui-ge** [sunkaixuan/SqlSugar#103]
请问有什么办法可以这插入的时候忽略这些字段
![image](https://user-images.githubusercontent.com/24669229/46124770-80e1ea80-c258-11e8-9038-d3ecebadc2f0.png)

文档中的这几个方法没有找到，我用的是 4.6.4.9版本
![image](https://user-images.githubusercontent.com/24669229/46124883-ff3e8c80-c258-11e8-8171-8216816e5651.png)

![image](https://user-images.githubusercontent.com/24669229/46124894-11b8c600-c259-11e8-83c2-739b2a733dfc.png)

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Doc/8 请看4.X文档
