### ISSUE TITLE
一个字段存储多个ID时的查询

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#104]
比如
-------------
ID      NO
-------------
1        1,2,3
2         3,11,23

如果想要查询NO里包含“1”的数据，用like肯定能把两条都查出来
已知解决方法
1、mysql 里有个NB的函数find_in_set，能精确匹配，mssql，sqlite貌似没有。。
2、用笨方法 NO='1' or NO like '1,%' or NO like '%,1,%' or NO like '%,1'
sqlsugar里考不考虑这种情况呢？

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Doc/8/1162
