### ISSUE TITLE
无法进行多字段修改

### ISSUE THREAD

**Issue by open-mfc** [sunkaixuan/SqlSugar#109]
//写法1
```
var t8 = db.Updateable(updateObj)
.UpdateColumns(it=>new {it.Name,it.ClassScore})
.ReSetValue(it => it.Name == (it.Name + 1) &&  it.ClassScore == (it.ClassScore + 1))
.ExecuteCommand();
```
这样写会给出异常  Expression  format error 而且是不会被 db.Aop.OnError捕获的异常
我想要的sql语句是：`update student set Name=Name+1 ,ClassScore=ClassScore+1 where id=11`

**Comment by open-mfc** [comment]
```
var t8 = db.Updateable(updateObj)
.UpdateColumns(it=>new {it.Name,it.ClassScore})
.ReSetValue(it => it.Name == (it.Name + 1))
.ReSetValue(it => it.ClassScore == (it.ClassScore+ 1)).ExecuteCommand();
```
经过测试 可以是这样解决

**Comment by reeshuai** [comment]
// SqlSugar.UpdateableProvider<T>
// Token: 0x0600080F RID: 2063 RVA: 0x000235B8 File Offset: 0x000217B8
public IUpdateable<T> ReSetValue(Expression<Func<T, bool>> setValueExpression)
{
	Check.Exception(!this.IsSingle, "Batch operation not supported ReSetValue", Array.Empty<string>());
	ExpressionResult expressionValue = this.UpdateBuilder.GetExpressionValue(setValueExpression, ResolveExpressType.WhereSingle, true);
	string value = Regex.Match(expressionValue.GetResultString(), "\\((.+)\\)").Groups[1].Value;
	Expression body = setValueExpression.Body;
	Check.Exception(!(body is BinaryExpression), "Expression  format error", Array.Empty<string>());
	Check.Exception((body as BinaryExpression).NodeType != ExpressionType.Equal, "Expression  format error", Array.Empty<string>());
	Expression left = (body as BinaryExpression).Left;
	Check.Exception(!(left is MemberExpression), "Expression  format error", Array.Empty<string>());
	string @string = this.UpdateBuilder.GetExpressionValue(left, ResolveExpressType.FieldSingle, true).GetString();
	this.UpdateBuilder.SetValues.Add(new KeyValuePair<string, string>(@string, value));
	return this;
}

**Comment by reeshuai** [comment]
WhereSingle  只能是单条件的，但是字段如果是枚举 会报错
