### ISSUE TITLE
Sqlsugar是 线程安全的吗？

### ISSUE THREAD

**Issue by Mike-Feng** [sunkaixuan/SqlSugar#11]
在一次实际应用中，并发量太高，导致缓存了错误的sql 模板，以至于后来每次sql查询 都会报”不能将int 转换成string”的错。
抱歉，暂时还没有找到一个非常简单的重现方法。
谢谢了。

**Comment by sunkaixuan** [comment]
正确使用是没有线程问题的
.一个实体只能映身一张表，如果存在多张表就可能出现你说的这种问题
