### ISSUE TITLE
MergeTable Datetime? 强制转换为0001-01-01了

### ISSUE THREAD

**Issue by chnzhang** [sunkaixuan/SqlSugar#112]
![image](https://user-images.githubusercontent.com/3386915/46934868-e53fdf00-d08b-11e8-9dee-4b44356bf806.png)

**Comment by chnzhang** [comment]
Datetime? 是弄的可为空字段

**Comment by sunkaixuan** [comment]
那是因为你ViewModel 不是datetime?

**Comment by chnzhang** [comment]
不是啊。你看图了吗。。对象是可为空字段，前面是用的匿名对象

**Comment by chnzhang** [comment]
new{
getDateTime=b.get_date_time
}
b.get_date_time是可为空的?  前面是一个匿名对象
![image](https://user-images.githubusercontent.com/3386915/46935358-83807480-d08d-11e8-91d9-2d4e0d09c199.png)
