### ISSUE TITLE
InSingle 方法 无法根据主键获取 

### ISSUE THREAD

**Issue by lintao1990720** [sunkaixuan/SqlSugar#114]
![qq 20181015211005](https://user-images.githubusercontent.com/14249175/46952885-c3ac1b00-d0be-11e8-8e95-30a21f4b1c62.png)
4.8 刚出，我用InSingle来获取实体，结果就出现下面情况
![image](https://user-images.githubusercontent.com/14249175/46952934-e9d1bb00-d0be-11e8-9462-b8231fef819d.png)
主键被拆分出来

**Comment by sunkaixuan** [comment]
4.9 ok
