### ISSUE TITLE
用新增Insertable()或者Updateable()方法，用字典方式，里面有null情况会报错

### ISSUE THREAD

**Issue by lintao1990720** [sunkaixuan/SqlSugar#115]
![image](https://user-images.githubusercontent.com/14249175/46953131-8431fe80-d0bf-11e8-8c04-56f571c1a2c2.png)
字典那边dic.Add("Name",null); 好像会报错
![image](https://user-images.githubusercontent.com/14249175/46953150-96ac3800-d0bf-11e8-85e5-c373c9587383.png)
![image](https://user-images.githubusercontent.com/14249175/46953192-b7748d80-d0bf-11e8-9e62-5ade3a61c92c.png)

**Comment by sunkaixuan** [comment]
4.8 oK
