### ISSUE TITLE
MysqlSugar 

### ISSUE THREAD

**Issue by Adevien** [sunkaixuan/SqlSugar#120]
hi, could you add a raw connection in the MysqlSugar nuget?

` public SqlSugarClient(string HOST, string DBNAME, string USER, string PASSWORD);`

is more useful than having a single-string.

**Comment by sunkaixuan** [comment]
MySqlSugar is the old version is no longer maintained, now the new version is SqlSugar, SqlSugr supports MySql. Heavy loading will be added later.

**Comment by Adevien** [comment]
Okey, good to hear. Also fixed the case sensitive issue? 
`Queryable<Classname>().ToList();` will fire an exception: databasename.Classname couldn't be found. It seems it is case sensitive.
