### ISSUE TITLE
@MethodConst 生成有bug

### ISSUE THREAD

**Issue by gwhzh21** [sunkaixuan/SqlSugar#122]
,.Select(
                        (t0, t1, t2, t3) =>
                    new Item()
                    {
 ...                       imgurl ="/images/"+t0.CODE+".jpg",
                        NAME = t0.NAME,
                        PROPERTY = SqlFunc.ToString("abc"),
                        IS_CX = SqlFunc.ToString("abc"),
                        IS_LP = SqlFunc.ToString("abc"),
                        IS_QC = SqlFunc.ToString("abc"),
                        IS_RX = SqlFunc.ToString("abc"),
                        IS_XP = SqlFunc.ToString("abc"),
                        IS_ZP = SqlFunc.ToString("abc"),
                        SIZE = SqlFunc.ToString("abc"),
                        //PROPERTY = "4"
                    })
                    )

被转成了
CAST(@MethodConst92 AS NVARCHAR(MAX)) AS [IS_CX] , CAST(@MethodConst1202 AS NVARCHAR(MAX)) AS [IS_LP] , CAST(@MethodConst1212 AS NVARCHAR(MAX))

@MethodConst1202  和 @MethodConst1212是不对的。
应该是
@MethodConst102
和@MethodConst112
sqlSugarCore 4.8.1

**Comment by gwhzh21** [comment]
我用到了unionall，

**Comment by sunkaixuan** [comment]
近期会更新
