### ISSUE TITLE
decimal相减问题

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#123]
版本4.8，数据库sqlite
数据库 Score 类型 real
实体类 Score 类型 decimal

问题描述
x.Score 值为10.2，Score值为10
db.Updateable<UserInfo>().UpdateColumns(x => x.Score == Score)
运行后数据库里的值为0.19999999999

解决思路
1、把数据库 Score类型 改为 float， 实体类 Score类型改为float，查询报错“实体与表映射出错。指定的转换无效”
2、把数据库 Score类型 改回 real， 实体类 Score类型改为double，查询正常，修改后数据库Score值为0.1999999999
3、重新把实体类 Score类型改为decimal，先读取出数据库score的值，再与score相减后值为0.2，正常
var uscore=db.Queryable.......
var zscore=uscore-Score;
db.Updateable<UserInfo>().UpdateColumns(x => x.Score == zcore)

不知这是数据库问题还是sqlsugar问题

**Comment by sunkaixuan** [comment]
数据库中的float对应C#float 好像是这样的并不是C#中的 float

**Comment by sunkaixuan** [comment]
你可以用DBFIRST生成实体和你建的实体比较一下

**Comment by KFine001** [comment]
DBFIRST 生成的结果是 数据库real → 实体类 double
运行db.Updateable().UpdateColumns(x => x.Score == x.Score-Score) 仍然得出来多位小数
