### ISSUE TITLE
数据库排序规则 Chinese_PRC_CS_AS

### ISSUE THREAD

**Issue by ankier** [sunkaixuan/SqlSugar#125]
在数据库改排序规则下，
1. Db.DbFirst.CreateClassFile无法生产库表的相关属性
2. ORM中 对 更新数据失败，无法自动识别表的主键。

**Comment by sunkaixuan** [comment]
无法找到表主键 参考这个
http://www.codeisbug.com/Doc/8/1154
生成属性
b.DbFirst.IsCreateDefaultValue().CreateClassFile("c:\\Demo\\4", "Demo.Models");
