### ISSUE TITLE
建议完善NuGet包依赖项

### ISSUE THREAD

**Issue by china-live** [sunkaixuan/SqlSugar#126]
目前NuGet上的SqlSugar在线安装包依赖项为空，但是实际上SqlSugar部分功能是需要依赖Newtonsoft.Json 9.0.0.1及以上版本。
![qq 20181105094356](https://user-images.githubusercontent.com/12002799/47973497-ac6db580-e0df-11e8-83bf-0fe763664d32.png)
![qq 20181105094406](https://user-images.githubusercontent.com/12002799/47973559-10907980-e0e0-11e8-8b05-3af367f505d1.png)

**Comment by sunkaixuan** [comment]
后续版本会去掉JSON.NET依赖
