### ISSUE TITLE
SqlFunc.HasValue 以及 SqlFunc.IsEmptyOrNull函数生成了Oracle无效语句

### ISSUE THREAD

**Issue by xman086** [sunkaixuan/SqlSugar#129]
SqlFunc.HasValue(item.Id)==>WHERE ( "ID"<>'' AND "ID" IS NOT NULL )
SqlFunc.IsEmptyOrNull(item.Id)==>WHERE NOT( "ID"='' OR "ID" IS NULL )

如果Oracle中ID字符串为空串（Oracle默认会将空串转为NULL存储) 以上语句将会把所有不为空的记录全部过滤掉，即与希望的结果恰好相反。正确生效的语句为WHERE "ID" IS NOT NULL。
注：以上SQL语句在mysql以及sqlserver中返回正确结果。

**Comment by sunkaixuan** [comment]
这个不作处理，有些人是需要我这样的SQL

你要IS NOT NULL直接 it.name !=null 就行了

**Comment by xman086** [comment]
> 这个不作处理，有些人是需要我这样的SQL
> 
> 你要IS NOT NULL直接 it.name !=null 就行了

对于非Oracle数据库确实有这个需求，但是建议说明一下方法的适用范围：）
