### ISSUE TITLE
oracletest测试出现的问题

### ISSUE THREAD

**Issue by RicordL** [sunkaixuan/SqlSugar#140]
在调用oracletest项目里的new Insert(1).Init()方法时报错？说连不上sqlserver???不是连接的是oracle吗？而且在测试时，我数据库里时int存储的schoolid是1，取出来成了1.0导致报错。

**Comment by sunkaixuan** [comment]
ORACLE TEST的功能都是可以执行的，可能是你表配置错误或者连接字符串错误

**Comment by RicordL** [comment]
ememem,可能是吧，后来发现是.net core的。。。但是不太适合我使用了，我的项目里还是想用.net framework，不过这个项目做得很棒，给星星了
