### ISSUE TITLE
SqlSugar的两个BUG

### ISSUE THREAD

**Issue by g767160** [sunkaixuan/SqlSugar#142]
1、oracle生成所有实体的时候，如果oralce中存在表带小写的，如Basic，查询的时候需要加双引号的，如：select * from "Basic"的，这个时候导出所有实体，会直接出现错误，表或视图不存在，建议修复；
2、反射的问题，看了下源码，如下面代码，这是修改后的，修改前没有做type和Result的一个类型判断，如果是反射的话，会导致这两个类型不一致而出错，建议修复。
            if (typeCache.ContainsKey(cacheKey))
            {
                type = typeCache[cacheKey];
                if(!(type is Restult))
                {
                    typeCache.Remove(cacheKey);
                }
            }
            if (!typeCache.ContainsKey(cacheKey))
            {
                lock (typeCache)
                {
                    type = Type.GetType(className + "`" + types.Length, true).MakeGenericType(types);
                    Check.ArgumentNullException(type, string.Format(ErrorMessage.ObjNotExist, className));
                    if (!typeCache.ContainsKey(cacheKey))
                    {
                        typeCache.Add(cacheKey, type);
                    }
                }
            }

**Comment by sunkaixuan** [comment]
ORACLE表名大写是规范，不支持小写表

**Comment by g767160** [comment]
如不支持小写表，可过滤小写表，要不然使用全部导出实体的功能会有异常

**Comment by g767160** [comment]
另外，也是反射的问题，在插入和更新的操作，第一次反射是没问题的，在不关闭程序的情况下，覆盖掉dll后，再次反射会出现“对象与目标类型不匹配“的异常信息，初步判断是使用了缓存了Type类型导致，请大神帮忙解决，谢谢

**Comment by sunkaixuan** [comment]
db.util.removeAllCache
