### ISSUE TITLE
SqlSugar新体验出现的BUG

### ISSUE THREAD

**Issue by xueandfeng** [sunkaixuan/SqlSugar#149]
1.使用读写分离后进行Dispose的bug
![default](https://user-images.githubusercontent.com/20178645/48964016-72a31700-efda-11e8-9d98-43ea61f72dc6.png)
直接实例化SqlSugarClient对象不做任何的操作直接释放出现的异常
![default](https://user-images.githubusercontent.com/20178645/48964019-7f276f80-efda-11e8-86e3-c9f3eca5d0f7.png)

2.Mapper结合MergeTable方法会导致Mapper中的mapperAction参数值丢失
![default](https://user-images.githubusercontent.com/20178645/48964047-0ffe4b00-efdb-11e8-98a1-538c3a6118d4.png)

![default](https://user-images.githubusercontent.com/20178645/48964045-0543b600-efdb-11e8-8c76-b5e0504a7f72.png)

**Comment by sunkaixuan** [comment]
已修复这2天会同步
