### ISSUE TITLE
sql语句怎么使用in语句？

### ISSUE THREAD

**Issue by wenjie88** [sunkaixuan/SqlSugar#153]
` Db.Ado.ExecuteCommand("DELETE table WHERE id in @ids", new { ids = ids.ToArray() });`

这样写会报错。Failed to convert parameter value from a Int32[] to a String.

**Comment by sunkaixuan** [comment]
Db.Ado.ExecuteCommand("DELETE table WHERE id in @ids", new { ids = ids.ToArray() });

db.deleteable<object>().as("table ").in(ids.ToArray() }).ExecuteCommand()

**Comment by sunkaixuan** [comment]
db.deleteable《object》().as("table ").in(ids.ToArray() }).ExecuteCommand()h
