### ISSUE TITLE
Oracle Clob Error

### ISSUE THREAD

**Issue by 64237442** [sunkaixuan/SqlSugar#155]
多谢版主支持，但 这个问题依旧存在。我用远程的写法是ok 的。
 new OracleParameter("p_XmlModule", OracleDbType.Clob,xmlModule, System.Data.ParameterDirection.Input),         
OracleParameter param_XmlData = new OracleParameter("p_XmlData", OracleDbType.Clob, System.Data.ParameterDirection.Output);   

但使用你的方法确实找不到原因：

    var p14 = new SugarParameter("@p_XmlModule", "<D><FNumber>2001</FNumber><FFormula>ACCT(6999.03)</FFormula></D>")
            {
                DbType = System.Data.DbType.Binary
            };
            var p15 = new SugarParameter("@p_XmlData", null)
            {         
                DbType = System.Data.DbType.Binary,
                 Direction = ParameterDirection.Output 

                 
            };
        
            //p22.IsRefCursor = true;
            db.Ado.UseStoredProcedure().ExecuteCommand("PS_KingDee_SynPSData", p11, p12, p13, p14, p15);

**Comment by sunkaixuan** [comment]
你看看我怎么写的啊上次贴子不是发过了吗
var p=new SugarParameter(“@name”,byte[]); 你的参数要是一个byte数组

**Comment by sunkaixuan** [comment]
Clob对应C# 的 byte[]类型的值

**Comment by sunkaixuan** [comment]
你一个XML设成 流类型不报错吗
