### ISSUE TITLE
SqlSugar是否支持夸库查询

### ISSUE THREAD

**Issue by wenjie88** [sunkaixuan/SqlSugar#157]

**Comment by sunkaixuan** [comment]
db.queryable<student>().As(库名.表名).ToList 你看看这样行不 同服务器是可以查询的

**Comment by wenjie88** [comment]
> db.queryable().As(库名.表名).ToList 你看看这样行不 同服务器是可以查询的

问题是现在不同服务器、、、

**Comment by wenjie88** [comment]
@sunkaixuan  问题是现在不同服务器、、、

**Comment by sunkaixuan** [comment]
跨服务器这块会在5.X 版本中去实现，你现在可以用 db.ado.sqlquery(sql)的方式实现
