### ISSUE TITLE
SqlFunc.HasValue 测试在sqlserver 里面，连续使用会生成错误的sql

### ISSUE THREAD

**Issue by herubber** [sunkaixuan/SqlSugar#159]
情况1： qry.Where( m=> SqlFunc.HasValue(m.col1) &&  SqlFunc.HasValue(m.col2)  )
       生成 AND ( CASE WHEN (col1<>'' AND col1 is not null) THEN 1 ELSE 0 END ) AND ...
这个 case 表达式 不是布尔类型，所以执行会报错。 应该在case 。。。end 后加 =1

情况2：qry.Where( m=> SqlFunc.HasValue(m.col1) && m.col3 ==0 && SqlFunc.HasValue(m.col2) )
       和情况1不同的地方是HasValue没有连续使用， 中间插入一个 m.col3==0 ,最终生成的语句，
没有case， 直接就是 col1<>'' AND col1 is not null，这个是布尔类型的结果，where可以执行

**Comment by sunkaixuan** [comment]
先这样写  SqlFunc.HasValue(it.Bool2)==true && SqlFunc.HasValue(it.Bool2)==true

这个BUG我本地已修复近期会同步
