### ISSUE TITLE
更新字段时间

### ISSUE THREAD

**Issue by 993352359** [sunkaixuan/SqlSugar#169]
数据库Oracle字段varchar(20)类型
string datetimeNow = DateTime.Now.ToString();
            return db.Updateable<RoadFlow.Data.Model.TB_CHATDATA>()
                .UpdateColumns(u => new RoadFlow.Data.Model.TB_CHATDATA() { READTIME = datetimeNow })
                .Where(u => u.ID == Id)
                .ExecuteCommand();
这样不会出错，但是
return db.Updateable<RoadFlow.Data.Model.TB_CHATDATA>()
                .UpdateColumns(u => new RoadFlow.Data.Model.TB_CHATDATA() { READTIME = DateTime.Now.ToString() })
                .Where(u => u.ID == Id)
                .ExecuteCommand();
长度就为34超长。

**Comment by sunkaixuan** [comment]
用上面的吧 一个是数据库转换一个是 C#转换
