### ISSUE TITLE
强烈希望增加以下接口

### ISSUE THREAD

**Issue by 840900649** [sunkaixuan/SqlSugar#171]
IUpdateable<T> UpdateColumns(string[] columns);
传入修改字段集合，指定字段修改，类似,IgnoreColumns。
 IInsertable<T> IncludeColumns(string[] columns);
传入添加字段集合，指定字段添加，类似,IgnoreColumns。

**Comment by 840900649** [comment]
接口：/Interface/IUpdateable/  增加接口：  IUpdateable<T> UpdateColumns(string[] columns);
接口：/Interface/IInsertable/  增加接口：  IInsertable<T> IncludeColumns(string[] columns);
类： /Abstract/InsertableProvider/InsertableProvider 增加函数  
        public IInsertable<T> IncludeColumns(string[] columns)
        { 
            this.InsertBuilder.DbColumnInfoList = this.InsertBuilder.DbColumnInfoList.Where(it => columns.Any(ig => ig.Equals(it.PropertyName, StringComparison.CurrentCultureIgnoreCase))).ToList();
            return this;
        }
类： /Abstract/UpdateProvider/UpdateableProvider 增加函数  
		 #region 扩展函数
        public IUpdateable<T> UpdateColumns(string[] columns)
        {
            this.UpdateBuilder.DbColumnInfoList = this.UpdateBuilder.DbColumnInfoList.Where(it => columns.Contains(it.PropertyName, StringComparer.OrdinalIgnoreCase)).ToList();
            return this;
        }
 #endregion

**Comment by sunkaixuan** [comment]
IUpdateable WhereColumns(string[] columns);这个现在有

**Comment by sunkaixuan** [comment]
这个是可能实现 var t4 = db.Insertable(insertObj).InsertColumns(it => new { it.Name, it.SchoolId }).ExecuteReturnIdentity(); 指定类参数，下个版本我在加一个string []的重载

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Doc/8/1129 文档有更详细用法
