### ISSUE TITLE
批量修改，只能用主键作为条件，用其他条件无效 

### ISSUE THREAD

**Issue by LXQ9527** [sunkaixuan/SqlSugar#176]
var t1 = db.Updateable(updateObj).WhereColumns(it=>new{it.XId}).ExecuteCommand();//单列可以用 it=>it.XId

**Comment by sunkaixuan** [comment]
多列也以用，只是没提示。打全就好。

**Comment by LXQ9527** [comment]
UpdateColumns与WhereColumns一起用是不行，生成SQL出来就是只有根据主键作为条件，在QQ群里面也也问过其他大神了，代码也贴出来了

**Comment by sunkaixuan** [comment]
有问题给我发一个控制台DEMO
