### ISSUE TITLE
可空枚举映射的字段，在插入数据库时，始终有默认值，无法为Null

### ISSUE THREAD

**Issue by liumanman** [sunkaixuan/SqlSugar#179]
实体某属性的数据类型为一个可空的枚举，数据库中会mapping为可空的整型，但是在进行数据插入操作时，这个字段始终有默认值，无法为null，不知是否是一个bug

**Comment by sunkaixuan** [comment]
枚举这个不处理 ，因为有些人 NULL就解释成0
