### ISSUE TITLE
MSSQL 更新列的时候，因为增加了中括号，导致存储过程rename时候，新的列有了中括号

### ISSUE THREAD

**Issue by zhaixiaoliang12138** [sunkaixuan/SqlSugar#182]
MSSQL 更新列的时候，因为增加了中括号，导致存储过程rename时候，新的列有了中括号，使用MSSQL2008 R2, codefirst 生成的更新列的语句为：exec sp_rename '[CodeTable4].[MyName555]','[MyName55588888]','column';   数据库执行完之后，列明也包含了【】，
![image](https://user-images.githubusercontent.com/15035376/50008767-230ba600-fff0-11e8-854d-5667682f3b53.png)，去掉newColumnName = this.SqlBuilder.GetTranslationColumnName(newColumnName)，则可正常使用

**Comment by sunkaixuan** [comment]
等发布
