### ISSUE TITLE
ConditionalModel 不支持 Oracle的date类型

### ISSUE THREAD

**Issue by xman086** [sunkaixuan/SqlSugar#183]
当使用ConditionalModel时，不支持Oracle的date类型字段。
错误信息：
ORA-01861: literal does not match format string

**Comment by sunkaixuan** [comment]
排查中

**Comment by sunkaixuan** [comment]
conModels.Add(new ConditionalModel() { FieldName = "Student.id", ConditionalType = ConditionalType.Equal, FieldValue = "1" ,FieldValueConvertFunc= it=>Convert.ToInt32(it)}); 添加了个转换回调  周一会发布一个版本
