### ISSUE TITLE
MySQL 插入和更新，aliyun 有些MySQL 数据库产品不支持 “ N'value' ”，例如：DRDS 和 HybirdDB FOR MYSQL.

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#184]
MySQL 插入和更新，aliyun 有些MySQL 数据库产品不支持 “ N'value' ”，例如：DRDS 和 HybirdDB FOR MYSQL. 
能否考虑 MYSQL 类型数据库，插入数据库，值前面，不要增加  N 字符。

**Comment by sunkaixuan** [comment]
先不用批量操作解决后期会更新

**Comment by haibozhou1011** [comment]
SELECT
                                    0 as TableId,
                                    TABLE_NAME as TableName, 
                                    column_name AS DbColumnName,
                                    CASE WHEN  left(COLUMN_TYPE,LOCATE('(',COLUMN_TYPE)-1)='' THEN COLUMN_TYPE ELSE  left(COLUMN_TYPE,LOCATE('(',COLUMN_TYPE)-1) END   AS DataType,
                                    CAST((SUBSTRING(COLUMN_TYPE,LOCATE('(',COLUMN_TYPE)+1,LOCATE(')',COLUMN_TYPE)-LOCATE('(',COLUMN_TYPE)-1)) AS signed) AS Length,
                                    column_default  AS  `DefaultValue`,
                                    column_comment  AS  `ColumnDescription`,
                                     CASE WHEN COLUMN_KEY = 'PRI'
                                    THEN true ELSE false END AS `IsPrimaryKey`,
                                    CASE WHEN EXTRA='auto_increment' THEN true ELSE false END as IsIdentity,
                                    CASE WHEN is_nullable = 'YES'
                                    THEN true ELSE false END AS `IsNullable`
                                    FROM
                                    Information_schema.columns 
                                    where TABLE_NAME='*****' and  TABLE_SCHEMA=(select database()) ORDER BY TABLE_NAME

以上SQL，在插入和更新，会提前产生执行此SQL，但是HybirdDB FOR MYSQL 这个鬼数据库，居然不支持 “CAST((SUBSTRING(COLUMN_TYPE,LOCATE('(',COLUMN_TYPE)+1,LOCATE(')',COLUMN_TYPE)-LOCATE('(',COLUMN_TYPE)-1)) AS signed) ” 此句SQL, 有没有办法关闭掉。

**Comment by sunkaixuan** [comment]
预订下周一 添加批量操作支持不出现N

**Comment by sunkaixuan** [comment]
你把initkey设置成attribute就不会执行这个SQL，需要在实体上加主键或者自增列的特性标识

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Doc/8/1141

**Comment by haibozhou1011** [comment]
好的，感谢！
