### ISSUE TITLE
更新字段问题

### ISSUE THREAD

**Issue by liaozb** [sunkaixuan/SqlSugar#187]
>  var df = db.Queryable<Aoshu_jindu>().First(it => it.userid == 61988 && it.jindu == 3 && it.kecheng == 1 && it.nianji == 1);
>             if (df!=null)
>             {
>                 df.uptime = DateTime.Now;
>                 db.Updateable(df).UpdateColumns(it => new { df.uptime }).ExecuteCommand();
>             }

生成后sql语句 ：UPDATE SET  [dbo].[Aoshu_jindu] SET  WHERE Id=@Id

**Comment by sunkaixuan** [comment]
你写错了 应该这样db.Updateable(df).UpdateColumns(it => new { it.uptime }).ExecuteCommand();
