### ISSUE TITLE
SqlFunc.ContainsArray 问题

### ISSUE THREAD

**Issue by liaozb** [sunkaixuan/SqlSugar#188]
` var ids =new List<int>();
            ids.Add(1);
            ids.Add(2);`
`db.Queryable<Aoshu_jindu>().Where(it => SqlFunc.ContainsArray(ids.ToArray(), it.nianji)).ToList()`
生成后sql :
`SELECT [Id],[nianji],[kecheng],[jindu],[userid],[addtime],[uptime] FROM [ccShouGong].[dbo].Aoshu_jindu  WHERE  (1=2)`

**Comment by sunkaixuan** [comment]
你先这么写      var ids = new List<int>(); ids.Add(1); ids.Add(2);
            var xx3 = ids.ToArray();
            db.Queryable<Aoshu_jindu>().Where(it => SqlFunc.ContainsArray(xx3, it.nianji)).ToList(); 下个版本会处理
