### ISSUE TITLE
MySQL 8.0 版本通过T4 模板生成Model出错

### ISSUE THREAD

**Issue by xltuo** [sunkaixuan/SqlSugar#194]
通过MySqlTest 示例工程中提供建库脚本新建MySQL版本为8.0 的数据库。修改连接字符串，直接保存模板报错

`严重性	代码	说明	项目	文件	行	禁止显示状态
错误		正在运行转换: SqlSugar.SqlSugarException: Dbfirst and  Codefirst requires system table permissions
   在 SqlSugar.Check.Exception(Boolean isException, String message, String[] args) 位置 ..\repos\SqlSugar\Src\Asp.Net\SqlSugar\Utilities\Check.cs:行号 30
   在 SqlSugar.DbFirstProvider.Init() 位置 ..\repos\SqlSugar\Src\Asp.Net\SqlSugar\Abstract\DbFirstProvider\DbFirstProvider.cs:行号 46
   在 SqlSugar.SqlSugarClient.get_DbFirst() 位置 ..\repos\SqlSugar\Src\Asp.Net\SqlSugar\SqlSugarClient.cs:行号 571
   在 Microsoft.VisualStudio.TextTemplating12DA67801B2AFA2E7531A285806458478FDFC3FF42EA0F02DF3CCD5DD5E46C06515E0EBDF82FC23BFFE692E613D21B65C636E4DDD37370F24D385930FF7B06D5.GeneratedTextTransformation.TransformText()	MySqlTest	..\repos\SqlSugar\Src\Asp.Net\MySqlTest\T4\SugarTemplate.tt	1	`

同样的连接字符，通过新建控制台程序 ，直接调用  db.DbFirst.CreateClassFile  生成Model 成功。

**Comment by sunkaixuan** [comment]
这个是WINDOWS权限等因素引起的，你新建的没问题就行了

**Comment by xltuo** [comment]
能给具体的说说吗？我尝试解决一下。电脑是系统是WIN10, 已经更新到最新的1809。VisualStudio2017是用管理员权限运行的。SqlServerTest 这个工程的T4模板通过调整数据库连接字符串，是可以正常生成实体文件的。
