### ISSUE TITLE
sqlite 插入自增列一直为0

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#196]
版本sqlSugarCore4.9.7.2
之前sqlite自增列一直正常，今天使用了EnableDiffLogEvent后插入自增列一直为0
如下
int newID = db.Insertable(model).EnableDiffLogEvent("添加角色").ExecuteReturnIdentity();
后来把EnableDiffLogEvent删掉后一切恢复正常

貌似EnableDiffLogEvent里的某个逻辑导致把自增列赋值为0了，所以一直插入为0
我有几个解决思路不知是否可行
1、把EnableDiffLogEvent顺序放到最后，先执行后获得差异。
2、把EnableDiffLogEvent和ExecuteCommand分开
      比如我不想获得差异日志 直接 db.Insertable(model).ExecuteCommand()
      如果想获得差异日志 再多写一行 db.Insertable(model).EnableDiffLogEvent() 或者其他方式单独获得
3、把差异日志当作对象返回，类似事务的写法

**Comment by KFine001** [comment]
补充：MySQL里自增是正常的

**Comment by KFine001** [comment]
又捣腾了一下午，终于把来龙去脉搞清楚了。我用的sqlite客户端是Navicat Premium 12.0.18 64-bit (破解版)
-------------------------------------------------------------------------------
错误重现
1、手动新建表的时候，ID 类型默认为大写的INTEGER（如果手动点到类型就会下拉出来小写），继续设置主键，勾上自增列
2、程序里使用EnableDiffLogEvent().ExecuteReturnIdentity()就出现郁闷的自增列为0
3、这时把程序里.EnableDiffLogEvent删掉，插入自增列还是0
4、然后把表ID的类型改为小写integer，插入仍然是0
5、最后把程序里的ExecuteReturnIdentity改为ExecuteCommand，插入自增列正常
6、程序里加上EnableDiffLogEvent()，正常
7、把ExecuteCommand改成ExecuteReturnIdentity，正常
有点不大相信，于是又把表删了重建
1、直接把ID类型选为小写integer
2、程序里用EnableDiffLogEvent().ExecuteReturnIdentity()，正常
3、改为EnableDiffLogEvent().ExecuteCommand()，正常
4、删掉EnableDiffLogEvent后各执行了一遍，正常
还是有点不服气，把表删了又重建
1、ID默认大写INTEGER
2、程序里删掉EnableDiffLogEvent，直接执行ExecuteReturnIdentity，插入为0
3、加上EnableDiffLogEvent执行了一遍，果然还是0
4、把表类型改为小写，把EnableDiffLogEvent去掉，仍用ExecuteReturnIdentity执行。还是0
5、把ExecuteReturnIdentity改为ExecuteCommand执行，正常

这说明自增列类型必须为小写integer，但是大写改为小写后必须去掉EnableDiffLogEvent，必须用ExecuteCommand执行才能恢复正常，情况就是这么个情况。。我已懵圈，希望能给大佬一点提示

**Comment by sunkaixuan** [comment]
我这边测试都是OK的我感觉你没有从本质发现问题，如果修改表结构记录清空VS实例如者全部重新生成项目
