### ISSUE TITLE
sqlite差异日志的Time问题

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#199]
版本sqlSugarCore4.9.7.4
差异日志返回的Time属性，我个人理解为sql语句的执行时间，单位为秒（不知是否正确）
今日在sqlite上跑了几下发现时间有点不对劲
1、添加操作，操作时间为2019/1/2 9:53:17，返回的Time为 737060.09:53:17.1744861
2、修改操作，操作时间为2019/1/2 9:57:06，返回的Time为 737060.09:57:06.8076690
3、删除操作，操作时间为2019/1/2 9:58:35，返回的Time为 737060.09:58:35.3966030
MySql上找了下之前的记录
1、添加操作，操作时间2018-12-21 14:52:15，Time: 00:00:00.0156271
2、修改操作，操作时间2018-12-21 15:56:20，Time: 00:00:00.0010793
3、删除操作，操作时间2018-12-18 16:37:54，Time: 00:00:00.1768035

个人觉得MySql返回的Time是正常的，sqlite是把时间乘了一下，即2019*365约等于 737060

**Comment by sunkaixuan** [comment]
估计和你的代码有关系，你可以写个简单例子试一下

**Comment by sunkaixuan** [comment]
我这边正常

**Comment by sunkaixuan** [comment]
我看了下.NET CORE有这个问题

**Comment by sunkaixuan** [comment]
后续会修复这个BUG

**Comment by sunkaixuan** [comment]
已解决，等下周一会同步到GITHUB和NUGET
