### ISSUE TITLE
oracle clob

### ISSUE THREAD

**Issue by liuzr111** [sunkaixuan/SqlSugar#207]
clob类型字段不为空时报映射不上实体的错误

**Comment by sunkaixuan** [comment]
clob用string ,如果还有错发DEMO到我邮箱，这些基本功能用户没有反馈过错

**Comment by JackChenLucky** [comment]
我遇到了和你一样的错误。映射补上去。难道和Oracle的这个Oracle.ManagedDataAccess.dll 驱动有关系？我用的4.122.18.3的版本有关，你是怎么处理的
