### ISSUE TITLE
mysql的分区查询的问题

### ISSUE THREAD

**Issue by kelyljk** [sunkaixuan/SqlSugar#213]
我使用的是
db.Queryable<Student>().PartitionBy("cp0").Where(d => d.a== 1).First();
直接执行sql是
SELECT * FROM `table`   WHERE ( `a` = @a0) GROUP BY cp0  ORDER BY NOW()  LIMIT 0,1

这是不是bug？ 我的是mysql的

**Comment by kelyljk** [comment]
我查到 在这个文件MySqlQueryable中 这边应该是有问题的
        public override ISugarFrom<T> PartitionBy(string groupFileds)
        {
            this.GroupBy(groupFileds);
            return this;
        }

**Comment by sunkaixuan** [comment]
生成的SQL哪不对吗

**Comment by sunkaixuan** [comment]
@a0是参数 ，其实就是1
