### ISSUE TITLE
contains查询的问题

### ISSUE THREAD

**Issue by 5118234** [sunkaixuan/SqlSugar#216]
使用的mssql，在contais中传入的字符串有括号时，拼接的sql语句有错误。如:contains("程序设计(C语言)")，则拼接的sql变成 ([KCMC] like '%'+ CAST(程序设计基础(C语言) AS NVARCHAR(MAX))+'%') )这样了，从而产生了异常。

**Comment by sunkaixuan** [comment]
好的你选用外部变量，下个版本会修复

**Comment by sunkaixuan** [comment]
SELECT [ID],[SchoolId],[Name],[CreateTime] FROM [STudent]  WHERE  ([Name] like '%'+@MethodConst0+'%')
{"@MethodConst0":"( c# )"}

代码怎么写的

**Comment by sunkaixuan** [comment]
var getAll2222 = db.Queryable<Student>().Where(it=>it.Name.Contains("( c# )")).ToList(); 并没有重现

**Comment by 5118234** [comment]
var getAll2222 = db.Queryable().Where(it=>it.Name.Contains("程序设计(C语言)")).ToList(); 
您可以试试上例
