### ISSUE TITLE
请问是否有支持postgresql的计划？

### ISSUE THREAD

**Issue by sunkainj** [sunkaixuan/SqlSugar#22]
一直都很喜欢和关注sqlsugar，可是平时多用的postgresql数据库，不知道有没这方面的计划，或是如何修改可以支持，有可能的话，也可以参与。

**Comment by sunkaixuan** [comment]
你可以下源码参考一下， MYSQL实现只更改了 Realization 里面的 MYSQL方法 ，postgresql我可能会在二个月后才加下，你们参与的话可能会更快支持
