### ISSUE TITLE
MergeTable和Mapper 同时用，导致OrderByIF失效

### ISSUE THREAD

**Issue by feiyit** [sunkaixuan/SqlSugar#221]
MergeTable和Mapper 同时用，导致OrderByIF失效
排序的字段在Mapper里面做了数据处理，所以OrderBy 排序的时候，不是按Mapper结果做的

MergeTable必须在Mapper的前面

原因分析可能是OrderBy优先级要高于Mapper

也就是，排序是在Mapper之前

**Comment by sunkaixuan** [comment]
这个实现不了的，Mapper已拖离数据层面了，你C#处理的代码是不能生成SQL的，Mapper是你操作库已经操作完成了然后进行的操作  你要排序只能内存排序 .tolist().orderby这种
