### ISSUE TITLE
生成的SQL中，应该将表名和列名等处理一下的

### ISSUE THREAD

**Issue by caopengfei** [sunkaixuan/SqlSugar#223]
比如在sqlserver中，就应该将表名和列名等用“[]”符号
例如
select LEN(key) from KeyLimit
是错误的，应该是
select LEN([key]) from KeyLimit

**Comment by sunkaixuan** [comment]
应该是处理的 看下你的C#代码

**Comment by caopengfei** [comment]
好的

**Comment by sunkaixuan** [comment]
已修复近期会同步
