### ISSUE TITLE
MySQL 插入和更新，aliyun 有些MySQL 数据库产品不支持 “ N'value' ”，例如：DRDS 和 HybirdDB FOR MYSQL.

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#224]
MySQL 插入和更新，aliyun 有些MySQL 数据库产品不支持 “ N'value' ”，例如：DRDS 和 HybirdDB FOR MYSQL.

这个已经处理了吗？

**Comment by sunkaixuan** [comment]
你这个是批量更新和插入才出现吗

**Comment by haibozhou1011** [comment]
是的，但是批量更新和插入是我们经常使用的！

**Comment by haibozhou1011** [comment]
好的，我是按照这个临时方案，但是后期排上日程。感谢！

**Comment by sunkaixuan** [comment]
`SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
            {
                ConnectionString = Config.ConnectionString,
                DbType = DbType.MySql,
                IsAutoCloseConnection = true,
                MoreSettings=new ConnMoreSettings() {
                     MySqlDisableNarvchar=true
                }

            }); 近期会同步`

**Comment by haibozhou1011** [comment]
感谢！

**Comment by sunkaixuan** [comment]
已修改近期会同步
