### ISSUE TITLE
两表做left join 有多个关联字段，没有用 “ AND ” 串联，请看图。

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#226]
![image](https://user-images.githubusercontent.com/10756986/51299776-86ac4780-1a64-11e9-87a3-6b9e7c3f4c5d.png)

**Comment by haibozhou1011** [comment]
![image](https://user-images.githubusercontent.com/10756986/51300323-74330d80-1a66-11e9-9e63-263a16b719db.png)

**Comment by haibozhou1011** [comment]
是这样写的吗？还是还不支持？

**Comment by sunkaixuan** [comment]
&&就行了。。

**Comment by haibozhou1011** [comment]
tks
