### ISSUE TITLE
ORACLE 聚合函数 联表更新bug

### ISSUE THREAD

**Issue by shengqi** [sunkaixuan/SqlSugar#229]
c#代码：
                 count = ssc.Client.Updateable<T_HZMJ_WDL>()
                        .UpdateColumns(t => new T_HZMJ_WDL()
                        {
                            ZNWC = t.GQMJ -
                        SqlFunc.Subqueryable<T_HZMJ>().Where(s => t.FUNION == s.FUNION)
                        .Select(s => SqlFunc.AggregateSum(s.GQMJ))
                        }).Where(t => t.ZLDWDM.StartsWith(xdm)).ExecuteCommand();

SQL解析：
UPDATE "T_HZMJ_WDL"
SET "ZNWC" = (
	"GQMJ" - (
		SELECT
			SUM ("GQMJ")
		FROM
			"T_HZMJ"
		WHERE
			("T"."FUNION" = "FUNION")
		AND ROWNUM = 1
	)
)
WHERE
	(
		"ZLDWDM" LIKE : MethodConst0 || '%'
	)

正确的SQL应该是：
UPDATE "T_HZMJ_WDL" T
SET "ZNWC" = (
	"GQMJ" - (
		SELECT
			SUM ("GQMJ")
		FROM
			"T_HZMJ"
		WHERE
			("T"."FUNION" = "FUNION")
	)
)
WHERE
	(
		"ZLDWDM" LIKE : MethodConst0 || '%'
	)

少了表别名T，以及用了聚合函数后，应该去掉AND ROWNUM = 1条件。

**Comment by sunkaixuan** [comment]
已修复近期会同步

**Comment by exy3351** [comment]
> 已修复近期会同步

更新后发现还是有问题
C# 代码
int count = ssc.Client.Updateable<T_HZMJ_WDL>()
                .UpdateColumns(t => new T_HZMJ_WDL()
                {
                    ZNWC = t.GQMJ -
                           SqlFunc.Subqueryable<T_HZMJ>().Where(s =>  **t.FUNION == s.FUNION** )
                               .Select(s => SqlFunc.AggregateSum(s.GQMJ))
                }).Where(t => t.ZLDWDM.StartsWith("331124")).ExecuteCommand();

解析后的Sql语句
UPDATE "T_HZMJ_WDL"
   SET "ZNWC" =
       ("GQMJ" - (SELECT SUM("GQMJ")
                    FROM "T_HZMJ"
                   WHERE (**"T"."FUNION" = "FUNION"**)
                     **AND ROWNUM = 1**))
 WHERE ("ZLDWDM" like :MethodConst0 || '%')
问题：
1.   **"T"."FUNION" = "FUNION"**  解析时t没有解析成表名；
2.  聚合函数多了 **ROWNUM = 1** 的判断
