### ISSUE TITLE
code first 生成表主键顺序问题

### ISSUE THREAD

**Issue by birdlll** [sunkaixuan/SqlSugar#235]
code first 生成字段顺序是 先子类>父类>....
但如果项目实体类是拆分很多根组合而成的, 主键和基础字段放到一些抽象基类, 实体是继承这些抽象类实现的. 
这样会导致主键被放到了最后..如果字段多得话很影响阅读.能否优先将主键排到首位?

**Comment by sunkaixuan** [comment]
这个可以的，后续更新

**Comment by sunkaixuan** [comment]
已修复近期会同步
