### ISSUE TITLE
Feature request: Support JSON datatype and functions

### ISSUE THREAD

**Issue by kotoneme** [sunkaixuan/SqlSugar#236]
MySQL 5.7.8  - 
https://dev.mysql.com/doc/refman/5.7/en/json-function-reference.html
SqlServer 2016 - 
https://docs.microsoft.com/en-us/sql/t-sql/functions/json-functions-transact-sql?view=sql-server-2016
SQLite3.9.0 - 
https://www.sqlite.org/json1.html
Oracle 12c
https://oracle-base.com/articles/12c/json-support-in-oracle-database-12cr1
Postgresql 9.4 - 
https://www.postgresql.org/docs/9.4/functions-json.html

**Comment by sunkaixuan** [comment]
public static void Json()
        {
            Db.CodeFirst.InitTables<JsonTest>();
            Db.DbMaintenance.TruncateTable<JsonTest>();
            Db.Insertable(new JsonTest() { Order = new Order { Id = 1, Name = "order1" } }).ExecuteCommand();
            var list = Db.Queryable<JsonTest>().ToList();
            UValidate.Check("order1", list.First().Order.Name, "Json");
            Db.Updateable(new JsonTest() { Id = 1, Order = new Order { Id = 2, Name = "order2" } }).ExecuteCommand();
            list= Db.Queryable<JsonTest>().ToList();
            UValidate.Check("order2", list.First().Order.Name, "Json");
            var list2 = Db.Queryable<JsonTest>().ToList();
        }
    }


    public class JsonTest
    {
        [SqlSugar.SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
        public int Id { get; set; }
        [SqlSugar.SugarColumn(ColumnDataType = "varchar(max)", IsJson = true)]
        public Order Order { get; set; }
    }

**Comment by sunkaixuan** [comment]
These two days will be synchronized

**Comment by darkflame0** [comment]
@sunkaixuan 
可以支持使用JObject进行Json查询吗？
比如

```csharp
public class JsonTest
{
    [SqlSugar.SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
    public int Id { get; set; }
    [SqlSugar.SugarColumn(ColumnDataType = "jsonb")]
    public JObject Jo { get; set; }
}

Db.Queryable<JsonTest>().Where(a=>a.Jo["prop"][1].Value<string>() == "test").ToList();
```

对于postgresql
翻译:
```sql
select * from "JsonTest" where "Jo"->'prop'->>1::text = 'test'
```
