### ISSUE TITLE
能否增加视图的操作，查询走视图，新增、更新、删除走表

### ISSUE THREAD

**Issue by huangzhk** [sunkaixuan/SqlSugar#238]
例如在SugarTable中增加View属性，在指定View属性的情况下可以按照View指定的视图名查询，
在SugarColumn中可以标记那些是视图属性，只在查询的时候赋值，Insert，Update都忽略该属性

**Comment by sunkaixuan** [comment]
不用搞这么麻烦 db.Queryable<视图类>().AS(db.EntityMaintenance.GetTableName<表类>()).ToList()

**Comment by sunkaixuan** [comment]
你的想法还是太绕了，并不是太好的设计，表就是表视图就是视图，你可以建个视图类继承表类
