### ISSUE TITLE
动态表名

### ISSUE THREAD

**Issue by lhxidian** [sunkaixuan/SqlSugar#242]
我需要根据我的业务需要动态修改表名？

**Comment by sunkaixuan** [comment]
描述具体一点

**Comment by sunkaixuan** [comment]
`       //修改表名(最新方法近期更新)
            db.DbMaintenance.RenameTable();

            //删除ORM表结构缓存
            db.Utilities.RemoveCache();

            //使用别名表
            db.Queryable<Student>().AS("新表名").ToList();`
