### ISSUE TITLE
报：索引和长度必须引用该字符串内的位置。\r\n参数名: length  这个错误

### ISSUE THREAD

**Issue by zhongnba** [sunkaixuan/SqlSugar#243]
官网这个写法会报：索引和长度必须引用该字符串内的位置。\r\n参数名: length  这个错误
//写法1
var t8 = db.Updateable<Student>().UpdateColumns(it => new Student() { Name = it.Name+1}).Where(it => it.Id == 11).ExecuteCommand();
 我参考上面的写法，写了一个语句
var t8 = mContext.Updateable<ShopOfChild>().UpdateColumns(it => new ShopOfChild() { ShopChildName = it.ShopChildName }).Where(it => it.ID == key).ExecuteCommand();
 但是会报错

**Comment by sunkaixuan** [comment]
基本上语法不会有BUG的，你认真看看是不是哪里写的不对，还有问题发个控制台程序到我邮箱去重现
