### ISSUE TITLE
程序集签名

### ISSUE THREAD

**Issue by Dason1986** [sunkaixuan/SqlSugar#244]
由于公司开发环境情况，项目都是有为程序集签名的。请问能在下个版本带上签名吗？
不然我为了一个签名文件 ，要把你新的版本所有代码复制一份。自己生成一个有签名的SqlSugar.dll

**Comment by sunkaixuan** [comment]
OK

**Comment by AtlantisDe** [comment]
这个必须随便加个签名啊 我也觉得特别麻烦 没签名我自己给加了个签名上去
