### ISSUE TITLE
mysql数据库，当union遇到limit时sql语法生成错误问题，需要用括号把limit查询部分包起来，不然会报错

### ISSUE THREAD

**Issue by tcltom** [sunkaixuan/SqlSugar#245]
例子：
List<ISugarQueryable<Menu>> listQuery = new List<ISugarQueryable<Menu>>();
            //获取指定的一条数据
            var query1 = client.Queryable<Menu>().Where(p=>p.Id==1).Take(1);
            listQuery.Add(query1);
            //获取指定的一条数据
            var query2 = client.Queryable<Menu>().Where(p => p.Id == 2).Take(1);
            listQuery.Add(query2);
            var ret = client.UnionAll(listQuery).ToSql();
生成的异常sql：
SELECT * FROM  (SELECT `Id`,`Name`,`DisplayName`,`ApplicationType`,`ParentId`,`Icon`,`Url`,`Index`,`Remark` FROM `Menu`   WHERE ( `Id` = @Id0UnionAll1 )   LIMIT 0,1 UNION ALL 
SELECT `Id`,`Name`,`DisplayName`,`ApplicationType`,`ParentId`,`Icon`,`Url`,`Index`,`Remark` FROM `Menu`   WHERE ( `Id` = @Id0UnionAll2 )   LIMIT 0,1) unionTable

**Comment by sunkaixuan** [comment]
测试下来没有问题，MYSQL是不是版本太老了，还有疑问写个DEMO发我邮箱
