### ISSUE TITLE
异步后RemoveDataCache()失效

### ISSUE THREAD

**Issue by wuzj8839** [sunkaixuan/SqlSugar#246]
异步后RemoveDataCache()失效

按照这样写，await db.Updateable(UnitEntity).RemoveDataCache().ExecuteCommandAsync()，失效，redis的内容没有删除。改成同步就没有问题。

**Comment by sunkaixuan** [comment]
你是最新版本吗？？

**Comment by wuzj8839** [comment]
> 你是最新版本吗？？

最新版的，从github下下来编译也不行。

**Comment by sunkaixuan** [comment]
等发布
