### ISSUE TITLE
4.1.0.8版本 Mysql出现的问题

### ISSUE THREAD

**Issue by Suuuuuuuuu** [sunkaixuan/SqlSugar#25]
1，分页查询ToPageList总是少第二页第一条数据，
2，数据库类型bit， DB模型不支持bool，报超出长度的错。用Int才可以。
3，数据库类型int，DB模型不支持long。

**Comment by sunkaixuan** [comment]
ToPageList的问题现在版本已经解决 ，bit类型和LONG是 查询还是插入有BUG?

**Comment by sunkaixuan** [comment]
bit long报错的原因也找到了， .UpdateColumns(it=>new DataTestInfo2() {  Bool1=false } ) 在Update时候不要使用匿名类  new{xx=xx}这是错误的写法 3.X才可以这么用

**Comment by sunkaixuan** [comment]
后期我会将提示做的更友好些

**Comment by sunkaixuan** [comment]
http://www.cnblogs.com/ovliverlin/archive/2007/11/26/972549.html  本地调了半天才发现不是ORM的问题

**Comment by sunkaixuan** [comment]
找到原因了，个别机器上能重现，已解决
