### ISSUE TITLE
插入 oracle 的 clob 字段 报错误  ORA-01704: 字符串文字太长

### ISSUE THREAD

**Issue by xilutian** [sunkaixuan/SqlSugar#252]

**Comment by sunkaixuan** [comment]
我插入了3万也没有报错，如果 有问题提供 DEMO发我邮箱 加上建表脚本

**Comment by sunkaixuan** [comment]
`    public class testclob
        {
            [SugarColumn(ColumnDataType = "clob")]
            public string clob { get; set; }
        }
        public static void Init()
        {
            var db = GetInstance();
            var x = "a";
            for (int u=0;u<30000;u++)
            {
                x=x+"a";
            }
            db.CurrentConnectionConfig.InitKeyType = InitKeyType.Attribute;
            db.CodeFirst.InitTables(typeof(testclob));
            db.Insertable(new testclob() {  clob=x}).ExecuteCommand();`
