### ISSUE TITLE
关于CodeFirst

### ISSUE THREAD

**Issue by 840900649** [sunkaixuan/SqlSugar#253]
根据CodeFirst生成表时， 生成都是不为NULL， 希望加一些简单判断。 比如string 可以为null, 主键不能为null，  DateTime?  可以为null 等等。。。。

  if (item.PropertyInfo.PropertyType.IsGenericType && item.PropertyInfo.PropertyType.GetGenericTypeDefinition() == typeof(Nullable<>))
                    {
                        item.IsNullable = true;
                    }

**Comment by sunkaixuan** [comment]
特性里面有isnull 设置
