### ISSUE TITLE
数据库关键字不能作为参数名

### ISSUE THREAD

**Issue by liuqiurong** [sunkaixuan/SqlSugar#254]
![image](https://user-images.githubusercontent.com/5915700/53300610-baa93280-3884-11e9-943d-e2234794e05e.png)
![image](https://user-images.githubusercontent.com/5915700/53300620-cf85c600-3884-11e9-91f2-9104b90c655f.png)

User是数据库的关键字，用作参数名的时候会报语法错误

**Comment by open-mfc** [comment]
同样，
建议作者 生成表别名的时候，加上[ ] 如：[user]

**Comment by jolboy** [comment]
这种问题其实华人orm框架本身无关,数据库表及字段的命名要规范,避开关键字!而不是让框架去迁就.

**Comment by sunkaixuan** [comment]
表和字段这些我都有处理，别名是你自个取的我暂时不处理，因为影响太多单元测试用例
