### ISSUE TITLE
DbFirst Mysql DataType:Time 转换为 System.DateTime 失败

### ISSUE THREAD

**Issue by kotoneme** [sunkaixuan/SqlSugar#256]
错误信息:Unable to convert MySQL date/time value to System.DateTime

MySQL 里的类型是 ~~`Date`~~`Time` 以前用EF是转成`System.Timespan` 的,但这里是`System.DateTime` 出错了
手动修改成`System.Timespan` 是可以的

2019-02-27 10:08 +8 更正

**Comment by kotoneme** [comment]
Mysql datetype : time、date、datetime、timestamp and year

**Comment by sunkaixuan** [comment]
支持了MYSQL time 转datetime ，近期会同步
