### ISSUE TITLE
建议DbFirst 预设自带SugarColumnAttribute - ColumnName

### ISSUE THREAD

**Issue by kotoneme** [sunkaixuan/SqlSugar#257]
数据库里的Columns 是小写的,希望能支持修改成大写,符合C#规范

    [SugarColumn(ColumnName = "userName")]
    /// <summary>
    /// Desc:
    /// Default:
    /// Nullable:False
    /// </summary>
    public DateTime UserName {get;set;}

**Comment by kotoneme** [comment]
暂时这样处理了

     db.DbMaintenance.GetTableInfoList().ForEach(table =>
     {
         db.DbMaintenance.GetColumnInfosByTableName(table.Name).ForEach(column =>
         {
            if (char.IsLower(column.DbColumnName.Substring(0, 1).ToCharArray()[0]))
            {
                string newcolumnName = column.DbColumnName.Substring(0, 1) + (column.DbColumnName.Length > 1 ? column.DbColumnName.Substring(1) : string.Empty);
                if (db.MappingColumns.FindIndex(f => f.DbColumnName.Equals(newcolumnName)) == -1)
                {
                    db.MappingColumns.Add(newcolumnName,column.DbColumnName,table.Name);
                }
            }
         });
     });

**Comment by kotoneme** [comment]
暂时这样处理了

     db.DbMaintenance.GetTableInfoList().ForEach(table =>
     {
         db.DbMaintenance.GetColumnInfosByTableName(table.Name).ForEach(column =>
         {
            if (char.IsLower(column.DbColumnName.Substring(0, 1).ToCharArray()[0]))
            {
                string newColumnName= column.DbColumnName.Substring(0, 1).ToUpper() + (column.DbColumnName.Length > 1 ? column.DbColumnName.Substring(1) : string.Empty);
                if (db.MappingColumns.FindIndex(f => f.DbColumnName.Equals(newColumnName)) == -1)
                {
                    db.MappingColumns.Add(newColumnName,column.DbColumnName,table.Name);
                }
            }
         });
     });

**Comment by sunkaixuan** [comment]
public DateTime UserName {get;set;}
这样就行了，数据库以标准建，实体类可以大写
