### ISSUE TITLE
timestamp 映射的时候有问题

### ISSUE THREAD

**Issue by mamingbo** [sunkaixuan/SqlSugar#26]
MSSQL 数据库，字段类型是timestamp  
实体里面的定义：
public DateTime LastUpdatedDateTime { get; set; }
var  list = SqlSugarClient.GetList<UsersInfo>("select * fromUsers"); 
  
错误信息：实体映射出错。
错误详情：指定的转换无效。

**Comment by sunkaixuan** [comment]
4.X还 是3.X

**Comment by sunkaixuan** [comment]
还有3.x不要使用db.getlist 尽量使用db.sqlquery

**Comment by mamingbo** [comment]
我用的还是  2.x
