### ISSUE TITLE
希望增加一个修改过滤接口

### ISSUE THREAD

**Issue by 840900649** [sunkaixuan/SqlSugar#261]
希望在UpdateableProvider 下增加以下接口。应用场景为数据权限控制时，指定用户修改字段权限，就只能拥有修改相应字段。类似InsertableProvider 类下的。 InsertColumns(string[] columns)

 public IUpdateable<T> UpdateColumns(string[] columns)
        {
            this.UpdateBuilder.DbColumnInfoList = this.UpdateBuilder.DbColumnInfoList.Where(it => columns.Contains(it.PropertyName, StringComparer.OrdinalIgnoreCase)).ToList();
            return this;
        }

**Comment by sunkaixuan** [comment]
已增加等同步
