### ISSUE TITLE
生成Sql时不支持C#新语法例如$符号

### ISSUE THREAD

**Issue by 1093439315** [sunkaixuan/SqlSugar#262]
例如使用如下的语句：
```       
var sql = DbContext.Updateable<Entity.Finance_RefundApply>()
                    .UpdateColumns(a => new Entity.Finance_RefundApply()
                    {
                        Editor = "系统",
                        AuditingUsetrSysNo = 33,
                        AuditingUserName = "系统",
                        AuditingTime = DateTime.Now,
                        BuissinessRefuseReason = $"系统同意退款!",
                        Status = auditStatus,
                        ActualRefundAmt = applyInfo.RefundAmt,
                    })
                    .Where(a => a.SysNo == applySysNo)
                    .ToSql();
```  
发现生成的Sql是这样：
```  
UPDATE [Finance_RefundApply]  
SET
[Status] = @Const6 , 
[AuditingUsetrSysNo] = @Const1 ,
[AuditingUserName] = @Const2 , 
[AuditingTime] = @Const3 , 
[BuissinessRefuseReason] = ISNULL(@MethodConst4, [Editor] = @Const0 , 
[ActualRefundAmt] = @Const7   
WHERE ( [SysNo] = @SysNo8 )
```  

希望能支持C#6.0字符串拼接新语法，这里我只用了$符号，不知其他地方是否还有同样问题

**Comment by open-mfc** [comment]
试试 改成这样
`var sql = DbContext.Updateable(new Entity.Finance_RefundApply()
                    {
                        Editor = "系统",
                        AuditingUsetrSysNo = 33,
                        AuditingUserName = "系统",
                        AuditingTime = DateTime.Now,
                        BuissinessRefuseReason = $"系统同意退款!",
                        Status = auditStatus,
                        ActualRefundAmt = applyInfo.RefundAmt,
                    })
                    .Where(a => a.SysNo == applySysNo)
                    .ToSql();`
