### ISSUE TITLE
全局过滤器无法清空

### ISSUE THREAD

**Issue by EmilyEdna** [sunkaixuan/SqlSugar#263]
当我在使用了QueryFilter.Clear()方法后;在查询QueryFilter.GeFilterList全局过滤器数量，Emily.QueryFilter.GeFilterList Count = 2然而并没有被清空。

**Comment by sunkaixuan** [comment]
你的代码有问题， 可能你并不是一个DB对象

**Comment by sunkaixuan** [comment]
我测过了可以的 var xx=xx.getdb();保证是一个DB对象

**Comment by EmilyEdna** [comment]
@sunkaixuan 我是构建的static db 按照文档上构建的不应该不是一个DB
