### ISSUE TITLE
自定义类型

### ISSUE THREAD

**Issue by JonyPengYJ** [sunkaixuan/SqlSugar#264]
[SugarColumn(ColumnDataType ="datetime2")]无法映射成数据库datetime2类型，DateTime.MinValue会报日期溢出错误。

**Comment by JonyPengYJ** [comment]
数据库是datetime2类型

**Comment by sunkaixuan** [comment]
实体要改成datetime?

**Comment by JonyPengYJ** [comment]
字段是datetime?类型的
