### ISSUE TITLE
支持分布式事务吗

### ISSUE THREAD

**Issue by JonyPengYJ** [sunkaixuan/SqlSugar#266]

**Comment by sunkaixuan** [comment]
支持

**Comment by the404** [comment]
想问下具体的原理能讲下吗,使用同一个connection 来实现的吧,和transactionscope的区别呢?如果这样可以实现,那干嘛要transactionscope这个类,有点觉得不可以思议

**Comment by JonyPengYJ** [comment]
你是？




------------------ 原始邮件 ------------------
发件人: "fox dan"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 中午11:47
收件人: "sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com>;
抄送: "紫觞"<605686104@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sunkaixuan/SqlSugar] 支持分布式事务吗 (#266)




想问下具体的原理能讲下吗,使用同一个connection 来实现的吧,和transactionscope的区别呢?如果这样可以实现,那干嘛要transactionscope这个类,有点觉得不可以思议
