### ISSUE TITLE
建议在MappingTableList里加个主键信息、自增信息

### ISSUE THREAD

**Issue by pengkai812** [sunkaixuan/SqlSugar#268]

**Comment by sunkaixuan** [comment]
SqlSugarClient db = new SqlSugarClient(new ConnectionConfig() {    
ConnectionString = Config.ConnectionString,    
DbType = DbType.SqlServer,    
IsAutoCloseConnection = true,    
ConfigureExternalServices=new ConfigureExternalServices() {    
EntityService = (property, column) => {    
    if(column.DbColumnName=="Id"){  column.isprimarykey=true }
},
