### ISSUE TITLE
MySQL CHAR(36)  无效

### ISSUE THREAD

**Issue by mamingbo** [sunkaixuan/SqlSugar#27]
数据库MYSQL、主键为CHAR(36)   实体接收的类型是Guid
查询 出来的值既然与实际DB 的值不一样
数据库值：da9462f9-b455-4a02-ac1c-3dfdc91f0b85
查询出来的值：00000001-62f9-da94-55b4-024aac1c3dfd  
不解

**Comment by sunkaixuan** [comment]
已经修复这个BUG

**Comment by mamingbo** [comment]
感谢！



mamingbowork@126.com
 
发件人： sunkaixuan
发送时间： 2017-07-25 22:36
收件人： sunkaixuan/SqlSugar
抄送： mamingbo; Author
主题： Re: [sunkaixuan/SqlSugar] MySQL CHAR(36) 无效 (#27)
已经修复这个BUG
