### ISSUE TITLE
关于设置全局过滤，生成Sql重复的问题。

### ISSUE THREAD

**Issue by dabftop** [sunkaixuan/SqlSugar#270]
//全局查询过滤IsDel为true
            Db.QueryFilter.Add(new SqlFilterItem()
            {
                FilterValue = f =>
                  {
                      return new SqlFilterResult() { Sql = "IsDel=0" };
                  },
                IsJoinQuery = false
            }).Add(new SqlFilterItem()
            {
                FilterValue = f =>
                {
                    return new SqlFilterResult() { Sql = "f.IsDel=0" };
                },
                IsJoinQuery = true
            });

//调用
Queryable<T>().Count()
的时候，生成sql出现重复的IsDel=0
SELECT Count(*) FROM `UpFileDirs`  WHERE **IsDel=0  AND IsDel=0**

**Comment by sunkaixuan** [comment]
应该是你ADD重复执行了，以参考我写的DEMO保证ADD不会重复执行
