### ISSUE TITLE
Select((it, f) => new { it,f.UserId})生成的sql别名错误

### ISSUE THREAD

**Issue by open-mfc** [sunkaixuan/SqlSugar#272]
**查询代码**
`var _list = DbRead.Queryable<EmployeeInfo, FaceInfo>((it, f) => new object[] {
                JoinType.Left, it.UserId == f.UserId })
                .With(SqlWith.NoLock)
                .Where(whereExpression)
                .OrderBy(orderExpression, isAsc ? OrderByType.Asc : OrderByType.Desc)
                .Select((it, f) => new { it, f.UserId, f.FaceImg, f.FaceToken })
                .ToPageList(pageIndex, pageSize, ref _count);`
**生成了这样的语句**
`SELECT * FROM (SELECT  [it].[employee_id] AS [EmployeeInfo.EmployeeId] , [it].[employee_name] AS [EmployeeInfo.EmployeeName] , [it].[mobile] AS [EmployeeInfo.Mobile] , [it].[is_admin] AS [EmployeeInfo.IsAdmin] , [it].[user_id] AS [EmployeeInfo.UserId] , [it].[brand_id] AS [EmployeeInfo.BrandId] , [it].[add_time] AS [EmployeeInfo.AddTime] , [it].[old_employee_id] AS [EmployeeInfo.OldEmployeeId] , [f].[user_id] AS [UserId] , [f].[face_img] AS [FaceImg] , [f].[face_token] AS [FaceToken] ,ROW_NUMBER() OVER(ORDER BY [it].[add_time] DESC) AS RowIndex  FROM [user_employee] it WITH(NOLOCK)  Left JOIN [user_face] f WITH(NOLOCK) ON ( [it].[user_id] = [f].[user_id] )   WHERE ( [it].[brand_id] = @BrandId0 )) T WHERE RowIndex BETWEEN 1 AND 10`

**我想象中 正确的sql应该是这样的**
`SELECT * FROM (SELECT  [it].[employee_id] AS [EmployeeId] , [it].[employee_name] AS [EmployeeName] , [it].[mobile] AS [Mobile] , [it].[is_admin] AS [IsAdmin] , [it].[user_id] AS [UserId] , [it].[brand_id] AS [BrandId] , [it].[add_time] AS [AddTime] , [it].[old_employee_id] AS [OldEmployeeId] , [f].[user_id] AS [UserId] , [f].[face_img] AS [FaceImg] , [f].[face_token] AS [FaceToken] ,ROW_NUMBER() OVER(ORDER BY [it].[add_time] DESC) AS RowIndex  FROM [user_employee] it WITH(NOLOCK)  Left JOIN [user_face] f WITH(NOLOCK) ON ( [it].[user_id] = [f].[user_id] )   WHERE ( [it].[brand_id] = @BrandId0 )) T WHERE RowIndex BETWEEN 1 AND 10`

**Comment by sunkaixuan** [comment]
升级过了吗

**Comment by open-mfc** [comment]
抱歉没注意消息，我用的 sqlSugar.4.9.9.1
