### ISSUE TITLE
CodeFirst数据库生成模型有功能缺陷

### ISSUE THREAD

**Issue by shinercan** [sunkaixuan/SqlSugar#279]
CodeFirst数据库生成模型
`Db.DbFirst.SettingNamespaceTemplate()`
不能修改生成的命名空间，只能修改Using的命名空间
只能通过下面这种方式指定namespace
```
Db.DbFirst.SettingClassTemplate(o=> 
return @"
{using}
namespace XXX.Infrastructure.Entities
{
{ClassDescription}{SugarTable}
    public partial class {ClassName}:BaseEntity
    {
            public {ClassName}(){

{Constructor}
            }
{PropertyName}
    }
}";
```

建议`Db.DbFirst.SettingNamespaceTemplate()`这个方法用指定namespace
另起一个方法`Db.DbFirst.SettingUsingTemplate()`替代原有`Db.DbFirst.SettingNamespaceTemplate()`的方法

**Comment by shinercan** [comment]
这一句不能单独设定指定：namespace XXX.Infrastructure.Entities

**Comment by sunkaixuan** [comment]
void CreateClassFile(string directoryPath,  string nameSpace = "Models");
