### ISSUE TITLE
模型增加属性导航，查询列表使用WithCache方法保存到Redis，从缓存读取数据序列化出错

### ISSUE THREAD

**Issue by xltuo** [sunkaixuan/SqlSugar#282]
对象增加一个导航属性查询子表相关数据，在获取对象列表的方法使用缓存。第一次可以正常查询数据并将结果集保存到Redis。第二次查询的时候使用缓存的数据。由于导航属性返回的是一个表达式，导致序列化失败。这种情况如果如何处理？

    public class tChlid
    {
        public string ParentID { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }

    }
    public class tParent : ModelContext
    {
        public string ID { get; set; }
        public string Name { get; set; }

        [SugarColumn(IsIgnore = true)]
        public List<tChlid> Child
        {
            get
            {
                return base.CreateMapping<tChlid>().Where(it => it.ParentID == this.ID).ToList();
            }
        }
    }

**Comment by sunkaixuan** [comment]
请使用mapper方式实现属性导航
