### ISSUE TITLE
[BUG] OnDiffLogEvent 中BeforeData与AfterData数据是一样的

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#283]
场景：
使用的sqlSugar版本为：4.9.9.3
使用读写分离模式
在更新时，日志记录BeforeData与AfterData数据是一样的，应该是在获取AfterData数据时，是取读库上的数据，这个时候，主库可能还没有同步数据到读库上。
代码：
 var i = db.Updateable<TestSelect>(entity).EnableDiffLogEvent().ExecuteCommand();

如果改成这样，就可以
 db.Ado.UseTran(()=> {
      var i = db.Updateable<TestSelect>(entity).EnableDiffLogEvent().ExecuteCommand();
});

后续：
测试Deleted与Insert的Diff，发现
1.Insert的Diff，只有AfterData有值，BeforeData=null，这个算正常。
2.Deleted的Diff，BeforeData的Count=0，AfterData=null，这个应该不正常

这些测试结果都是在 读写分离模式测试的。

**Comment by sunkaixuan** [comment]
这个近期会处理

**Comment by Cloud33** [comment]
谢谢，处理完通知我一下，我更新一下版本。

**Comment by sunkaixuan** [comment]
下周一前会更新，我这边已经改掉了

**Comment by Cloud33** [comment]
使用的sqlSugar版本为：4.9.9.4版本，不知道这个版本是否修复这个问题？
如果有修复
但测试发现，还是同样的问题。
@sunkaixuan
