### ISSUE TITLE
子查询时, 使用sum()方法报错问题

### ISSUE THREAD

**Issue by PorPit** [sunkaixuan/SqlSugar#284]
在子查询时  使用sum方法统计和时
如果 统计行==0  则会报错 
示例
.Select(t1=>new {
		totalAmount= SqlFunc.Subqueryable<DBAccess.Models.SaleCenter.t_Sale_PortSurChargeEntry>().Where(it=>it.FInterID==t1.FInterID).Sum(it=>it.FAmount),
	})

此时 t_Sale_PortSurChargeEntry 表 没有一条可用数据

报错:
`Newtonsoft.Json.JsonSerializationException:“Error converting value {null} to type 'System.Decimal'. Path 'totalAmount', line 1, position 219.”

InvalidCastException: 空对象不能转换为值类型。`

如果往t_Sale_PortSurChargeEntry表插入数据

则查询正常

我觉得正确情况下  查询不到数据 应该是返回0
或者是我操作不对?

**Comment by sunkaixuan** [comment]
已解决等发布 周一前发布
