### ISSUE TITLE
关于构造IConditionalModel之ConditionalCollections参数的bug

### ISSUE THREAD

**Issue by jolboy** [sunkaixuan/SqlSugar#285]
当多个ConditionalCollections构造条件时,同一个字段,构造参数化时,重名.
如:构造 (id=1 or id=2) and (id=3 or id=4),这样形态的组合,同一个ConditionalCollections不会重现参数重名,但不同的ConditionalCollections中,出现了重名.
错误如下:
#错误SQL:SELECT * FROM (SELECT *,ROW_NUMBER() OVER( ORDER BY GetDate() ) AS RowIndex  FROM [SYS_USER]  WHERE   USER_STATUS = @ConditionalUSER_STATUS0   AND (   USER_STATUS =  **@ConditionalUSER_STATUS1000**   )  OR (   USER_STATUS = **@ConditionalUSER_STATUS1000**   OR   USER_STATUS = @ConditionalUSER_STATUS2000   AND   USER_STATUS = @ConditionalUSER_STATUS3000   )  ) T WHERE RowIndex BETWEEN 1 AND 20
实例号:71dbfb00-b423-45f6-addf-6b77128c6ae0
  SqlSugar.SqlSugarException: 变量名 '@ConditionalUSER_STATUS1000' 已声明。变量名在查询批次或存储过程内部必须唯一。
必须声明标量变量 "@ConditionalUSER_STATUS2000"。

**Comment by sunkaixuan** [comment]
已解决 周一前发布
