### ISSUE TITLE
同一个SqlSugarClient中，先执行某个操作并使用了As(tableName) 后，后面调用其他操作时之前的As仍然有效

### ISSUE THREAD

**Issue by thinkif** [sunkaixuan/SqlSugar#286]
遇到问题的过程：

在一个操作中，先执行了 db.Insertable < T >().As(tableName) 的操作后，插入数据成功，此处T对应的表名与 As 的表名 tableName 不同。

紧接着执行 db.Queryable < T >() ，此处的T与插入操作的T 时同一个实体类，并且查询操作没调用As 方法。

执行结果时，即便 Queryable 并没有调用 As 方法，但是生成的SQL语句依然按照插入操作的As后的表名生成。

这样是危险的，两个独立的语句不应该产生联系。

**Comment by sunkaixuan** [comment]
As<T>(Name)

**Comment by sunkaixuan** [comment]
As《T》（name）

**Comment by thinkif** [comment]
抱歉我没明白您的回复
