### ISSUE TITLE
可能的cpu泄露问题

### ISSUE THREAD

**Issue by gebiWangshushu** [sunkaixuan/SqlSugar#287]
最新系统即将上线，压测发现：
某些操作极其耗费CPU资源，我模拟30个用户不间断访问某个接口，然后我发现我其中一台**CPU 24核**，**内存128G**的服务器CUP占用率持续超过98%，接口响应时间立刻从100多毫秒到20~30秒；

疑似CPU资源耗费查询：
```
Db.Queryable<PassportUser, PassportUserExpand>((u, e) => u.Pid == e.Pid)
                 .Where((u, e) => u.Phone.Equals(phone) && e.AuditPhone == true)
                 .Select<PassportUser>().First();
```

**sqlSugar: 4.9.8.1 
dotnet:  2.2.105
OS： centos 7.2**

忘作者有空抽个时间看看~

最后，diss .NET SqlSugar (3群),群号：654015377 的一个叫“公良子卿”的管理，
不认真审题，回答极不专业；
动不动给人随意定标签；
面对疑问，极尽嘲讽之词，譬如：你究竟懂不懂C#，你连Ado都不懂等等；
随意踢人；
![image](https://user-images.githubusercontent.com/27838829/54915600-7d42ce00-4f32-11e9-99e0-0791db2cd7dc.png)

**Comment by sunkaixuan** [comment]
很多人都说过CPU问题，最后基本都自个找到了问题，有的是REDIS什么引起的，有的是其它代码引起的。这个问题我是很难解答，sqlsugar ORM目前所有测试CPU占用率都是非常低的

**Comment by gebiWangshushu** [comment]
问题没有解决；
我当前业务连表查询不多，我把连表查询全都换成了2次查询，cup异常情况消失；

ps:我特地建立一个干净的Action，就只写两个表的连表查询，重现问题。
