### ISSUE TITLE
2个小功能,希望能加入

### ISSUE THREAD

**Issue by jolboy** [sunkaixuan/SqlSugar#289]
1、目前sugar中，无法修改表名，字段名倒是可以，希望可以增加这个方法。
2、创建字段时，DbColumnInfo.DataType的赋值，sugar不支持根据当前连接的数据库类型自动转，因为数据库可能会出现切换，或者同时支持多种数据库，动态建表建字段时，有些数据库用int，oracle可能就要用number，用ntext的可能就要用nclob，我觉得也不需要支持所有数据库字段的所有类型，常见常用的一些支持即可
去年在群里反应过，小杰说下个版本加进去，可能忘了(*^_^*)

**Comment by sunkaixuan** [comment]
int,number 可以用逗号格开，是可以多个的，还有修改表名的方法应该有了
