### ISSUE TITLE
Core 

### ISSUE THREAD

**Issue by duyanming** [sunkaixuan/SqlSugar#29]
`
            var list = baseRepository.db.Queryable<Model.sys_member, Model.bif_company>((m, c) => new object[] { SqlSugar.JoinType.Left, m.coid == c.id }).OrderBy((m)=>m.rdt,SqlSugar.OrderByType.Desc)
                .Select((m, c) => new Model.sys_member{ account=m.account, name=m.name, position=m.position, rdt=m.rdt, coid=m.coid,corpName=c.name}).ToList();`

 public partial class sys_member
    {
        [SugarColumn(IsIgnore = true)]
        public string corpName { get; set; }
    }

我的 sys_member   corpName 加了  [SugarColumn(IsIgnore = true)] 但是我 ew Model.sys_member{ account=m.account, name=m.name, position=m.position, rdt=m.rdt, coid=m.coid,**corpName=c.name})** 用的 是 Model.bif_company.name  取出来之后 是 NULL ，这应该和数据库 操作没关系 ，可我的 取值确实 Null

**Comment by sunkaixuan** [comment]
SugarColumn(IsIgnore = true 的列是查不出值的，所以不要混着用

**Comment by sunkaixuan** [comment]
你可以用 new{} 匿名类来实现你要的功能，在把匿类mapper到现在的类
