### ISSUE TITLE
数据库线程被占用

### ISSUE THREAD

**Issue by JerryMouseLi** [sunkaixuan/SqlSugar#290]
提示错误：
There is already an open DataReader associated with this Connection which must be closed first.
运行环境webapi，win10,win8 数据库 5.1.58，8.0.15，5.7.25多台电脑上试过都有这个问题。

同样的电脑连接到云上的webapi服务就没问题。

**Comment by sunkaixuan** [comment]
文档 释放数据库和线程安全，一般是你DB对象静态或者单例引起的，或者你没关数据库

**Comment by JerryMouseLi** [comment]
调试了三个晚上，问题我已经解决了，是数据库单例引起的，数据库生命周期我改成每次请求结束就解决了。
