### ISSUE TITLE
Oracle数据库，sqlsugar4.6版本多表查询.select()里面使用查询函数sqlfunc多次嵌套，解析的sql语句表别名丢失问题

### ISSUE THREAD

**Issue by sunyufeng** [sunkaixuan/SqlSugar#293]
`.Select ((rec, zd, scs, con, na, price, sbzd) => new NewModel(){
           SUFFIX.NO.Product = SqlFunc.IsNull (rec.SUFFIX.NO, SqlFunc.IIF (con.LB == 1, SqlFunc.IsNull (sbzd.FJBH, 111), SqlFunc.IsNull (price.SUFFIX.NO, 112)))
})`

上述代码里面select一个字段，用到了SqlFunc.IsNull ，SqlFunc.IIF等的嵌套，生成的sql语句里面 查询函数部分的sql语句con，sbzd，price等别名丢失，数据库执行报“未明确定义列”的错误

下面是代码截图和生成的sql语句截图，sql语句截图里面红色圈出来的别名是人为加上去的，sqlsugar生成的语句里面别名丢失了
![image](https://user-images.githubusercontent.com/5832610/55068904-cf642a80-50bd-11e9-8115-df3edb305f3c.png)
![image](https://user-images.githubusercontent.com/5832610/55068937-e6a31800-50bd-11e9-8476-d9328db03daa.png)

**Comment by sunkaixuan** [comment]
请用最新的测试，老版本的BUG都在新版本改了

**Comment by sunyufeng** [comment]
好的




| |
孙玉峰
邮箱：sunyufeng007@163.com
|

签名由 网易邮箱大师 定制

在2019年03月27日 19:28，sunkaixuan 写道：

Closed #293.
