### ISSUE TITLE
IN语法， 没有按照类型 IN 值，而是全部字符串，这样执行时SQL指令，会带来性能问题。

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#294]
![image](https://user-images.githubusercontent.com/10756986/55071799-8bc0ef00-50c4-11e9-995e-1a4cd2fd2965.png)
![image](https://user-images.githubusercontent.com/10756986/55071898-be6ae780-50c4-11e9-8f7b-68199c468d95.png)

**Comment by sunkaixuan** [comment]
你要知道参数化为什么提高性能，那是因为参数个数不会改变能够缓存执行计划，IN的参数位数是不固定长度的会引影响其它执行计划的缓存，因为执行计划缓存是有上限的，所以写成字符串反而对提高性能有好处，并且参数化上限只有有2000多个超过就会报错。我这么处理是非常合理的

**Comment by haibozhou1011** [comment]
执行计划，最终会自动进行类型转换，这样不消耗性能吗？
