### ISSUE TITLE
DbFirst.CreateClassFile 缺陷

### ISSUE THREAD

**Issue by FQLin** [sunkaixuan/SqlSugar#296]
`DbFirst.CreateClassFile` 生成的 `Model `没有为 ID （主键）添加
`[SugarColumn(IsPrimaryKey = true)]`，
这种情况下使用` Queryable<TEntity>().InSingle(key) `或者 `SimpleClient.GetById`的时候会出现异常：Only one primary key

**Comment by sunkaixuan** [comment]
没主键用不了这个方法，你这个KEY对应哪个字段呢

**Comment by FQLin** [comment]
> 没主键用不了这个方法，你这个KEY对应哪个字段呢

数据库里面是有主键的，都是`Guid(uniqueidentifier)`类型的字段，只是创建出来的 `cs`文件：
``` c#
/// <summary>
/// Desc:
/// Default:
/// Nullable:False
/// </summary>           
public Guid ID {get;set;}
```
在Model上是没有主键的，我需要手动添加一下
```c#
/// <summary>
/// Desc:
/// Default:
/// Nullable:False
/// </summary>          
[SugarColumn(IsPrimaryKey = true)] //手动添加部分
public Guid ID {get;set;}
```
才能不出现 `Only one primary key`异常。
能在`CreateClassFile `方法里面自动为主键加上`[SugarColumn(IsPrimaryKey = true)]`就完美了！
