### ISSUE TITLE
[建议]是否在读写分离模式下，查询可以强制指定主库

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#298]
是否在读写分离模式下，提供一个对象，可以在查询时，指定是从哪个库查询数据？默认是从库，但也可以强制使用主库进行查询，例如这样：
指定主库查询：
Db.Master.Queryable<Student>().Where(it => SqlFunc.ToLower(it.Name) == SqlFunc.ToLower("JACK")).ToList();

这样，有些对时间比较敏感数据，就可以这样解决。

**Comment by sunkaixuan** [comment]
db.Ado.IsDisableMasterSlaveSeparation=true 强制走主库  ，我这边已经实现了 ，近期会发布

**Comment by Cloud33** [comment]
这个好像没有更新到文档中！请问，这个设置是全局的，还是说存在上下文？需要手动关闭吗？
是像这样使用吗？

db.Ado.IsDisableMasterSlaveSeparation=true;
db.Queryable().Where(it => SqlFunc.ToLower(it.Name) == SqlFunc.ToLower("JACK")).ToList();
db.Ado.IsDisableMasterSlaveSeparation=false;

**Comment by sunkaixuan** [comment]
你写的是对的

**Comment by Cloud33** [comment]
这个是线程安全吗？能保证只有：
db.Queryable().Where(it => SqlFunc.ToLower(it.Name) == SqlFunc.ToLower("JACK")).ToList();
使用主库查询？
如果能这样写就更好，也更容易理解：
db.Master

**Comment by Cloud33** [comment]
@sunkaixuan  这样写在并发下，会出现问题吗？
