### ISSUE TITLE
mssql能否给个选项-分页改用offset fetch 

### ISSUE THREAD

**Issue by moneyfengcn** [sunkaixuan/SqlSugar#300]
MSSQL2014后面的版本offset fetch 分页性能更优，代码也更简洁。
数据库类型再可否加个枚举，enum mssqlVer{V2005,V2008,V2014,V2016,通用} 这样子，
根据具体版本，采用更新的语法，提升SQL性能。

另外，调用存储过程那里，能否改成类似dapper那样，可以给几个func<T1,T2,T2..>这样，挺多时候存储过程需要返回N张表的。

**Comment by sunkaixuan** [comment]
说offset fetch 快，那一定是自个没测过的，在排序列是主键或者索引列的情况下ROWNUMBER性能是最优的，http://www.codeisbug.com/Doc/8/1145

**Comment by moneyfengcn** [comment]
我确实在生产环境中试过，速度高约20%左右。
SQL 2014

sunkaixuan <notifications@github.com> 于2019年3月31日周日 上午9:40写道：

**Comment by sunkaixuan** [comment]
排序列有索引吗？

**Comment by moneyfengcn** [comment]
有的，倒序，整张表约3KW左右 翻页到最后面差距就出来了

sunkaixuan <notifications@github.com> 于2019年4月8日周一 下午7:40写道：
