### ISSUE TITLE
什么时候支持mysql 8.0?

### ISSUE THREAD

**Issue by penjay** [sunkaixuan/SqlSugar#301]
请问，为什么一个ORM要限制mysql的版本？

**Comment by sunkaixuan** [comment]
因为sqlsugar是framework 4.0 ， 8.0的驱动只能framework4.5用，并不是我要限制，你可以用源码自个编译

**Comment by sunkaixuan** [comment]
我也是考虑到更多低版本的用户可以使用

**Comment by penjay** [comment]
用源码编译就更新麻烦了，不是有一个sqlsugarCore吗？ 建议sqlsugarCore可否单独做一个分支支持8.0.15？

**Comment by penjay** [comment]
> 我也是考虑到更多低版本的用户可以使用

用源码编译就更新麻烦了，不是有一个sqlsugarCore吗？ 建议sqlsugarCore可否单独做一个分支支持8.0.15？

**Comment by sunkaixuan** [comment]
CORE你更新NUGET应该不影响吧

**Comment by chenbigit** [comment]
mysql8.0 链接的时候报 uthentication to host 'XXIP' for user 'root' using method 'caching_sha2_password' failed with message: Access denied for user 'root'@'XXIP' (using password: NO).
