### ISSUE TITLE
非常好的一个项目，不知是否支持以下功能：添加或修改时的事件，onInserting,onupdateing 

### ISSUE THREAD

**Issue by wuchao288** [sunkaixuan/SqlSugar#302]
1.添加或修改时的事件，onInserting,onupdateing ,应用场景有添加修改时统一设置某一个属性的值,比如记录修改的时间。（Npoco）
2,一条sql返回多个表,像dapper如下功能 
var sql =
@"
select * from Customers where CustomerId = @id
select * from Orders where CustomerId = @id
select * from Returns where CustomerId = @id";

using (var multi = connection.QueryMultiple(sql, new {id=selectedId}))
{
   var customer = multi.Read<Customer>().Single();
   var orders = multi.Read<Order>().ToList();
   var returns = multi.Read<Return>().ToList();
   ...
}
来自(dapper)
谢谢...

**Comment by sunkaixuan** [comment]
db.Aop.OnExecutingChangeSql = (sql, pars) => //SQL执行前 可以修改SQL
{
    return new KeyValuePair<string, SugarParameter[]>(sql,pars);
};
目前有这么个事件 ，后续会完善你提的一些功能点

**Comment by MonkSoul** [comment]
其实这个功能一直也想要，一个sql返回多个表。

**Comment by sunkaixuan** [comment]
返回多表已经有了 db.ado.sqlquery<T,T2>

**Comment by wuchao288** [comment]
> db.Aop.OnExecutingChangeSql = (sql, pars) => //SQL执行前 可以修改SQL
> {
> return new KeyValuePair<string, SugarParameter[]>(sql,pars);
> };
> 目前有这么个事件 ，后续会完善你提的一些功能点

非常好
