### ISSUE TITLE
读写分离，先读后写，写的时候，还是调用读库。

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#303]
读写分离，先读后写，写的时候，还是调用读库。
![image](https://user-images.githubusercontent.com/10756986/55319697-095f7300-54a8-11e9-9335-099d1666ff79.png)

**Comment by haibozhou1011** [comment]
感觉是读完后，CurrentConnectionString 没有恢复到写库，还是读库。

**Comment by sunkaixuan** [comment]
写个重现DEMO给我吧，不然我很难重现出问题

**Comment by haibozhou1011** [comment]
是要初始化IsDisableMasterSlaveSeparation ？

db.Ado.IsDisableMasterSlaveSeparation=false

**Comment by haibozhou1011** [comment]
不是这个原因！我写个DEMO！！

**Comment by haibozhou1011** [comment]
我自己写了一个简单的demo，怎么测试都可以，就是用仓储模式，然后依赖注入，就是不行。

**Comment by sunkaixuan** [comment]
db.CurrentConnectionConfig.Debugger = new SqlSugar.SugarDebugger() { EnableThreadSecurityValidation = true }; 声名SQLSUGAR的时候加上这句话，他会检测你代码线程是否安全，如果不安全会抛出错，就证明你的代码线程不安全

**Comment by sunkaixuan** [comment]
如果抛出了线程不安全错误就是你的DB跨线程使用了，保证一个线程一个DB对象，IOC有几种模式销毁模式单例模式等。

**Comment by sunkaixuan** [comment]
生产环境要删除  db.CurrentConnectionConfig.Debugger 这个代码有一定性能损耗

**Comment by haibozhou1011** [comment]
我试一下！

**Comment by haibozhou1011** [comment]
![image](https://user-images.githubusercontent.com/10756986/55326496-809e0280-54ba-11e9-8379-6bd41f08fa3a.png)

**Comment by haibozhou1011** [comment]
加上了这个 IsShardSameThread = true 应该是线程安全的吧！

**Comment by sunkaixuan** [comment]
加上 这个只能证明sqlconnection是安全的，不能证明sqlsugarclient是安全的

**Comment by sunkaixuan** [comment]
sqlsugarclient是不能给静态或者单例的

**Comment by sunkaixuan** [comment]
IOC如果是单例模式可能会出问题

**Comment by haibozhou1011** [comment]
![image](https://user-images.githubusercontent.com/10756986/55328616-5d298680-54bf-11e9-993a-a4a96516251c.png)
![image](https://user-images.githubusercontent.com/10756986/55328641-6c103900-54bf-11e9-98b1-b6360ceffb8c.png)
![image](https://user-images.githubusercontent.com/10756986/55328692-8518ea00-54bf-11e9-9777-b4e30c214b43.png)

**Comment by haibozhou1011** [comment]
Debugger 这些代码，有加过，没有报错。

**Comment by haibozhou1011** [comment]
Autofac 依赖注入 都是默认的。

**Comment by sunkaixuan** [comment]
你这不是默认的生命周期改成这个 InstancePerDependency

**Comment by haibozhou1011** [comment]
具体该哪一个注入的。

**Comment by sunkaixuan** [comment]
你现在用的是这个InstancePerLifetimeScope 换成InstancePerDependency

**Comment by haibozhou1011** [comment]
好的，我试一下！

**Comment by haibozhou1011** [comment]
试过了，老样子，就是执行了一个查询后，没有切换到写的链接。

**Comment by sunkaixuan** [comment]
你写个IOC的DEMO给我吧

**Comment by sunkaixuan** [comment]
没有完善的DEMO我很难测出来

**Comment by sunkaixuan** [comment]
还有SQLSUGAR要最新版本

**Comment by haibozhou1011** [comment]
确实也不好查，SQLSUGAR 是最新的。

**Comment by haibozhou1011** [comment]
我再想办法一下。没有办法再找您！感谢。辛苦！

**Comment by haibozhou1011** [comment]
刚刚看出来一点蹊跷，写入操作时，是会再次实例化SqlSugarClient 对象，但是写入操作之前的，查询表结构 读操作，是不会再次实例化对象，不知道是不是这个原因导致没有更新回 master 链接，这种可能在简单的demo是无法看出来，要在多次实例 SqlSugarClient 对象，才能出现问题。

**Comment by sunkaixuan** [comment]
INITKEY设置成attribute这种读特性模式就不会读系统表操作了

**Comment by sunkaixuan** [comment]
你可以改了确认一下，是不是这个引起的

**Comment by haibozhou1011** [comment]
这种我们开始就没有用特性，因为特性会使数据模型有依赖，一定要引用sqlsugar！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sunkaixuan <notifications@github.com>
发送时间: Monday, April 1, 2019 10:01:14 PM
收件人: sunkaixuan/SqlSugar
抄送: haibozhou1011; Author
主题: Re: [sunkaixuan/SqlSugar] 读写分离，先读后写，写的时候，还是调用读库。 (#303)


你可以改了确认一下，是不是这个引起的

―

**Comment by sunkaixuan** [comment]
`using OrmTest.Demo;
using OrmTest.Models;
using SqlSugar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OrmTest.Demo
{
    public class MasterSlave : DemoBase
    {

        public static void Init()
        {
            var db = GetMasterSlaveInstance();
            db.CurrentConnectionConfig.IsShardSameThread = true;
            Console.WriteLine("");
            for (int i = 0; i < 10; i++)
            {
            
                Console.WriteLine("开始");



                // var list2 = db.Insertable(new Student() { Name = "aa" }).ExecuteCommand();// ConnectionString2 or ConnectionString3
                db.Queryable<Student>().First();
                var list = db.Insertable(new Student() { Name = "aa" }).ExecuteCommand();
                var list2 = db.Insertable(new Student() { Name = "aa" }).ExecuteCommand();

            }
            //db.Insertable(new Student() { Name = "masterTest" }).ExecuteCommand();// Config.ConnectionString
            Console.WriteLine("saveable");
            GetMasterSlaveInstance().Saveable(new Student() { Name = "a" }).ExecuteCommand();
        }

        public static SqlSugarClient GetMasterSlaveInstance()
        {
            SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
            {
                ConnectionString = Config.ConnectionString,
                DbType = DbType.SqlServer,
                IsShardSameThread=true,
                IsAutoCloseConnection = true,
                SlaveConnectionConfigs = new List<SlaveConnectionConfig>() {
                     new SlaveConnectionConfig() { HitRate=10, ConnectionString=Config.ConnectionString2 } ,
                       new SlaveConnectionConfig() { HitRate=10, ConnectionString=Config.ConnectionString3 }
                }
            });
            db.Aop.OnLogExecuting = (sql, pars) =>
            {
                Console.WriteLine(db.Ado.Connection.ConnectionString);
            };
            return db;
        }
    }
}
`
重现不出来

**Comment by sunkaixuan** [comment]
我的代码一个方法只用了一个db 理论上你们依赖注入也是这样的一个线程是一个db对象才对

**Comment by sunkaixuan** [comment]
建议你把你的方法写精简点直接在你的方法里面new sqlsugarclient 进行测试

**Comment by sunkaixuan** [comment]
选把IOC放一放

**Comment by haibozhou1011** [comment]
![image](https://user-images.githubusercontent.com/10756986/55340197-c5379700-54d6-11e9-884d-2896944d7f2d.png)

**Comment by haibozhou1011** [comment]
找到原因了，但是就是不知道为什么会出现这样的问题。
![image](https://user-images.githubusercontent.com/10756986/55340660-b6051900-54d7-11e9-8c1c-a58e18eb819f.png)

**Comment by haibozhou1011** [comment]
OnExecutingChangeSql 委托里面，我改了一点东西，不知道为什么导致无法更新回，主库链接。

**Comment by haibozhou1011** [comment]
很奇怪，我试了一下各种写法，发现只要在里面加东西，就不行。不知道有什么特殊要求。

**Comment by sunkaixuan** [comment]
OnExecutingChangeSql  ，你加了什么代码

**Comment by haibozhou1011** [comment]
const string needReplaceDatabase = "(select database())";
                var database = "irobotbox";
                if (sql1.Contains(needReplaceDatabase))
                {
                    sql1 = sql1.Replace(needReplaceDatabase, $"'{database}'"); ;
                }

**Comment by haibozhou1011** [comment]
我加一段这样的代码是，是阿里云DRDS 中间件产品 特殊性，导致用 select database() 获取，数据库，跟我指定不一致，所以我加了一段代码。

**Comment by haibozhou1011** [comment]
我发现了问题所在.  应该是我把"(select database())" 替换了 没有 select 语句，导致没有切换主库。

**Comment by haibozhou1011** [comment]
const string needReplaceDatabase = "(select database())";
                var database = "irobotbox";
                if (sql1.Contains(needReplaceDatabase))
                {
                    sql1 = sql1.Replace(needReplaceDatabase, $"(select '{database}')");
                }

**Comment by haibozhou1011** [comment]
上面代码就可以了！

**Comment by haibozhou1011** [comment]
可以是，你的那个判断读的 正则表达式，有点小瑕疵吧！

**Comment by sunkaixuan** [comment]
正常ORM生成的 SQL应该没问题，你试着把替换的语法扔SQL后面执行，这样你暂时就可以用了

**Comment by sunkaixuan** [comment]
或者把 ()去掉，按正则的来

**Comment by sunkaixuan** [comment]
const string needReplaceDatabase = " select database() ； “;
