### ISSUE TITLE
使用的sqlSugar版本为：4.9.9.4版本，不知道这个版本是否修复这个问题？

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#310]
使用的sqlSugar版本为：4.9.9.4版本，不知道这个版本是否修复这个问题？
如果有修复
但测试发现，还是同样的问题。
@sunkaixuan

_Originally posted by @Cloud33 in https://github.com/sunkaixuan/SqlSugar/issues/283#issuecomment-478912988_

**Comment by sunkaixuan** [comment]
应该是修复了的，我在看看

**Comment by Cloud33** [comment]
好的，再问一下，有没有 db.Ado.IsDisableMasterSlaveSeparation=true 的使用文档，不知道这样设置，是在一次请求中生效，还是全局生效？

**Comment by sunkaixuan** [comment]
读写分离这个还存在问题吗 OnDiffLogEvent

**Comment by sunkaixuan** [comment]
已修复等同步

**Comment by Cloud33** [comment]
OnDiffLogEvent 功能，在Saveable下，还有一个问题。
![image](https://user-images.githubusercontent.com/8787198/55638902-d5af8080-57fa-11e9-9d24-7f5e8d376c8e.png)
