### ISSUE TITLE
关于嵌套子查询

### ISSUE THREAD

**Issue by tonyjianhu** [sunkaixuan/SqlSugar#311]
![image](https://user-images.githubusercontent.com/29139627/55461467-15be0a00-5627-11e9-8aef-7b9db9a8ad61.png)
这个语句，可以通过sqlsugar表达出来吗？
![image](https://user-images.githubusercontent.com/29139627/55461481-1f477200-5627-11e9-860b-46290032b48e.png)
这个字符串，其实是一个IQueryable<x,y,z>对象。。但是目前，要对这个对象 外部再嵌套一个 查询，并且分组。。好像写不出来

**Comment by sunkaixuan** [comment]
var q1 = db.Queryable<Student, School>((st,sc)=>new object[] {
                JoinType.Left,st.SchoolId==sc.Id
            }).Select((st, sc) => new ViewModelStudent4() { Id=st.Id, Name=st.Name,SchoolName=sc.Name });
 
var q2 = db.Queryable<School>();
 
 
var innerJoinList = db.Queryable(q1, q2, (j1, j2) => j1.Id == j2.Id).Select((j1, j2) => j1).ToList();//inner join
 
var leftJoinList = db.Queryable(q1, q2,JoinType.Left, (j1, j2) => j1.Id == j2.Id).Select((j1, j2) => j1).ToList();//left join

**Comment by tonyjianhu** [comment]
> var q1 = db.Queryable<Student, School>((st,sc)=>new object[] {
> JoinType.Left,st.SchoolId==sc.Id
> }).Select((st, sc) => new ViewModelStudent4() { Id=st.Id, Name=st.Name,SchoolName=sc.Name });
> 
> var q2 = db.Queryable();
> 
> var innerJoinList = db.Queryable(q1, q2, (j1, j2) => j1.Id == j2.Id).Select((j1, j2) => j1).ToList();//inner join
> 
> var leftJoinList = db.Queryable(q1, q2,JoinType.Left, (j1, j2) => j1.Id == j2.Id).Select((j1, j2) => j1).ToList();//left join

您好。您发的答案，我还存有一些疑问：
1、var q2 = db.Queryable();//貌似没有无参数构造函数
2、又因为没有空的构造函数，所以我这样写：var q2= db.Queryable<LoadBalanceRange>();

![image](https://user-images.githubusercontent.com/29139627/55467343-adc1f080-5633-11e9-8a8b-f467fbe5ef4e.png)


最后抛出此异常：
SqlSugar.UtilExceptions: SqlSugarException.NotSupportedException：FullConditionalExpression

**Comment by sunkaixuan** [comment]
不是最新版本

**Comment by tonyjianhu** [comment]
> 不是最新版本

更新了最新版本，4.9.9.6
还是有问题。首先
var q2 = db.Queryable();//貌似没有无参数构造函数
第二，我通过此方法解决问题了
![image](https://user-images.githubusercontent.com/29139627/55469788-cb458900-5638-11e9-84ad-517893c1b508.png)
