### ISSUE TITLE
建议增加复杂对象查询功能

### ISSUE THREAD

**Issue by young312** [sunkaixuan/SqlSugar#313]
1.先说多对多情况

    public class Club{
         public string  Id{ get; set;}
         public string  Name{ get; set; }

         //其他属性
          .....

          [SugarAssociateTable("club_student")] //此特性标注多对多关系中间表
           public   List<Student>  Students { get; set; }   //兴趣小组与学生是多对多关系
    }
    
    public class Student{

         public string  Id{ get; set;}

        public string Name{ get; set; }

        public int Age {get; set;}

        [SugarAssociateTable("club_student")] //此特性标注多对多关系中间表
        public List<Club> Clubs{ get; set;}
    }    

    public class StudentOut {
         public string Name{ get; set; }

         public int Age {get; set;}
    }   

    public class ClubOut{
         public string Name{ get; set; }
         public List<StudentOut> Students{ get; set;} //这里StudentOut可以替换成Student类型
    }
能否实现类似 SqlSugarClient.Queryable&lt;Club>(where).OrderBy(sort).MapperSelect&lt;ClubOut>().ToList();
where 条件可以是 t => t.Name ="AA" && t.Students.Age >10 && t.Students.Age <15
可以直接查询出ClubOut里面含有StudentOut的对象

2.接下来是一对多，一对一情形，相对简单

     public class Class{
          public string  Id{ get; set;}

         public string  Name{ get; set; }

         public List<Student> Students { get; set;}  //班级学生一对多关系
    }

    public class ClassOut{
          public string  Name{ get; set; }

          public List<StudentOut> Students { get; set;}  //班级学生一对多关系
    }

SqlSugarClient.Queryable&lt;Class>(where).MapperSelect&lt;ClassOut>().ToList();
同理和多对多一样输出ClassOut模型，一对一情形应该更简单

不知能否实现这种变态需求。。。

**Comment by sunkaixuan** [comment]
后续会加的
