### ISSUE TITLE
OnDiffLogEvent 功能，在Saveable下，还有一个问题。

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#314]
OnDiffLogEvent 功能，在Saveable下，还有一个问题。
![image](https://user-images.githubusercontent.com/8787198/55638902-d5af8080-57fa-11e9-9d24-7f5e8d376c8e.png)

应该是，如果使用Saveable做Update操作，就不会进入OnDiffLogEvent 中。
补充一下代码：
![image](https://user-images.githubusercontent.com/8787198/55639088-32ab3680-57fb-11e9-9574-fe2b90962433.png)

_Originally posted by @Cloud33 in https://github.com/sunkaixuan/SqlSugar/issues/310#issuecomment-480319626_

**Comment by sunkaixuan** [comment]
已解决等发布
