### ISSUE TITLE
多表查询bug

### ISSUE THREAD

**Issue by loveyeguo** [sunkaixuan/SqlSugar#319]
官方文档中有个例子是这样的：
![image](https://user-images.githubusercontent.com/7542451/55863667-9479f080-5bad-11e9-83a6-b1ec32c2b9e5.png)

我发现，当st,也就是Student表中含有一个字段，其属性为  [SugarColumn(IsIgnore = true)]时,
方法执行将会出现堆栈溢出错误

**Comment by loveyeguo** [comment]
请注意 这个 [SugarColumn(IsIgnore = true)]  含有二级对象 ： 例如
[SugarColumn(IsIgnore = true)]
public  school  bindSchool{get;set;}

**Comment by sunkaixuan** [comment]
该功能已经放到5.X版本中完成了，会在今年下半年发布
[SugarColumn(IsIgnore = true,NoSerialize=true)]
public school bindSchool{get;set;}
