### ISSUE TITLE
模糊查询 Contains 方法生成语句bug

### ISSUE THREAD

**Issue by coolxlc** [sunkaixuan/SqlSugar#320]
发现在使用Contains 方法模糊查询时，生成的Sql语句在%后和前各加了一个‘，’逗号 。如： `(`ConGuid` like concat('%',@MethodConst1,'%'))`   我用的是Mysql 数据库 V5.6.26， .net Core 2.2项目
![bug01](https://user-images.githubusercontent.com/1211869/55888272-ae352b00-5be1-11e9-99b1-c82f5b864965.png)
![bug2](https://user-images.githubusercontent.com/1211869/55888273-aecdc180-5be1-11e9-8088-cb226f26fe6a.png)

**Comment by coolxlc** [comment]
后来我升级SqlSugar版本为4.9.97 也是报相同的错误

**Comment by sunkaixuan** [comment]
生成的sql没问题 报什么错

**Comment by sunkaixuan** [comment]
Can cat是个拼字符串函数

**Comment by coolxlc** [comment]
查不出期望的结果 ，用sql语句是可以查出的。很奇怪，我在搜索文章的地方也用了Contains 能查出结果

**Comment by AtlantisDe** [comment]
我也遇到了 冒汗

**Comment by derily** [comment]
如果是Contains((string)params.searchword)这种就会有问题 生成的sql是 like concat('%',searchword,‘%’)，其中模糊关键字不带引号报语法错误

**Comment by AtlantisDe** [comment]
反正我是用 自定义sql 自己写个函数处理解决的 其它没有去深的挖掘.. 
好像有些 拉达姆 没支持....的很完全 还有就是 系统的一些常见函数 直接用上去 不能正确 完全的 解析为sql语句 
我后来是写 函数 生成 sql 去解决的 反正问题点在哪里我也忘记了
