### ISSUE TITLE
百思不得其解，分页时，报这个错误。

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#321]
[SqlSugarException]: English Message : Entity mapping error.未将对象引用设置到对象的实例。
Chinese Message : 实体与表映射出错。未将对象引用设置到对象的实例。
   在 SqlSugar.Check.Exception(Boolean isException, String message, String[] args)
   在 SqlSugar.DbBindAccessory.GetEntityList[T](SqlSugarClient context, IDataReader dataReader)
   在 SqlSugar.DbBindProvider.DataReaderToList[T](Type type, IDataReader dataReader)
   在 SqlSugar.QueryableProvider`1.GetData[TResult](KeyValuePair`2 sqlObj)
   在 SqlSugar.QueryableProvider`1._ToList[TResult]()
   在 SqlSugar.QueryableProvider`1.ToList()
   在 SqlSugar.QueryableProvider`1.ToPageList(Int32 pageIndex, Int32 pageSize)
   在 SqlSugar.QueryableProvider`1.<>c__DisplayClass124_0.<ToPageList>b__0()
   在 SqlSugar.UtilMethods.GetOldValue[T](T value, Action action)
   在 SqlSugar.QueryableProvider`1.ToPageList(Int32 pageIndex, Int32 pageSize, Int32& totalNumber)

**Comment by haibozhou1011** [comment]
单元测试项目测试时不会有问题，但是web项目就报这个错误。

**Comment by sunkaixuan** [comment]
这个是数据引起的，就是类体类型和库不一致，用DBFIRST生成实体这样是最为标准，或者你找出哪条数据引起的

**Comment by sunkaixuan** [comment]
如果手动改库类型需要重启IIS

**Comment by haibozhou1011** [comment]
有可能，修改了链接地址，没有重启IIS!
