### ISSUE TITLE
更新操作 where 条件包含子查询 SQL 出错

### ISSUE THREAD

**Issue by FQLin** [sunkaixuan/SqlSugar#323]
`C#`代码
```c#
this._db.Updateable<Picture>()
                        .UpdateColumns(p => p.Value == SqlFunc.Subqueryable<Picture>()
                                                .Where(pp => pp.ID == newCarTypePictureId)
                                                .Select(pp => pp.Value))
                        .Where(p => p.ID == carTypePictureId)
                        .ExecuteCommand();
```
生成的`SQL`：
```sql
UPDATE [Picture]  SET
            [Value] =(SELECT TOP 1 [Value] FROM [Picture] WHERE ( [ID] = @ID0 )【这个位置少一个")"】   WHERE ( [ID] = @ID1 )
```

**Comment by sunkaixuan** [comment]
实体类能发一下吗

**Comment by sunkaixuan** [comment]
还有版本是最新版本吗

**Comment by FQLin** [comment]
我升级到最新版本`4.9.9.7`确实还会出现这个问题

```c#
    public partial class Picture
    {
           public Picture(){


           }
           /// <summary>
           /// Desc:
           /// Default:
           /// Nullable:False
           /// </summary>           
           [SugarColumn(IsPrimaryKey = true)]public Guid ID {get;set;}

           /// <summary>
           /// Desc:
           /// Default:
           /// Nullable:False
           /// </summary>           
           public byte Type {get;set;}

           /// <summary>
           /// Desc:
           /// Default:
           /// Nullable:False
           /// </summary>           
           public string Value {get;set;}

    }
```

**Comment by yuzhigang5460** [comment]
这个问题很大，请尽快更新一下。更新操作基本废了。

**Comment by yuzhigang5460** [comment]
wherecolumns方法也有问题，生成的where条件变成了key的，而不是指定的

**Comment by yuzhigang5460** [comment]
这个问题巨大，请尽快修复。上个版本是没问题的，最新版本有问题。我怀疑是引入saveable的updatewherecolmuns方法引起的。

测试用例写的太简单了，每次更新都发现问题

**Comment by yuzhigang5460** [comment]
wherecolumns更新也有问题，指定的条件某些情况下无效，直接使用了主键作为where

**Comment by sunkaixuan** [comment]
WHERE  columns出错你代码怎么写的，最近会发布一个版本

**Comment by yuzhigang** [comment]
·await this.DbContext.Updateable(jobPlans)
                    .WhereColumns(s => new { s.CmdNo }).UpdateColumns(s => new
                    {
                        s.HeatNo,
                        s.CmdNo
                    }).ExecuteCommandAsync();·

**Comment by sunkaixuan** [comment]
实体发一下

**Comment by yuzhigang** [comment]
`
    /// <summary>
    /// 表示作业计划表，保存用户确认的作业计划。
    /// </summary>
    [SugarTable("PL_JOB_PLAN")]
    public class JobPlan
    {
       public long Id{get;set;}

        /// <summary>
        /// 获取或设置炉次号。
        /// </summary>
        public string HeatNo { get; set; }


        /// <summary>
        /// 获取或设置制造命令号。
        /// </summary>
        [SugarColumn(ColumnName = "PONO")]
        public string CmdNo { get; set; }
}
`
ID在数据库中是主键，自增，oracle触发器之类的已经配置好（通过aop），这里不会有问题。
生成对应的sql语句为：
UPDATE "PL_JOB_PLAN"  SET
           "HEAT_NO"=:HEAT_NO  WHERE "ID"=:ID

似乎WhereColmns并没有被使用。

**Comment by yuzhigang** [comment]
jobPlans 是列表，这个实体列表中的每个实体不带有主键。

**Comment by sunkaixuan** [comment]
我测没没毛病

**Comment by sunkaixuan** [comment]
UPDATE S SET S.[HeatNo]=T.[HeatNo] FROM [PL_JOB_PLAN] S    INNER JOIN             (

 SELECT NULL AS [HeatNo],NULL AS [PONO]
UNION ALL
 SELECT NULL AS [HeatNo],NULL AS [PONO]


            ) T ON S.[PONO]=T.[PONO]
                ;
生成的SQL也OK

**Comment by yuzhigang5460** [comment]
你测试的异步方法吗？同步方法没问题，异步有

**Comment by yuzhigang5460** [comment]
为啥您生成的sql语句这么复杂，如何写的update语句。

**Comment by sunkaixuan** [comment]
批量生成的SQL是这样子的

**Comment by sunkaixuan** [comment]
UPDATE [PL_JOB_PLAN]  SET
           [HeatNo]=@HeatNo  WHERE [PONO]=@PONO
{"@HeatNo":null,"@PONO":null}  单条生成这样的也没问题

**Comment by sunkaixuan** [comment]
上面的问题已经改过了，我在周一前会发布新版本

**Comment by yuzhigang** [comment]
经过断点测试，发现逻辑问题出在这里。
测试代码：
```csharp
 public async Task Do()
        {
            var me = DbFactory.Build(DbFactory.ME);
            var items = new List<ManufacturePlan>(2);
                 //items.Add(new ManufacturePlan()
            //{
            //    CmdNo = "D908863",
            //    HeatNo = "1931003384"
            //});
            items.Add(new ManufacturePlan()
            {
                CmdNo = "D908864",
                HeatNo = "1932003516"
            });
            await me.Updateable(items)
             .WhereColumns(s => new { s.CmdNo })
             .UpdateColumns(s => new
             {
                 s.HeatNo,
             }).ExecuteCommandAsync();
        }
[SugarTable("PL_JOB_INFO")]
    public class ManufacturePlan
    {
        public long Id { get; set; }

        [SugarColumn(ColumnName = "PONO")]
        public string CmdNo { get; set; }

        public string HeatNo { get; set; }

        [SugarColumn(ColumnName = "PONO_STATE")]
        public int CmdState { get; set; }

    }

```
触发条件：
items的List类型，且items的Count 为1.
导致：
UpdateBuilder  进入 ToSingleSqlString 方法，该方法（第224行）：

`    if (this.WhereValues.HasValue())`

为空，导致直接使用PrimaryKeys来确定Where条件，所以会出现我上面所说的错误。

`else if (PrimaryKeys.HasValue())`

UPDATE "PL_JOB_INFO"  SET
           "HEAT_NO"=:HEAT_NO  WHERE "ID"=:ID

目前Oracle是有错误的。

**Comment by yuzhigang** [comment]
#328
