### ISSUE TITLE
建议Guid类型对应sqlite的uniqueidentifier类型

### ISSUE THREAD

**Issue by moumingtao** [sunkaixuan/SqlSugar#325]
看了下EF生成的表，GUID对应的是uniqueidentifier类型，只占16个字节，比较好用

**Comment by sunkaixuan** [comment]
SQLITE  本身只有四个类型，uniqueidentifier也是假的 都是扩展类型

**Comment by sunkaixuan** [comment]
你也可以通过特性强制指定 ColumnDataType  ="uniqueidentifier"

**Comment by moumingtao** [comment]
这只在CodeFirst生成表的时候有用吧，查询的时候数据库的uniqueidentifier并不能成功转换成C#的Guid
