### ISSUE TITLE
更新字段时间精确到毫秒

### ISSUE THREAD

**Issue by foxfolk** [sunkaixuan/SqlSugar#327]
更新字段时间精确到毫秒  upsertable如何实现

**Comment by sunkaixuan** [comment]
这个要看你的数据库和和你的数据库字段类型

**Comment by foxfolk** [comment]
mysql数据库  字段类型  datetime(3)  upsertable进去后，显示为2019-04-18 16:00:05.000;
多次尝试，毫秒显示都是000

**Comment by sunkaixuan** [comment]
可能我的MYSQL库比较老没法设置你的类型，你看看   updateObj.CreateTime = DateTime.Now;
     
            var t1 = db.Updateable(updateObj).UpdateColumns(it=> new { it.CreateTime}).ExecuteCommand(); 这行写可以不， 如果用表达式解析的可能是now()，理论上要new(3)
