### ISSUE TITLE
批量打包Sql出现问题

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#329]
我这边有四个查询，使用SaveQueues执行时，如果有些SQL没有查询数据，就会报错：
![image](https://user-images.githubusercontent.com/8787198/56400988-4b026300-6289-11e9-99b4-fe349ec88c89.png)

可能是因为没有结果的原因？我拿到SQL执行执行，确定有四个结果，其中三个结果是没有数据的。

**Comment by Cloud33** [comment]
不知道会不会有统一的问题，如果查询没有数据，在填充时，就会出现这个问题？

**Comment by sunkaixuan** [comment]
有几个查询用几个T，明白不

**Comment by sunkaixuan** [comment]
和查不出数据没有关系，还有你用的是哪个数据库，可能不同数据库驱动原理存在差异

**Comment by sunkaixuan** [comment]
select * from xx
insert xx;
select * from xxx 
 这样是3个操作，只有2个T

**Comment by Cloud33** [comment]
我明白你的意思。
我使用的是MSSQL 2014.
我有四个查询，也有四个T，但是我只有前一个查询有数据，后面三个都是空的数据，我先确定一下吧，如果有问题，我再提交ISSUES。

**Comment by Cloud33** [comment]
@sunkaixuan  这个问题已经找出来了，**我有些SQL在执行的过程中会出一些错误，但是错误的级别不高，不会影响最终的查询结果**，这个错误发现在，我有一个查询结果是放在一个本地的临时表中，然后每次查询前都会把这个临时表清空掉，但是没有做判断，所以在执行第一次查询会出现临时表不存在的错误。

但是SqlSugar误导了我，所以我一直在查，我的结果集数量是否正确！查了都是确定的。

**所以这个地方，我觉得可以去改进，需要抛出真实的错误出来。**

把判断临时表是否存在的SQL加上，就不会出现这个问题了。
