### ISSUE TITLE
[建议]在类似 UseTranAsync 方法中添加第二个参数，来处理事务中发生的异常

### ISSUE THREAD

**Issue by FQLin** [sunkaixuan/SqlSugar#330]
我在使用 UseTranAsync 方法的时候发生的异常是在返回结果中，
这样我还需要判断事务的处理结果来记录异常（或者是对异常的一些其他操作），能不能添加一个重载 类似于：
```c# 
Task<DbResult<bool>> UseTranAsync(Action action[,Action<Exception> exptionHandler]);
```
在事务出错的时候调用 `exptionHandler` 让用户处理异常，省下来我的多步判断操作。
甚至`异常`不用放在结果里面，直接使用 `handler` 委托交由调用者处理，就类似于 `JS` 中的`callback`回调。
望采纳

**Comment by FQLin** [comment]
把`异常`从结果中剔除好像有点欠妥...

**Comment by sunkaixuan** [comment]
var asyncResult = db.Ado.UseTranAsync(() =>
            {
 
                var beginCount = db.Queryable<Student>().ToList();
                db.Ado.ExecuteCommand("delete student");
                var endCount = db.Queryable<Student>().Count();
                throw new Exception("error haha");
            });
            asyncResult.Wait();
if(asyncResult.IsSuccess){}   返回值当然给你封装好了

**Comment by FQLin** [comment]
我的意思就是不想写 `if(asyncResult.IsSuccess){//doing something}` 这种判断，由程序内部来完成这个判断操作，
发生异常的时候自动调用我的第二个参数委托（即上面写的`Action<Exception> exptionHandler`）。

**Comment by sunkaixuan** [comment]
可以可以
