### ISSUE TITLE
如何对没有实体的表进行插入数据

### ISSUE THREAD

**Issue by a83302493** [sunkaixuan/SqlSugar#331]
如何对没有实体的表进行插入数据

**Comment by sunkaixuan** [comment]
db.insertable(字典).exec


字典类型 string,object

**Comment by a83302493** [comment]
//var dt =new List< Dictionary<string, object>>();
        //    var i = Db.Insertable(dt).AS(tablename).ExecuteCommand();
我这样是插入一条还是多条
