### ISSUE TITLE
[Bug] 使用WhereColumns 的异步更新出错

### ISSUE THREAD

**Issue by yuzhigang** [sunkaixuan/SqlSugar#332]
@sunkaixuan 
经过断点测试，发现逻辑问题出在这里。
测试代码：
```csharp
      public async Task Do()
        {
            var me = DbFactory.Build(DbFactory.ME);
            var items = new List<ManufacturePlan>(2);
                 //items.Add(new ManufacturePlan()
            //{
            //    CmdNo = "D908863",
            //    HeatNo = "1931003384"
            //});
            items.Add(new ManufacturePlan()
            {
                CmdNo = "D908864",
                HeatNo = "1932003516"
            });
            await me.Updateable(items)
             .WhereColumns(s => new { s.CmdNo })
             .UpdateColumns(s => new
             {
                 s.HeatNo,
                s.CmdNo
             }).ExecuteCommandAsync();
        }
    [SugarTable("PL_JOB_INFO")]
    public class ManufacturePlan
    {
        public long Id { get; set; }

        [SugarColumn(ColumnName = "PONO")]
        public string CmdNo { get; set; }

        public string HeatNo { get; set; }

        [SugarColumn(ColumnName = "PONO_STATE")]
        public int CmdState { get; set; }

    }

```
触发条件：
**items为List类型，且items的Count 为1， 且为异步调用ExecuteCommandAsync**
导致：
UpdateBuilder类 进入 ToSingleSqlString 方法（实际期望进入**TomultipleSqlString方法**）。该方法（第224行）：

`    if (this.WhereValues.HasValue())`

为空，因为WhereColumns指定的列都不会在WhereValues列表里存在。

为空则会使用PrimaryKeys来确定Where条件，所以会出现我上面所说的错误。

`else if (PrimaryKeys.HasValue())`

UPDATE "PL_JOB_INFO"  SET
           "HEAT_NO"=:HEAT_NO  WHERE "ID"=:ID

期望的语句为：
UPDATE "PL_JOB_INFO" SET "HEAT_NO"=N'1931003739' WHERE  "PONO"=N'D909867'

PrimaryKeys为啥为默认的表主键Id，而不是期望的PONO？ 

```csharp
public Task<int> ExecuteCommandAsync()
        {
            Task<int> result = new Task<int>(() =>
            {
                IUpdateable<T> asyncUpdateable = CopyUpdateable();
                return asyncUpdateable.ExecuteCommand();
            });
            TaskStart(result);
            return result;
        }
```

此方法调用后， this.WhereColumnList 为null。辛辛苦苦clone的UpdateBuilder，其PrimaryKeys在第427行付之一炬。

而items的个数大于1时就不会出现问题，以OracleUpdateBuilder为例，其TomultipleSqlString平不会直接使用PrimaryKeys（此时为默认的表主键ID，而不是期望的PONO），而是使用DbColumnInfoList中IsPrimary为true的列，逃过一劫。

我的跟踪调试，不一定正确，仅供参考。今天因为这个问题折腾了一天，十分郁闷。

_Originally posted by @yuzhigang in https://github.com/sunkaixuan/SqlSugar/issues/323#issuecomment-485110387_

**Comment by sunkaixuan** [comment]
断网了近期会看

**Comment by sunkaixuan** [comment]
已解决等今晚发布，
