### ISSUE TITLE
【feedback】是否可以对WhereIF提供关于IConditionalModel的重载支持及关于or条件符

### ISSUE THREAD

**Issue by yshbchenlie** [sunkaixuan/SqlSugar#334]
![图片](https://user-images.githubusercontent.com/12081681/56573553-f0079d80-65f3-11e9-8899-1235946bfa77.png)

反馈
IConditionalModel 不能实现多层 or条件 或者尚无此类示例
例如 select * from table where field1 = '1' and ( field2 = '2' or field3 = '3' or ( field4 = '4' and field5 = '5'))

**Comment by sunkaixuan** [comment]
可以的，后续加上
