### ISSUE TITLE
建议配置增加默认缓存时间

### ISSUE THREAD

**Issue by kingflyok** [sunkaixuan/SqlSugar#335]
对于二级缓存增加默认配置时间

**Comment by sunkaixuan** [comment]
SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
            {
                ConnectionString = Config.ConnectionString,
                DbType = DbType.SqlServer,
                IsAutoCloseConnection = true,
                ConfigureExternalServices = new ConfigureExternalServices()
                {
                    DataInfoCacheService = myCache //Setting external cache service
                },
                MoreSettings=new ConnMoreSettings {
                    DefaultCacheDurationInSeconds=10
                }
            });等发布

**Comment by kingflyok** [comment]
好的，谢谢
