### ISSUE TITLE
非常希望查询能返回IEnumerable<T>

### ISSUE THREAD

**Issue by moumingtao** [sunkaixuan/SqlSugar#336]
查询数据后，常常需要对数据进行类型转化或者进行一下遍历操作，这种情况不必要产生一个List对象。List对象会缓存查询出来的所有结果，这种情况只需要返回IEnumerable<T>，然后用foreach遍历就可以了。

**Comment by sunkaixuan** [comment]
IEnumerable<T> xx=db.quryable.tolist()

**Comment by wuuer** [comment]
> 请问现在是否有IEnumerable 的方法么？ list只是IEnumerable的一个非常狭隘的实现，IEnumerable可以非常大，最大值可以是无限的，对于非常大的结果用list并不合适，会oom的

应该是说能不能stream流式传输，一个一个返回, 用foreach一个一个接，将内部new list的过程暴露出来。如果ADO.net有这种实现的话可以实现
