### ISSUE TITLE
启用事务，异步插入无响应

### ISSUE THREAD

**Issue by moumingtao** [sunkaixuan/SqlSugar#337]
![image](https://user-images.githubusercontent.com/40648342/56707191-7209da80-674a-11e9-9c65-5ef616f4d29e.png)

我用的sqlite数据库，上面那样写可以正常执行异步Insert，下面那样写异步Insert无响应。我拉完屎回来，过了十多分钟，也不抛异常，也没任何反应，代码就停在这个断点的位置。
![image](https://user-images.githubusercontent.com/40648342/56707122-396a0100-674a-11e9-8a13-4d3a78ccbfc2.png)
同步Insert是没问题的。

**Comment by sunkaixuan** [comment]
异步事务内只要用同步方法就行了，这样整体就是一个异步

**Comment by sunkaixuan** [comment]
异步事务内不能用异步方法
