### ISSUE TITLE
建议增加对uniqueidentifier类型的默认值newid()的判断

### ISSUE THREAD

**Issue by lenghun** [sunkaixuan/SqlSugar#338]
使用t4模板生成的的guid默认值是Guid.Parse("newid()"),
看了源码对时间类型有判断是getdate()是会转为DateTime.Now,
guid也可以做同样简单的转换,自己改了判断为newid()时转为Guid.NewGuid()生成的也能用,
但是习惯全部通过NuGet管理引用,希望能加上这一判断

**Comment by sunkaixuan** [comment]
已更新 ，等发布

**Comment by TomLiu-GitHub** [comment]
DefaultValue ="newid()"  这样设置的默认值是不是就是 文本'newid()'
