### ISSUE TITLE
如果在条件上使用Enum，无法怎么操作，都是识别为int

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#343]
代码：
`Db.Queryable<xxxxxxx>().Where(t =>SqlFunc.Equals(t.Type, Level.User.ToString())).AddQueue();`

这样的查询，条件是int类型的值，所以是索引，后面写的ToString()是没有效果的
需要这样写，才有作用：
```
var type=Level.User.ToString();
Db.Queryable<xxxxxxx>().Where(t =>SqlFunc.Equals(t.Type, type)).AddQueue();
```

**Comment by sunkaixuan** [comment]
已解决等发布
