### ISSUE TITLE
Whereif 时间不同系统格式不一致

### ISSUE THREAD

**Issue by xiaguoli** [sunkaixuan/SqlSugar#344]
![image](https://user-images.githubusercontent.com/10445205/56859433-77229000-69bd-11e9-9ba7-243eca10f050.png)

![image](https://user-images.githubusercontent.com/10445205/56859441-96b9b880-69bd-11e9-966a-ba712be6feb9.png)

**Comment by sunkaixuan** [comment]
用参数化的方式，你这种字符串方式不行的
