### ISSUE TITLE
希望SqlSugarClient.ConfigureExternalServices.EntityService过滤时可以可以用table+column的方式过滤

### ISSUE THREAD

**Issue by nocanstillbb** [sunkaixuan/SqlSugar#345]
**现在**
                ConfigureExternalServices = new ConfigureExternalServices
                {
                    EntityService = (property, column) => {
                        column.IsIgnore = (new List<string>
                        {
                            **"Column"**
                        }).Any(a => a == property.Name);
                    },
                }
**想要**
                ConfigureExternalServices = new ConfigureExternalServices
                {
                    EntityService = (property, column) => {
                        column.IsIgnore = (new List<string>
                        {
                            **"Table.Column"**
                        }).Any(a => a == property.Name);
                    },
                }

**Comment by sunkaixuan** [comment]
column.TableName
