### ISSUE TITLE
.net core preview4 提示   实体与表映射出错。Bad IL format

### ISSUE THREAD

**Issue by xmlijia** [sunkaixuan/SqlSugar#348]
“SqlSugar.SqlSugarException”类型的异常在 SqlSugar.dll 中发生，但未在用户代码中进行处理
English Message : Entity mapping error.Bad IL format.
Chinese Message : 实体与表映射出错。Bad IL format. 

原本preview 3的时候是正常的，今天装了preview4 ，再运行就这个错误了！
我用的是sqlite
id类字段用的是integer类型，原本在代码里定义的是int，现在改成long就可以
但是nvarchar之类的字段就不能用string，也找不到c#有什么类型是代表字符串的。
目前测试
decimal、bool、自定义enum类型、datetime这几个类型不影响使用，跟之前是一样的
string会出错

**Comment by sunkaixuan** [comment]
这个暂时不处理，等正式版我在处理
