### ISSUE TITLE
新下载的DEMO，SqlLite报错

### ISSUE THREAD

**Issue by xingwen1987** [sunkaixuan/SqlSugar#35]
![image](https://user-images.githubusercontent.com/15207100/33305224-0895dbb2-d448-11e7-82e1-e17c1b1051a5.png)
SqlSugar.UtilExceptions:“English Message : Connection open error . unable to open database file
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：unable to open database file.”

**Comment by sunkaixuan** [comment]
连接字符串的路径不对，手动修改一下
