### ISSUE TITLE
关于SqlSugar诸多Bug问题

### ISSUE THREAD

**Issue by taozx1** [sunkaixuan/SqlSugar#351]
我看源码的时候发现几个问题  例如DataRead 未释放；Oracle 获取队列号逻辑也不对 插入后再获取当前队列的值，多线程下这个又是插入后关闭连接然后再开启的连接 这个查询的值会不对啊。

**Comment by sunkaixuan** [comment]
用不用这个我管不了，datareader怎么可能不释放呢，https://github.com/sunkaixuan/SqlSugar/blob/dev/Src/Asp.Net/SqlSugar/Abstract/DbBindProvider/DbBindProvider.cs  public virtual List<T> DataReaderToList<T>(Type type, IDataReader dataReader) 这个方法，数据库对象本来就是保证一个线程一个db对象又何来你说的ORACLE的问题

**Comment by taozx1** [comment]
Oracle队列比较建议先获取值然后插入再之前获取的值作为返回值，目前情况在微服务的情况下 有多个服务在使用一个数据库的 Sequence时 ，例如服务A 插入调用Sequence 当前值为4 这个时候b服务调用了 值成了5 这个时候A服务查询所得就是5了。

**Comment by taozx1** [comment]
https://github.com/sunkaixuan/SqlSugar/blob/dev/Src/Asp.NetCore2/SqlSeverTest/SqlSugar/Abstract/DbBindProvider/DbBindAccessory.cs 


        protected List<T> GetValueTypeList<T>(Type type, IDataReader dataReader)
        {
            List<T> result = new List<T>();
            while (dataReader.Read())
            {
                var value = dataReader.GetValue(0);
                if (type == UtilConstants.GuidType)
                {
                    value = Guid.Parse(value.ToString());
                }
                if (value == DBNull.Value)
                {
                    result.Add(default(T));
                }
                else if (type.IsEnum)
                {
                    result.Add((T)Enum.Parse(type, value.ObjToString()));
                }
                else
                {
                    result.Add((T)Convert.ChangeType(value, UtilMethods.GetUnderType(type)));
                }
            }
            return result;
        }
    }

**Comment by sunkaixuan** [comment]
public virtual List<T> DataReaderToList<T>(Type type, IDataReader dataReader)
        {
            using (dataReader)
            {
                if (type.Name.Contains("KeyValuePair"))
                {
                    return GetKeyValueList<T>(type, dataReader);
                }
                else if (type.IsValueType() || type == UtilConstants.StringType || type == UtilConstants.ByteArrayType)
                {
                    return GetValueTypeList<T>(type, dataReader);  
               }
看代码不要看局部，你看看getvalueType的外面包的是什么

**Comment by sunkaixuan** [comment]
至于你说的序列问题，第一插入时数据库默认会锁表，第一个执行的也是第一个插入的后SELECT，因为其它INSERT给之前的第一个插入锁入进了 ,当然分2次写目前用户并没出现过问题，不过如果你有更好的一次性返回序列的方法我也可以改，目前我是没找到更好写法
