### ISSUE TITLE
SqlFunc.Substring解析问题..

### ISSUE THREAD

**Issue by lupming** [sunkaixuan/SqlSugar#354]
Id = SqlFunc.MergeString(Utils.GetDateStr,SqlFunc.Substring(SqlFunc.GetRandom(), 2, 12)),
 
![image](https://user-images.githubusercontent.com/17874973/57264813-b3817a80-70a6-11e9-8137-548b80df22dd.png)

 我现在是sqlsugarcore4.9.9.10,mysql8.0.15

**Comment by sunkaixuan** [comment]
近期会修复

**Comment by sunkaixuan** [comment]
已修复近2天会发布
