### ISSUE TITLE
Updateable<T>希望增加自动过滤所有默认值相同的参数

### ISSUE THREAD

**Issue by xueandfeng** [sunkaixuan/SqlSugar#355]
类似这种
db.Updateable<User>(updateObj).IgnoreColumns(ignoreAllNullColumns:true).ExecuteCommand();
updateObj 实体类和User实体类是不同的。
只需要有个设置updateObj 里面字段只要为null的值 自动过滤掉字段不修改.
要不然现在只能一个一个的
![图片](https://user-images.githubusercontent.com/20178645/57284262-666fc980-70e3-11e9-851d-975ac0848f68.png)
比较繁琐

**Comment by MonkSoul** [comment]
请看文档：

IgnoreColumns(ignoreAllNullColumns:true)

**Comment by xueandfeng** [comment]
这种是需要updateObj对象和Updateable<T> 的泛型T的实体要一样。我现在是2个实体不一样。前提还需要数据库实体需要设置int?这种。才支持过滤的

**Comment by sunkaixuan** [comment]
已经添加，过几天会发布新版本，多加了一个参数重载
