### ISSUE TITLE
codefirst 不支持owner用户

### ISSUE THREAD

**Issue by andyz168** [sunkaixuan/SqlSugar#356]
比如oralcle会有很多用户create user a;
默认配置是User ID=system 那创建的表就是在system用户下

**Comment by andyz168** [comment]
SugarColumn， 是否可以在此加个属性叫userid 在创建表的时候生成sql :create table {userid}.{tablename}

**Comment by sunkaixuan** [comment]
`
SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
{
    ConnectionString = Config.ConnectionString,
    DbType = DbType.SqlServer,
    IsAutoCloseConnection = true,
    InitKeyType=InitKeyType.Attribute,
    ConfigureExternalServices = new ConfigureExternalServices()
    {
     
        EntityNameService = (type, entity) =>
        {
           entity.DbTableName=“userid.”+entity.DbTableName;
        }
    }
});
`
这样看看行不

**Comment by andyz168** [comment]
> `
> SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
> {
> ConnectionString = Config.ConnectionString,
> DbType = DbType.SqlServer,
> IsAutoCloseConnection = true,
> InitKeyType=InitKeyType.Attribute,
> ConfigureExternalServices = new ConfigureExternalServices()
> {
> 
> ```
>     EntityNameService = (type, entity) =>
>     {
>        entity.DbTableName=“userid.”+entity.DbTableName;
>     }
> }
> ```
> 
> });
> `
> 这样看看行不

codefirst取到的表名称不对

**Comment by andyz168** [comment]
[SqlSugar.SugarTable("auser.equ_work_hours_bak1")]
    public class EquWorkHours

**Comment by sunkaixuan** [comment]
经过测试这样可以了           SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
            {
                DbType = DbType.SqlServer,
                ConnectionString = Config.ConnectionString,
                InitKeyType = InitKeyType.Attribute,
                IsAutoCloseConnection = true,
                ConfigureExternalServices=new ConfigureExternalServices() {
                    EntityNameService = (p, n) => {
                        n.DbTableName = "xx."+p.Name;
                    }
                }
            });

**Comment by andyz168** [comment]
> 经过测试这样可以了 SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
> {
> DbType = DbType.SqlServer,
> ConnectionString = Config.ConnectionString,
> InitKeyType = InitKeyType.Attribute,
> IsAutoCloseConnection = true,
> ConfigureExternalServices=new ConfigureExternalServices() {
> EntityNameService = (p, n) => {
> n.DbTableName = "xx."+p.Name;
> }
> }
> });
这样相当于写死了，并不是很方便，相当于全局的。那我要切换用户就得改一次
