### ISSUE TITLE
4.9.9.10上面写支持.net4.0但是实际不支持

### ISSUE THREAD

**Issue by kelyljk** [sunkaixuan/SqlSugar#357]
![image](https://user-images.githubusercontent.com/10511872/57495886-c1333c00-7302-11e9-8087-d2d6f489bea4.png)
![image](https://user-images.githubusercontent.com/10511872/57495892-c7291d00-7302-11e9-95c6-e1157a70ea6c.png)

**Comment by sunkaixuan** [comment]
这个是你JSON.NET的问题 NUGERT安装合适的JSON.NET就好
