### ISSUE TITLE
SqlSugar在Mysql中使用 SqlFunc.IIF时候拼接字段的问题

### ISSUE THREAD

**Issue by Hello-Mango** [sunkaixuan/SqlSugar#36]
Code：
` SqlFunc.IIF<String>(s1.RESERVATION_SEX == "0", s1.RESERVATION_NAME + "女士", s1.RESERVATION_NAME + "先生")` 

SQL：
` SELECT
	RESERVATION_COUSULTANT_ID AS RESERVATION_COUSULTANT_ID,
	RESERVATION_TIME AS RESERVATION_TIME,
	RESERVATION_SEX,
	RESERVATION_MOBILE AS RESERVATION_MOBILE,
	(
		CASE
		WHEN (RESERVATION_SEX = '0') THEN
			(
				RESERVATION_NAME + '女士'
			)
		ELSE
			(
				RESERVATION_NAME + '先生'
			)
		END
	) AS RESERVATION_NAME,
	RESERVATION_QUESTION AS RESERVATION_QUESTION
FROM
	c_reservation_cousultant_t
ORDER BY
	RESERVATION_TIME DESC
LIMIT 0,
 10` 
在这里如果在MYSQL里 应该是要使用Concat进行拼接才有效果

**Comment by sunkaixuan** [comment]
SqlFunc.MagreString()
