### ISSUE TITLE
多表查询 报SqlException

### ISSUE THREAD

**Issue by pangmer** [sunkaixuan/SqlSugar#360]
System.Data.SqlClient.SqlException
查了很久文档都不行，报错信息也不显示，恳请帮助
查询语句
![image](https://user-images.githubusercontent.com/25192663/57573286-061cb700-7458-11e9-9e6e-1221e8a35995.png)

![image](https://user-images.githubusercontent.com/25192663/57573310-5ac03200-7458-11e9-9284-7bb5f4550c8a.png)

表结构
![image](https://user-images.githubusercontent.com/25192663/57573294-264c7600-7458-11e9-9631-eacffaca3e9f.png)

![image](https://user-images.githubusercontent.com/25192663/57573297-2f3d4780-7458-11e9-925e-3932424c2ace.png)

**Comment by sunkaixuan** [comment]
打上try catch就能拿到错误信息了，这个和你的VS异常设置关系，打上TRY CATCH 看什么错

**Comment by sunkaixuan** [comment]
知道什么错了 别名不要取关键字  user这个是关键字， (re,u)=>这样就OK了
