### ISSUE TITLE
建议支持唯一键自动判断

### ISSUE THREAD

**Issue by billsking** [sunkaixuan/SqlSugar#361]
开发中遇到个问题，应该是普遍存在的问题。比如，用户表的用户名要求唯一的。所以，当新增用户时需要判断用户名是否唯一。其他业务的字段也有可能有相似的需求。我已经实现了相关功能，觉得大神可以将此功能加到项目中去。部分代码如下，供参考：
`var type = entity.GetType();
                var properties = type.GetProperties();
                foreach (var propertyInfo in properties)
                {
                    if (propertyInfo.IsDefined(typeof(DbValidAttribute), false))
                    {
                        var dbvalid = (DbValidAttribute)propertyInfo.GetCustomAttribute(typeof(DbValidAttribute));
                        if (dbvalid.IsUnique)
                        {
                            var sql = $"select count(1) from {type.Name} where {propertyInfo.Name}='{propertyInfo.GetValue(entity)}'";
                            if (context.Db.Ado.GetInt(sql)>0)
                            {
                                return new ApiResult<string>{Code = ResponseCode.DataExist};
                            }
                        }
                    }
                }`

**Comment by billsking** [comment]
原理就是判断是否有IsUnique特性， 有的话，就拼接sql去查询是否已经存在相同的数据。

**Comment by klg111** [comment]
select count(1) from {type.Name} where {propertyInfo.Name}='{propertyInfo.GetValue(entity)}'
判断记录是否存在，建议不用count统计，而用top性能更高：
select top(1) 1 from {type.Name} where {propertyInfo.Name}='{propertyInfo.GetValue(entity)}'
