### ISSUE TITLE
异常信息：拉姆达解析出错：不支持ArrayIndex此种运算符查找。

### ISSUE THREAD

**Issue by Larpx** [sunkaixuan/SqlSugar#362]
- 数据库：SQLServer 2016
- SQLSugar版本：4.9.9.10
- .Net Framework:4.7
- 系统环境：Windows10

问题描述：做查重操作（以一个URL为参数，检查该URL是否已经在表中存在）时引发异常，这个URL是一个网盘地址（https://pan.baidu.com/s/1wSC0qRzNke3XXyAnyEbe-w），异常内容为

> SqlSugarException.NotSupportedException：English Message : Lambda parsing error: ArrayIndex does not support the operator to find!
> Chinese Message : 拉姆达解析出错：不支持ArrayIndex此种运算符查找！

**Comment by sunkaixuan** [comment]
给个提取密码

**Comment by sunkaixuan** [comment]
这个错也很清楚了就是 数组[i] 这种操作不支持，可以提取到表达式外面来
