### ISSUE TITLE
[BUG] ModelContext属性导航问题

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#363]
我在使用属性导航时，发现有两个问题
sqlSugar版本：4.9.9.10
1.如果Model使用了ModelContext，然后指定主库查询：
```
Db.Ado.IsDisableMasterSlaveSeparation = true;
xxxxx
Db.Ado.IsDisableMasterSlaveSeparation = false;
```
发现，只有主Model使用主库查询，子查询走的是从库。

2.像这种子查询，并没有在AOP日志存在，无法通过AOP日志获取子查询的执行信息。

**Comment by sunkaixuan** [comment]
不推荐用这个东西，建议用mapper,后续会修复

**Comment by sunkaixuan** [comment]
已修复近2天内会发布
