### ISSUE TITLE
ReSetValue支持不传对象的使用方式吗？

### ISSUE THREAD

**Issue by FQLin** [sunkaixuan/SqlSugar#364]
我想把一个`bool`类型的字段在`true`和`false`之间相互转换
我的代码：
```c#
            Program._db.Updateable<CarType>()
                .UpdateColumns(c => new { c.State })
                .ReSetValue(c => c.State == !c.State)
                //.Where(c => c.ID == id)
                .ExecuteCommand();
```
这种方式生成的`sql`会报错。
还是只能类似
```c#
db.Updateable(updateObj)
.ReSetValue(it => it.Name == (it.Name + 1)).ExecuteCommand();
```
使用对象的方式调用才可以吗？
[demo](https://github.com/FQLin/AllTest/blob/master/SqlSugar/TestDemo/UpdateDemo.cs)

**Comment by sunkaixuan** [comment]
你试试c.state?true:false

**Comment by FQLin** [comment]
修改成：
```c#
            Program._db.Updateable<CarType>()
                .UpdateColumns(c => new { c.State })
                .ReSetValue(c => c.State == (c.State ? true : false))
                //.Where(c => c.ID == id)
                .ExecuteCommand();
```
这次还是：
`System.Data.SqlClient.SqlException:“Must declare the scalar variable "@State".”`

[https://github.com/FQLin/AllTest/blob/master/SqlSugar/TestDemo/UpdateDemo.cs](https://github.com/FQLin/AllTest/blob/master/SqlSugar/TestDemo/UpdateDemo.cs)

**Comment by sunkaixuan** [comment]
var t8 = db.Updateable(updateObj)
                .UpdateColumns(it => new Student{ Name=it.Name，state=it.state?true:false }).Where().ExecuteCommand();更新到最新版本试试这写法

**Comment by sunkaixuan** [comment]
ReSetValue 在5.X会加上过期标签不建议用了

**Comment by FQLin** [comment]
> 
> 
> ```
> var t8 = db.Updateable()
>             .UpdateColumns(it => new CarType{  State =it.State ?true:false }).Where(c => c.ID == id).ExecuteCommand();更新到最新版本试试这写法
> ```

`sqlSugarCore`的版本是`4.9.9.10`最新版
代码：
```c#
            Program._db.Updateable<CarType>()
            .UpdateColumns(it => new CarType { State = (it.State ? true : false) })
            //.Where(c => c.ID == Guid.Empty)
            .ExecuteCommand();
```
异常：
```c#
SqlSugar.SqlSugarException
  HResult=0x80131500
  Message=SqlSugarException.ArgumentNullException：UpdateColumns Parameter error, UpdateColumns(it=>new T{ it.id=1}) is valid, UpdateColumns(it=>T) is error
  Source=SqlSugar
  StackTrace:
   at SqlSugar.Check.ArgumentNullException(Object[] checkObj, String message)
   at SqlSugar.UpdateableProvider`1.UpdateColumns(Expression`1 columns)
   at TestDemo.UpdateDemo.Update3() in E:\GitHub\AllTest\SqlSugar\TestDemo\UpdateDemo.cs:line 34
   at TestDemo.Program.Main(String[] args) in E:\GitHub\AllTest\SqlSugar\TestDemo\Program.cs:line 39

```

**Comment by sunkaixuan** [comment]
Db.Updateable<CarType>()
                  .UpdateColumns(it => new CarType { State =SqlSugar.SqlFunc.IIF(it.State==true,false,true) }).Where(it=>true)
               .ExecuteCommand(); 先这么用，后续我完善表达式

**Comment by sunkaixuan** [comment]
已修复近期会同步
