### ISSUE TITLE
 var t10 = db.Updateable<Student>() .UpdateColumns(it => new Student() { Name = "a", CreateTime = DateTime.Now }) .Where(it => it.Id == 11).ExecuteCommand(); 无法执行

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#37]
var t10 = db.Updateable<Student>() .UpdateColumns(it => new Student() { Name = "a", CreateTime = DateTime.Now }) .Where(it => it.Id == 11).ExecuteCommand(); 无法执行

提示 值 为null

**Comment by sunkaixuan** [comment]
我的源码可以通过

**Comment by haibozhou1011** [comment]
我是封装成 Repository 模式，然后在业务层调用就报错！直接用时没有问题。

**Comment by haibozhou1011** [comment]
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;
using IrobotBox.Infrastructure.Model;
using IrobotBox.Infrastructure.Repository.Base.IBaseRepository;

namespace IrobotBox.Infrastructure.Repository.Base.BaseRepository
{
    public partial class Repository<TModel, TPrimaryKey> : IRepository<TModel, TPrimaryKey>
        where TModel : class, IModel<TPrimaryKey>, new()
    {
        public int Update(TModel model)
        {
            return DbClient.Updateable<TModel>(model).ExecuteCommand();
        }
        
        public int Update(Expression<Func<TModel, bool>> whereEpression, Expression<Func<TModel, object>> updateColumns)
        {
            
            return DbClient.Updateable<TModel>().UpdateColumns(updateColumns).Where(whereEpression).ExecuteCommand();
        }

        public int Update(IEnumerable<TModel> models)
        {
            return DbClient.Updateable<TModel>(models).ExecuteCommand();
        }

        public async Task<int> UpdateAsync(TModel model)
        {
            return await DbClient.Updateable<TModel>(model).ExecuteCommandAsync();
        }
        public async Task<int> UpdateAsync(Expression<Func<TModel, bool>> whereEpression, Expression<Func<TModel, object>> updateColumns)
        {

            return await DbClient.Updateable<TModel>().UpdateColumns(updateColumns).Where(whereEpression).ExecuteCommandAsync();
        }
        public async Task<int> UpdateAsync(IEnumerable<TModel> models)
        {
            return await DbClient.Updateable<TModel>(models).ExecuteCommandAsync();
        }
    }
}

**Comment by haibozhou1011** [comment]
public int Update(Expression<Func<TModel, bool>> whereEpression, Expression<Func<TModel, object>> updateColumns)
        {
            
            return DbClient.Updateable<TModel>().UpdateColumns(updateColumns).Where(whereEpression).ExecuteCommand();
        }
调用这个方法就报错！

**Comment by haibozhou1011** [comment]
public void Update(long id)
        {
            _sysUserRepository.Update(m => m.Id == id, m => new Sys_User { UserName = "abcdef" });
        }
业务层，是这样调的。

**Comment by haibozhou1011** [comment]
![qq 20171211201643](https://user-images.githubusercontent.com/10756986/33830728-4395bbe8-deb0-11e7-8996-2ff3b71cb3f0.png)

**Comment by haibozhou1011** [comment]
报错是上图所示！
