### ISSUE TITLE
CodeFirst时MappingTables好像没用正常工作

### ISSUE THREAD

**Issue by lindenrty2** [sunkaixuan/SqlSugar#370]
CodeFirst建表时MappingTables好像没用正常工作，会抛异常提示表（映射后表名）找不到

**Comment by sunkaixuan** [comment]
看看你的实体类和你的代码 ，写个简单的示例

**Comment by lindenrty2** [comment]
改回去不重现了，可能和某些环境因素有关，下次再发生的事情再研究一下
