### ISSUE TITLE
希望增加对参数表达式查询条件的支持

### ISSUE THREAD

**Issue by doson2006** [sunkaixuan/SqlSugar#371]
` var db = DbFactory.GetSqlSugarClient();
            db.Deleteable<SysUser>().Where(a => new List<int> { 1, 2, 3 }.Where(b => b > 1).Contains(a.Uuid))
                .ExecuteCommand();` 这样的写法必须要改成` var db = DbFactory.GetSqlSugarClient();
            var list = new List<int> {1, 2, 3}.Where(b => b > 1);
            db.Deleteable<SysUser>().Where(a => list.Contains(a.Uuid))
                .ExecuteCommand();`  这样 才可以

**Comment by sunkaixuan** [comment]
已修复等更新
