### ISSUE TITLE
oracle数据库decimal类型，数据中是0值，但是读取出来时是一个很大的值

### ISSUE THREAD

**Issue by sxf359** [sunkaixuan/SqlSugar#372]
使用的是oracle12, vs2017

这种值5029493556076512432695017472.0在数据库中是0，但是读取出来在更新语句中就变成这么大了。
这是读取语句的写法： 
var query = DbDaka.Queryable<Base_Customers>().Where(m => m.SCARDSNR == bc.SCARDSNR);
//NlogHelper.LogInfo("query:" + (query==null));
var model2 = query.First();

[2019-05-23 18:33:40.3951][DEBUG][common]UPDATE "BASE_CUSTOMERS"  SET
           "CUSTOMERID"=:CUSTOMERID,"SCARDSNR"=:SCARDSNR,"CARDTYPEDETAILID"=:CARDTYPEDETAILID,"CARDSN"=:CARDSN,"STATUS"=:STATUS,"QUERYPWD"=:QUERYPWD,"CARDKIND"=:CARDKIND,"COUNTRYID"=:COUNTRYID,"ELECTROPCOUNT"=:ELECTROPCOUNT,"ELECTRSAVEOPCOUNT"=:ELECTRSAVEOPCOUNT,"MONOPCOUNT"=:MONOPCOUNT,"MONSAVEOPCOUNT"=:MONSAVEOPCOUNT,"SUMELECTRADDFAREACC"=:SUMELECTRADDFAREACC,"SUMELECTRADDFARE"=:SUMELECTRADDFARE,"SUMMONADDFAREACC"=:SUMMONADDFAREACC,"SUMCONSUMFARE"=:SUMCONSUMFARE,"SUMELECTRCONSUMFARE"=:SUMELECTRCONSUMFARE,"SUMMONCONSUMFARE"=:SUMMONCONSUMFARE,"SUMELECTRDUMMYFARE"=:SUMELECTRDUMMYFARE,"SUMMONRUSHFARE"=:SUMMONRUSHFARE,"SUMDISCOUNT"=:SUMDISCOUNT,"ELECTRODDFARE"=:ELECTRODDFARE,"ELECTRODDFAREACC"=:ELECTRODDFAREACC,"NOUSEDATE"=:NOUSEDATE,"EMPID"=:EMPID,"YEARCHECKS"=:YEARCHECKS,"CHECKBEGINDAY"=:CHECKBEGINDAY,"CHECKENDDAY"=:CHECKENDDAY,"VER"=:VER,"SUMMONTHODDFAREACC"=:SUMMONTHODDFAREACC,"DEPRECIATEFARE"=:DEPRECIATEFARE,"DEPRECIATEDATE"=:DEPRECIATEDATE,"SUMELECTRADDDUMMYFARE"=:SUMELECTRADDDUMMYFARE,"REFUNDDUMPFARE"=:REFUNDDUMPFARE,"REFUNDLIMITCONSUMFARE"=:REFUNDLIMITCONSUMFARE,"NONAMEFLAG"=:NONAMEFLAG,"TEMCARDNO"=:TEMCARDNO,"JGCARDNO"=:JGCARDNO,"CARDTYPEID"=:CARDTYPEID,"PRODUCTID"=:PRODUCTID,"ASN"=:ASN,"OUTID"=:OUTID,"CARDTYPEPEOPLEID"=:CARDTYPEPEOPLEID,"CARDTYPECITYID"=:CARDTYPECITYID,"SERVERID"=:SERVERID,"SENDSYS"=:SENDSYS,"NUMBEROPCOUNT"=:NUMBEROPCOUNT,"NUMBERSAVEOPCOUNT"=:NUMBERSAVEOPCOUNT,"NUMBERODDFARE"=:NUMBERODDFARE,"NUMBERODDFAREACC"=:NUMBERODDFAREACC,"ISNEWCAPECSYS"=:ISNEWCAPECSYS,"SUMMANGEFARE"=:SUMMANGEFARE,"MANGEFARELASTDATE"=:MANGEFARELASTDATE,"SUMFREEMANGEFARE"=:SUMFREEMANGEFARE,"CUSTOMERUNITCODE"=:CUSTOMERUNITCODE,"OPDT"=:OPDT,"CARDNO"=:CARDNO,"MONODDFARE"=:MONODDFARE,"ACCOUNTTYPE"=:ACCOUNTTYPE,"SUMVICERUSHFARE"=:SUMVICERUSHFARE,"ELECASHTYPE"=:ELECASHTYPE,"VICEVALIDTIMESTART"=:VICEVALIDTIMESTART,"VIDEVALIDTIMEEND"=:VIDEVALIDTIMEEND,"MONVALIDTIMESTART"=:MONVALIDTIMESTART,"MONVALIDTIMEEND"=:MONVALIDTIMEEND,"VICESAVEPLANID"=:VICESAVEPLANID,"MONSAVEPLANID"=:MONSAVEPLANID,"ELESAVEPLANID"=:ELESAVEPLANID,"IDCARD"=:IDCARD  WHERE "ID"=:ID
{":ID":"7801",":CUSTOMERID":7277,":SCARDSNR":"000001",":CARDTYPEDETAILID":3,":CARDSN":1,":STATUS":3,":QUERYPWD":null,":CARDKIND":0,":COUNTRYID":0,":ELECTROPCOUNT":0,":ELECTRSAVEOPCOUNT":0,":MONOPCOUNT":0,":MONSAVEOPCOUNT":5029493556076512432695017472.0,":SUMELECTRADDFAREACC":5029493556076512432695017472.0,":SUMELECTRADDFARE":5029493556076512432695017472.0,":SUMMONADDFAREACC":5029493556076512432695017472.0,":SUMCONSUMFARE":5029493556076512432695017472.0,":SUMELECTRCONSUMFARE":5029493556076512432695017472.0,":SUMMONCONSUMFARE":5029493556076512432695017472.0,":SUMELECTRDUMMYFARE":5029493556076512432695017472.0,":SUMMONRUSHFARE":5029493556076512432695017472.0,":SUMDISCOUNT":0,":ELECTRODDFARE":993283.67,":ELECTRODDFAREACC":993283.67,":NOUSEDATE":"2017-12-22T00:00:00",":EMPID":0,":YEARCHECKS":0,":CHECKBEGINDAY":"0001-01-01T00:00:00",":CHECKENDDAY":"0001-01-01T00:00:00",":VER":16558,":SUMMONTHODDFAREACC":5029493556076512432695017472.0,":DEPRECIATEFARE":0.0,":DEPRECIATEDATE":"0001-01-01T00:00:00",":SUMELECTRADDDUMMYFARE":5029493556076512432695017472.0,":REFUNDDUMPFARE":0,":REFUNDLIMITCONSUMFARE":0,":NONAMEFLAG":0,":TEMCARDNO":0,":JGCARDNO":0,":CARDTYPEID":1,":PRODUCTID":0,":ASN":0,":OUTID":"005659",":CARDTYPEPEOPLEID":1,":CARDTYPECITYID":1,":SERVERID":0,":SENDSYS":null,":NUMBEROPCOUNT":0,":NUMBERSAVEOPCOUNT":0,":NUMBERODDFARE":5029493556076512432695017472.0,":NUMBERODDFAREACC":5029493556076512432695017472.0,":ISNEWCAPECSYS":1,":SUMMANGEFARE":5029493556076512432695017472.0,":MANGEFARELASTDATE":"0001-01-01T00:00:00",":SUMFREEMANGEFARE":0,":CUSTOMERUNITCODE":"08600000002",":OPDT":"2017-06-22T11:26:49",":CARDNO":1,":MONODDFARE":0.0,":ACCOUNTTYPE":5,":SUMVICERUSHFARE":0.0,":ELECASHTYPE":"1",":VICEVALIDTIMESTART":"0001-01-01T00:00:00",":VIDEVALIDTIMEEND":"0001-01-01T00:00:00",":MONVALIDTIMESTART":"0001-01-01T00:00:00",":MONVALIDTIMEEND":"0001-01-01T00:00:00",":VICESAVEPLANID":0,":MONSAVEPLANID":0,":ELESAVEPLANID":0,":IDCARD":"005659"}

**Comment by sunkaixuan** [comment]
这个是因为ORACLE的类型转你C#类型失败引起的，用SQLSUGAR的DBFIRST生成实体和你的实体比较一下区别
