### ISSUE TITLE
order by 与group by 之间排序问题

### ISSUE THREAD

**Issue by bbstoyou** [sunkaixuan/SqlSugar#374]
order by 与group by 之间排序问题:  sql语句直接查询得出的记录与sugar查出的记录不同。
SELECT * FROM `TestRecord`  WHERE (( `UutType` = "DC-A" ) AND ( `UutNum` = "001" ))GROUP BY `TestType`,`TestBand`,`TestDirect` ORDER BY `TestTime` DESC  

 var records = db.Queryable<TestRecord>().Where(it => it.UutType == "DC-A" && it.UutNum == "001").GroupBy(it => new { it.TestType, it.TestBand, it.TestDirect }).OrderBy(it => it.TestTime, OrderByType.Desc).ToList();

**Comment by sunkaixuan** [comment]
检查一下表或者库有没有连错，如果正确从数据库去监控SQL语句，如果还有问题发DEMO到我邮箱
