### ISSUE TITLE
无实体类情况的新增修改

### ISSUE THREAD

**Issue by lifanmvc** [sunkaixuan/SqlSugar#376]
在实际工作中，有些业务表客户需求变化比较大，字段会根据业务的需求频繁的做新增或者删除。文档有非泛型的说明：
var dt = new Dictionary<string, object>();
dt.Add("name", "1");
var t66 = db.Insertable(dt).AS("student")
是否有啥方法，比如说：
var t66 = db.Insertable(tablename,dt)
这样传入表的名字和字典。这样业务字段变化大的情况，就用这个模式。
我和我几个朋友们做业务系统，EF等等就是处理不了无实体的情况。
我的QQ 522797821，希望能够沟通一下这种需求的情况。谢谢。

**Comment by sunkaixuan** [comment]
```cs
//Insert Dictionary or List<Dictionary >
var dt = new Dictionary<string, object>();
            dt.Add("name", "1");
            dt.Add("CreateTime", null);
db.Insertable(dt).AS("student").ExecuteReturnIdentity();
```
这样写有什么满足不了你的需求吗

**Comment by lifanmvc** [comment]
谢谢您的回复。关于模型的问题，我后来想了，我用T4模板生成实体，这样系统里面的表，我都把做成实体。也就没问题呢了。但是另外.net core 中，取消了 SqlCacheDependency 。以前查询可以用SqlCacheDependency做到表级的缓存依赖。我看了sqlsugar里面的文件二级缓存，做了缓存过期。想实现查询结果依赖数据库：比如查询的结果中，表字段发生了变化，缓存失效，这块您怎么实现呢？

发送自 Windows 10 版邮件应用

发件人: sunkaixuan
发送时间: 2019年5月27日 20:48
收件人: sunkaixuan/SqlSugar
抄送: lifanmvc; Author
主题: Re: [sunkaixuan/SqlSugar] 无实体类情况的新增修改 (#376)

//Insert Dictionary or List<Dictionary >

var dt = new Dictionary<string, object>();

            dt.Add("name", "1");

            dt.Add("CreateTime", null);

db.Insertable(dt).AS("student").ExecuteReturnIdentity();
这样写有什么满足不了你的需求吗

**Comment by lifanmvc** [comment]
群主，您好。网上有篇文章，我看了一下，是可以实现。看看您是否考虑这种需求。我倒是希望SqlSugar越做越完善。缓存依赖我行业里做服务，很重要。

https://www.cnblogs.com/luna-hehe/p/9122458.html

发送自 Windows 10 版邮件应用

发件人: sunkaixuan
发送时间: 2019年5月27日 20:48
收件人: sunkaixuan/SqlSugar
抄送: lifanmvc; Author
主题: Re: [sunkaixuan/SqlSugar] 无实体类情况的新增修改 (#376)

//Insert Dictionary or List<Dictionary >

var dt = new Dictionary<string, object>();

            dt.Add("name", "1");

            dt.Add("CreateTime", null);

db.Insertable(dt).AS("student").ExecuteReturnIdentity();
这样写有什么满足不了你的需求吗

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Doc/8/1156 支持自个定义缓存
