### ISSUE TITLE
Manage simple collections (List of strings)

### ISSUE THREAD

**Issue by whitedevils** [sunkaixuan/SqlSugar#379]
Hi to everyone.
I have this object

```
public class A
{ 
        [SugarColumn(IsPrimaryKey = true)]
        public string OrderNumber { get; set; }  
        public string LDV { get; set; }
        public List<string> Parcels { get; set; }
}
```

If i want to insert to db a list of string in Parcels property i get this error:

> There are fewer columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement.

Is the possibility to manage simple list like list of strings or int or decimal?
Thanks

**Comment by sunkaixuan** [comment]
https://github.com/sunkaixuan/SqlSugar/blob/SqlSugar5/Src/Asp.Net/SqlServerTest/UnitTest/UJson.cs

**Comment by sunkaixuan** [comment]
Support Json string  to object
