### ISSUE TITLE
我是封装成 Repository 模式，然后在业务层调用就报错！直接用时没有问题。

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#38]
我是封装成 Repository 模式，然后在业务层调用就报错！直接用时没有问题。
参考 `https://github.com/sunkaixuan/SqlSugar/issues/37`

**Comment by sunkaixuan** [comment]
有几个重载你不要封装错了，

**Comment by sunkaixuan** [comment]
UpateColums 重载错了方法

**Comment by haibozhou1011** [comment]
那要如何重载才不错呢？？

**Comment by haibozhou1011** [comment]
调用那个方法才算不错呢？
