### ISSUE TITLE
5.0.0.2 SetColumns出错

### ISSUE THREAD

**Issue by blackxea** [sunkaixuan/SqlSugar#380]
更新表中的bit列例如：SetColumns(t => new Model { IsTrue = !t.IsTrue })时，报错SqlException: “(”附近有语法错误。

**Comment by sunkaixuan** [comment]
这个还在修复中，先这么用 it => new CarType { State =SqlSugar.SqlFunc.IIF(it.State==true,false,true) }

**Comment by sunkaixuan** [comment]
已修复近几天会更新
