### ISSUE TITLE
AddColumn 对表名增加了两次双引号?

### ISSUE THREAD

**Issue by 919946646** [sunkaixuan/SqlSugar#381]
public virtual bool AddColumn(string tableName, DbColumnInfo columnInfo)
        {
            tableName = this.SqlBuilder.GetTranslationTableName(tableName); //第一次执行
            string sql = GetAddColumnSql(tableName, columnInfo);   //函数内又执行一次
            this.Context.Ado.ExecuteCommand(sql);
            return true;
        }

**Comment by sunkaixuan** [comment]
什么数据库

**Comment by sunkaixuan** [comment]
GetTranslationTableName 这个方法底层有是否处理过的验证的应该，理论上不会重复

**Comment by 919946646** [comment]
数据库是postgreSQL 数据库，如下使用方式 

//新增列
SqlSugar.DbColumnInfo col_createuid = new SqlSugar.DbColumnInfo
                {
                    DataType = "uuid",
                    DbColumnName = "createuid555",
                    IsNullable = true,
                    IsPrimarykey = false
                };
                bool ret = new Db.DbMaintenance.AddColumn("test3", col_createuid);


生成的sql语句类似 
ALTER TABLE ""test3"" ADD COLUMN "createuid555" uuid DEFAULT NULL 
在表名test3多了一组双引号。
或许是我使用不当？请指教，谢谢

**Comment by sunkaixuan** [comment]
好的我看一下

**Comment by sunkaixuan** [comment]
已解决近期会发布
