### ISSUE TITLE
请问新版本还支持下面这样的IgnoreColumns写法么， 为什么更新数据时候被忽略的列也被更新了呢

### ISSUE THREAD

**Issue by WenRuonan** [sunkaixuan/SqlSugar#384]
public bool Update<T>(List<T> entity, string[] colums) where T : class, new()
        {
            int i = _jQContext.Updateable(entity).IgnoreColumns(colums).ExecuteCommand();
            return (i > 0 ? true : false);
        }

**Comment by sunkaixuan** [comment]
你看看是不是参数大小写区别

**Comment by sunkaixuan** [comment]
是我的问题，你先把参数转小写传进来吧，这个我已经修复，后续会更新
