### ISSUE TITLE
where中IEnumerable集合调用Contains无效，但不影响执行

### ISSUE THREAD

**Issue by FQLin** [sunkaixuan/SqlSugar#385]
我的删除语句：
```c#
            Program._db.Deleteable<CarTypeExtend>()
                    .Where(p => /*ids.*/cts.Select(c => c.ID).Contains(p.ID))
                    .ExecuteCommand();
```
最重要的是：没有抛异常，执行通过了，但是数据没有删除成功！
应该是还没有支持`IEnumerable`类型集合，使用`List`就没问题。
感觉这是一个比较严重的问题了
[https://github.com/FQLin/AllTest/blob/master/SqlSugar/TestDemo/IEnumerbleContains.cs](https://github.com/FQLin/AllTest/blob/master/SqlSugar/TestDemo/IEnumerbleContains.cs)

**Comment by Cloud33** [comment]
我也有这个问题，它的条件会解析为(1=2)。。。。
后面，我都改为`In(t=> t.xxx,new {}) `这种方式去做了

**Comment by sunkaixuan** [comment]
已修复近期会同步
