### ISSUE TITLE
[BUG]使用SaveQueues打包查询出来结果并没有按数据库排序返回到程序

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#386]
在使用SaveQueues打包查询时，我根据日期字段 Desc排序，发现到程序中是乱掉的，但是直接执行打包查询的SQL，发现结果是正常的。
意思是说：
1.数据在数据库查询时，是正常的排序
2.这个数据通过SaveQueues返回到程序时，这个时候，排序是乱掉的。

不知道是否是因为程序在接收数据时，有没有处理。

**Comment by sunkaixuan** [comment]
你最好写个重现的DEMO 这个应该不太可能发生

**Comment by Cloud33** [comment]
我只能提供截图了，都是一样的SQL，数据也是全部一样的：
这是数据库查询的截图：
![image](https://user-images.githubusercontent.com/8787198/58675717-23261500-8388-11e9-820c-3b1398a0833c.png)

这是程序内的数据：
![image](https://user-images.githubusercontent.com/8787198/58675751-48b31e80-8388-11e9-9897-171569bac6be.png)

因为我做了分页，好像只有第一页数据是乱掉的，其它页的数据都是正常的。

**Comment by sunkaixuan** [comment]
你用SQL写一个简单DEMO，不要用存储过程 ，如果SQL好的那就不是我这边问题

**Comment by sunkaixuan** [comment]
db.Queryable<Order>().OrderBy(it=>it.Id,OrderByType.Desc).AddQueue();
            db.AddQueue("select 1");
            db.SaveQueues<Order,int>();

**Comment by sunkaixuan** [comment]
我这么测试都是好的，理论上不是我这边出的错

**Comment by sunkaixuan** [comment]
你也可以用sqlprofile 监控一下数据库最终于行的SQL是什么

**Comment by Cloud33** [comment]
我之前截图的二张图片，执行的SQL是完全一样的，都是执行一个存储过程，没有在出存储过程结果后做任务事情（因为我的SQL比较多，所以我用存储过程包装了一下，这样能提高一点效率），sqlprofile 如果你的打包查询不包装，理念上，SQL应该是一样的，但还是要用sqlprofile 去看，所以，我等下会使用sqlprofile 去监控最终执行的SQL是什么，后续补充，谢谢。

**Comment by sunkaixuan** [comment]
你最好确一下原因，我今天要发布版本，今天确认出是否有问题我好加入到版本之中

**Comment by Cloud33** [comment]
找到原因了，不是SqlSugqr的问题，是我SQL的问题，初步原因是：
使用offset fetch next 分页：
offset  0 rows fetch next 10 rows only
0前面有一个空格，好像去掉空格排序就不会乱掉了！不知道是什么原理。
