### ISSUE TITLE
postgresql 使用sqlsugar，代码中写sql语句查询，sql语句表使用了别名，结果生产的sql语句查不到数据

### ISSUE THREAD

**Issue by Lukerli** [sunkaixuan/SqlSugar#387]
代码中的SQL语句
var data = client.SqlQueryable<dynamic>("select S.name,S.code from test_t S").ToList();

调试打印出来的sql语句：

![QQ图片20190530191609](https://user-images.githubusercontent.com/4084296/58629602-80ca4b00-830f-11e9-965a-d2a517ee041f.png)

异常信息如下
![Uploading QQ图片20190530191623.png…]()

**Comment by sunkaixuan** [comment]
已修复，等更新
