### ISSUE TITLE
更新列的语句有BUG

### ISSUE THREAD

**Issue by binglinlu** [sunkaixuan/SqlSugar#390]
文件：Methods.cs
方法：GetUpdateColumnSql
错误行：string columnName = this.SqlBuilder.GetTranslationTableName(columnInfo.DbColumnName);
正确应该是：string columnName = this.SqlBuilder.GetTranslationColumnName(columnInfo.DbColumnName);

**Comment by binglinlu** [comment]
文件：Methods.cs
方法：GetUpdateColumnSql 
错误行：string columnName = this.SqlBuilder.GetTranslationTableName(columnInfo.DbColumnName);

**Comment by binglinlu** [comment]
正确应该是：
           string columnName = this.SqlBuilder.GetTranslationColumnName(columnInfo.DbColumnName);

**Comment by binglinlu** [comment]
该BUG将导致某表字段名如果与某表类名一样，将无法修改该字段。

**Comment by sunkaixuan** [comment]
已修改近期会同步
