### ISSUE TITLE
4.9 升级 5.x 导致无法无法找到下图方法，是不兼容4.9？

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#392]
![image](https://user-images.githubusercontent.com/10756986/58692559-6e104e80-83c1-11e9-9e8e-c57142aa041c.png)

**Comment by sunkaixuan** [comment]
去VS里面重新生成，看看编译哪儿有兼容问题

**Comment by haibozhou1011** [comment]
生成了的，我把5.x 降下来，就可以正常访问。

**Comment by sunkaixuan** [comment]
在VS里面调试，看看是什么错

**Comment by haibozhou1011** [comment]
好吧，我定位一下，再跟你讨论！

**Comment by haibozhou1011** [comment]
可以关闭了，可能是我没有重启IIS缘故。
