### ISSUE TITLE
更新优化建议

### ISSUE THREAD

**Issue by bluesky2128** [sunkaixuan/SqlSugar#394]
//如:model.name="ABC";model.sex="man";修改了实体中两个属性
//ORM会记住您修改了上面2个字段，所以在生成SQL的时候仅仅是：
//UPDATE table SET name='ABC',sex='girl' WHERE id=1

**Comment by sunkaixuan** [comment]
这个是EF查出来在更新的理念了和SQLSUGAR不是一个思路
