### ISSUE TITLE
[建议] 希望能出一个版本的说明

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#396]
希望能出一个版本的推进说明，现在好像没办法知道新的版本改进或改变了哪些东西，或我没有找到地方？

**Comment by yuzhigang** [comment]
支持建议。API有很多改变的。完全不知道为啥。现在的新版本一运行就出错，还是得退回到老版本。
不要再增加新特性了。保持已有功能足够稳定。
不要再增加新特性了。保持已有功能足够稳定。
不要再增加新特性了。保持已有功能足够稳定。

System.ArgumentNullException
 在 SqlSugar.OracleDbMaintenance.<>c__DisplayClass74_0.<GetFieldComment>b__1(DbColumnInfo it)
   在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   在 SqlSugar.OracleDbMaintenance.GetFieldComment(String tableName, String filedName)
   在 SqlSugar.OracleDbMaintenance.GetColumnInfosByTableName(String tableName)
   在 SqlSugar.OracleDbMaintenance.<>c__DisplayClass70_0.<GetColumnInfosByTableName>b__0()
   在 SqlSugar.ReflectionInoCore`1.GetOrCreate(String cacheKey, Func`1 create)
   在 SqlSugar.ReflectionInoCacheService.GetOrCreate[V](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds)
   在 SqlSugar.OracleDbMaintenance.GetColumnInfosByTableName(String tableName, Boolean isCache)
   在 SqlSugar.DbMaintenanceProvider.<>c__DisplayClass5_0.<GetPrimaries>b__0()
   在 SqlSugar.ReflectionInoCore`1.GetOrCreate(String cacheKey, Func`1 create)
   在 SqlSugar.ReflectionInoCacheService.GetOrCreate[V](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds)
   在 SqlSugar.DbMaintenanceProvider.GetPrimaries(String tableName)
   在 SqlSugar.InsertableProvider`1.GetPrimaryKeys()
   在 SqlSugar.InsertableProvider`1._ExecuteCommand()
   在 SqlSugar.InsertableProvider`1.ExecuteCommand()
   在 SqlSugar.OracleInsertable`1.ExecuteCommand()

**Comment by sunkaixuan** [comment]
官网正在开发中
