### ISSUE TITLE
[BUG] 打包查询问题

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#397]
因为我有使用分页查询，第一个是结果集，第二个是总数量
如果没有查询到数据：
结果集是一个List，Count==0
总数量是null，但是，真正执行的SQL，是有数量返回的，结果为0
![image](https://user-images.githubusercontent.com/8787198/58785953-2be14a00-8619-11e9-9269-a09b502b28bd.png)

所以这个地方，是不是可以把真正的结果返回到程序？
使用的版本为5.0.0.6

**Comment by sunkaixuan** [comment]
代码发一下，看不到代码

**Comment by Cloud33** [comment]
代码：
![image](https://user-images.githubusercontent.com/8787198/58845072-5af4cb80-86ac-11e9-90ce-8d555929d675.png)

**Comment by Cloud33** [comment]
我还发现了一个问题，如果打包查询中间有空的数据，后面有数据也查询不出来：
原始数据：
![image](https://user-images.githubusercontent.com/8787198/58846319-5bdc2c00-86b1-11e9-8540-fa5e53dd9eda.png)

程序内的数据：
![image](https://user-images.githubusercontent.com/8787198/58846375-87f7ad00-86b1-11e9-8602-6152055a6b48.png)

**Comment by sunkaixuan** [comment]
你这个是什么数据库

**Comment by sunkaixuan** [comment]
已修复节前会更新
