### ISSUE TITLE
postgresql 整型字段查询提示操作异常

### ISSUE THREAD

**Issue by wangjunjx8868** [sunkaixuan/SqlSugar#398]
List<IConditionalModel> conModels = new List<IConditionalModel>();
 conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Equal, FieldValue = "1" });

对于postgresql 来说，id是整型字段，也是主键，那么这么查询提示 Npgsql.PostgresException:“42883: 操作符不存在: 
用拉姆达表达式可以查询。

**Comment by wangjunjx8868** [comment]
我的版本号是 sqlSugarCore 5.0.0.5

**Comment by sunkaixuan** [comment]
PGSQL这块有点 坑             conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Equal, FieldValue = "1" , FieldValueConvertFunc=it=>Convert.ToInt32(it) });//id=1 必须这么写

**Comment by sunkaixuan** [comment]
还有建议升级到5.0.0.6修复了一个BUG
