### ISSUE TITLE
postgresql  插入时不返回自增字段的ID

### ISSUE THREAD

**Issue by wangjunjx8868** [sunkaixuan/SqlSugar#399]
正常情况下 插入并返回最新自增ID 是这样的
INSERT INTO festival(hdmc,hdbz,isdq)VALUES('a','a',1) RETURNING "id";
4.x和5.x版本都i有这个错误  语句少了 id
生成的错误语句是
INSERT INTO festival(hdmc,hdbz,isdq)VALUES('a','a',1) RETURNING； 导致语法错误
除非[SugarColumn(IsPrimaryKey = true, IsIdentity = true)] 并设置  InitKeyType = InitKeyType.Attribute,

如果 InitKeyType = InitKeyType.SystemTable,  且id 不加[SugarColumn(IsPrimaryKey = true, IsIdentity = true)] 。代码不自动识别主键id

**Comment by sunkaixuan** [comment]
已修复
