### ISSUE TITLE
列更新BUG，对于Dec，Dob类型的字段，没有比较小数位，将无法更新字段。

### ISSUE THREAD

**Issue by binglinlu** [sunkaixuan/SqlSugar#400]
文件：CodeFirstProvider.cs
方法：ExistLogic
行：var alterColumns = entityColumns。。。。没有比较小数位精度，将无法修改字段。

**Comment by binglinlu** [comment]
长度，小数位均需做比较。(ec.Length != dc.Length || ec.DecimalDigits != dc.DecimalDigits)

**Comment by binglinlu** [comment]
DecType、FloatType、DobType都需要

**Comment by sunkaixuan** [comment]
这种会影响数据考虑到安全我不作处理，手动更新
