### ISSUE TITLE
表示多主建，提示这个错误

### ISSUE THREAD

**Issue by lwd11007566248** [sunkaixuan/SqlSugar#401]
English Message : This type of Dictionary is not supported for the time being. You can try Dictionary<string, string>, or contact the author!!
Chinese Message : 暂时不支持该类型的Dictionary 你可以试试 Dictionary<string ,string>或者联系作者！！

public class PlatfromTagKeyValuePair

   {

        /// <summary>

        /// 平台

        /// </summary>

        [SugarColumn(IsPrimaryKey = true, IsIdentity = false)]

        public int PlatfromId { get; set; }

        /// <summary>

        /// 关键字

        /// </summary>

        [SugarColumn(IsPrimaryKey = true, IsIdentity = false)]

        public int KeyWord { get; set; }

        /// <summary>

        /// 值

        /// </summary>

        [SugarColumn(IsPrimaryKey = true, IsIdentity = false)]

        public int Value { get; set; }

        /// <summary>

        /// 类型

        /// </summary>

        [SugarColumn(IsPrimaryKey = true, IsIdentity = false)]

        public int KeyValueTypeId { get; set; }

        public DateTime CreatedTime { get; set; } = DateTime.Now;

        /// <summary>

        /// 使用次数

        /// </summary>

        public int UseNumber { get; set; } = 1;

}

**Comment by sunkaixuan** [comment]
这个近期会修复

**Comment by lwd11007566248** [comment]
后面，多种尝试发现，居然和类的名称有关系

**Comment by sunkaixuan** [comment]
已修复

**Comment by sunkaixuan** [comment]
关注5.0.0.8
