### ISSUE TITLE
更新错误bug

### ISSUE THREAD

**Issue by Kiliggggg** [sunkaixuan/SqlSugar#402]
1.Expression<Func<QUERY_RELEVANCE, QUERY_RELEVANCE>> setEx = s => new QUERY_RELEVANCE { ISDELETED = false, UPDATEUSERID = "sa", UPDATEUSERNAME = user ?? string.Empty, UPDATETIME = DateTime.Now };
2.db.Updateable<QUERY_RELEVANCE>().SetColumns(setEx)

UPDATEUSERNAME = user ?? string.Empty 当这种情况时更新失败，错误提示
MySql.Data.MySqlClient.MySqlException: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE ( `RELEVANCEID` = 1 )' at line 2'

sql语句输出：UPDATE `QUERY_RELEVANCE`  SET
            `NAME` = @Const0 , `GIST` = @Const1 , `UPDATEUSERID` = @Const2 , `UPDATEUSERNAME` = IFNULL(@MethodConst3, `UPDATETIME` = @constant5   WHERE ( `RELEVANCEID` = @RELEVANCEID6 )    少了个括号

**Comment by yuzhigang** [comment]
越更新错误越多。 非常后悔入了这个orm的坑。
 从三月份开始用，浪费很多时间在找orm增删改的问题上。
我已经提出好几个bug了，还不断发现新bug。
作者倒是更新很及时，不过测试用例cover的太少了。
