### ISSUE TITLE
可以设计更通用一些

### ISSUE THREAD

**Issue by fuwei54321** [sunkaixuan/SqlSugar#404]
楼主是否考虑加个创建和更新的时候对实体进行拦截修改的拦截器，和mybatisplus一样的那个，因为数据库有一些共通字段，像createdate，updatedate，is-delete这些字段等等，可以加在实体上的注解，比如CreateFill=true,这种的，可以选择用或者不用，还有就是可以加个逻辑删除嘛，比如我在实体上加入一个注解，[LogicDeleted = true], 那么在生成sql的时候会手动拼接上当前注解对应的属性

**Comment by pypykim** [comment]
建议增加上述功能
