### ISSUE TITLE
非常感谢增加了默认值支持，如果可以的话DefaultValue最好是object型的

### ISSUE THREAD

**Issue by lindenrty2** [sunkaixuan/SqlSugar#409]
非常感谢增加了默认值支持，如果可以的话DefaultValue最好是object型的，一般这类值都有公共定义在，定成String就没办法用int型常量，枚举之类的了，因为Attribute上没办法做转型

**Comment by lindenrty2** [comment]
另外类里面定义了不支持的类型时，提示最好能友好一点，猜了半天才发现是一个类型(sbyte)不支持，最好还能增加枚举型的支持

**Comment by lindenrty2** [comment]
在表里有数据的情况下加非空列的时候默认值功能好像不正常，期望的结果是添加新列，现有数据的该列都填充默认值，但是现在会报错，改为允许为空以后可以通过，从数据库来看默认值也的确加上去了，不知道你这里是不是先Add后Alter造成的。

Sqlserver的时候的错误如下
----------------------------------------------------------------------------------------------------
ALTER TABLE 只允许添加满足下述条件的列: 列可以包含 Null 值；或者列具有指定的 DEFAULT 定义；或者要添加的列是标识列或时间戳列；或者，如果前几个条件均未满足，则表必须为空以允许添加此列。不能将列“XXXXXX”添加到非空表“XXXXXX”中，因为它不满足上述条件。”

**Comment by sunkaixuan** [comment]
你试着把数据清空试试，可能是数据约束

**Comment by lindenrty2** [comment]
这是新列，的确有非空约束，所以上回我提意加默认值支持来解决有数据得情况下新列非空的问题，清空数据就没意义了。我手工执行 Alter Table XXXX Add XXXXX Not Null Default 1 来添加非空新列是没问题的。

**Comment by YannKing** [comment]
我是搜索 SqlSUgar DefaultValue找到这的。。确实，要是清空数据就没意义了  只是要给新增列一个默认值而已 。  比如我，只想要加一个bool列。
