### ISSUE TITLE
MySQL 批量插入 能支持这种语法？

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#41]
insert into tabl1 values (1,1), (2,1), (3,1), (4,1), (5,1), (6,1), (7,1)

MySQL 批量新增 能支持这种语法？

现在我看您的是
insert into tabl1
select 1,1
union all
select 2,1
...
这种语法

**Comment by sunkaixuan** [comment]
暂时不支持，不过UNION ALL也是处理过的 UNION ALL，自带有分页 ，所以性能没必要担心
