### ISSUE TITLE
使用异步异常:System.AggregateException:“One or more errors occurred. (The connection does not support MultipleActiveResultSets.)”

### ISSUE THREAD

**Issue by xushenchen** [sunkaixuan/SqlSugar#411]
使用异步多线程查询时出错
![image](https://user-images.githubusercontent.com/37541358/59478751-04964280-8e8d-11e9-9568-e41c789cb0b5.png)
代码如下:
![image](https://user-images.githubusercontent.com/37541358/59478760-1546b880-8e8d-11e9-9698-d5688ccbc945.png)

**Comment by sunkaixuan** [comment]
这个是你的代码问题 ， 看错误 提示也明白了，你的wait和你的异步 都 不在一个线程 了
