### ISSUE TITLE
插入Bug

### ISSUE THREAD

**Issue by lic0914** [sunkaixuan/SqlSugar#413]
db.Insertable(entity).ExecuteReturnEntity() 
报异常：序列不包含任何元素
堆栈：
 在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   在 SqlSugar.EntityMaintenance.GetProperty[T](String dbColumnName)
   在 SqlSugar.InsertableProvider`1.ExecuteCommandIdentityIntoEntity()
   在 SqlSugar.InsertableProvider`1.ExecuteReturnEntity()
....
而使用ExecuteCommand 就没问题

**Comment by sunkaixuan** [comment]
给个DEMO吧获取把实体类发出来看一下

**Comment by AtlantisDe** [comment]
# 插入数据 引发的
```c#
 我的是插入导致数据库一直处于被占用状态网页上使用 iis那个 w3wp.exe 占用我我 sqlite 数据库文件  现在不知道怎么用 SqlSugar 执行 类似 这样的功能 
 SQLiteConnection.ClearPool(conn);  
```

**Comment by lic0914** [comment]
> 给个DEMO吧获取把实体类发出来看一下


##  示例如下：
dbType:：SqlServer
实体类型：

``` csharp
 public class UserRoleRelation
    {
       
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RoleId { get;set; }
    }

 var db= new SqlSugarClient(new ConnectionConfig()
                {
                    ConnectionString = ConnectionStrings,
                    DbType = DbType.SqlServer,
                    InitKeyType = InitKeyType.SystemTable,//从默认表Id作为主键
                    IsAutoCloseConnection = true,//开启自动释放模式和EF原理一样我就不多解释了

                });

            return  DbFactory.SugarContext.Insertable(entity).ExecuteReturnEntity()
```
会引发异常

**Comment by sunkaixuan** [comment]
ID是主键并且自增吗

**Comment by AtlantisDe** [comment]
看样子 好像应该是主键问题 检查下逻辑对了么

**Comment by lic0914** [comment]
没问题，是自增的 要说逻辑有问题，为何我使用 ExecuteReturnIdentity() 却没问题呢

**Comment by yuzhigang** [comment]
Oracle的这个方法ExecuteReturnEntity也有问题。
提示xxx.currval 未在会话里定义。 
自增的触发器什么的都指定了。ExecuteReturnIdentity()没问题。
