### ISSUE TITLE
经测试 Insert 引发数据库一直处于  iis那个 w3wp.exe 被占用问题

### ISSUE THREAD

**Issue by AtlantisDe** [sunkaixuan/SqlSugar#414]
# 插入数据 引发的
```c#
 我的是插入导致数据库一直处于被占用状态网页上使用 iis那个 w3wp.exe 
占用我我 sqlite 数据库文件  现在不知道怎么用 SqlSugar 执行 类似 这样的功能 
 SQLiteConnection.ClearPool(conn);  
```

```c#
using (var db = Aleseocore.Module.siteitem.Main.Base.GetInstance(root.siteconfig.host))
{
	db.Insertable(muluclassitems).ExecuteCommand();
//插入数据会引发被占用
//db.Queryable //查询不会 ...引发这个问题 
	db.Close();
}
```

##  搜索老大说了这样关闭连接池 可以暂时解决这问题
-  这个是其它类库 关闭 方法 
-  SQLiteConnection.ClearPool(conn);  
- 咱们这个sqlsugar 怎么来关闭.

**Comment by sunkaixuan** [comment]
SQLiteConnection.ClearPool(db.ado.connection);

**Comment by sunkaixuan** [comment]
db.ado.connection.ClearPool

**Comment by AtlantisDe** [comment]
你版本没更新上来么 db.ado.connection.ClearPool 需要这个功能啊

**Comment by AtlantisDe** [comment]
> db.ado.connection.ClearPool

你版本没更新上来么 db.ado.connection.ClearPool 需要这个功能啊

**Comment by sunkaixuan** [comment]
((sqliteconnection)db.ado.connection).ClearPool

**Comment by AtlantisDe** [comment]
> ((sqliteconnection)db.ado.connection).ClearPool

 var sQLiteConnection = ((SQLiteConnection)db.Ado.Connection);
                    System.Data.SQLite.SQLiteConnection.ClearPool(sQLiteConnection);
