### ISSUE TITLE
提交一份新代码上来啊 这个 的 db.ado.connection.ClearPool

### ISSUE THREAD

**Issue by AtlantisDe** [sunkaixuan/SqlSugar#415]
#414 
## 提交一份新代码上来啊 这个 的 db.ado.connection.ClearPool

**Comment by sunkaixuan** [comment]
((sqliteconnection)db.ado.connection).ClearPool

**Comment by AtlantisDe** [comment]
> ((sqliteconnection)db.ado.connection).ClearPool

 var sQLiteConnection = ((SQLiteConnection)db.Ado.Connection);
                    System.Data.SQLite.SQLiteConnection.ClearPool(sQLiteConnection);
