### ISSUE TITLE
 db.Ado.LogEventStarting ErrorEvent 当前版本都废弃了吗 我看了下 没有了?

### ISSUE THREAD

**Issue by AtlantisDe** [sunkaixuan/SqlSugar#416]
db.Ado.LogEventStarting ErrorEvent 当前版本都废弃了吗 我看了下 没有了?

**Comment by AtlantisDe** [comment]
db.Aop.OnLogExecuting

**Comment by Rohmeng** [comment]
> db.Aop.OnLogExecuting 
每个db.Queryable都会执行OnLogExecuting吗 ？我遇到了多次查询只输出了部分sql语句的情况 @AtlantisDe

**Comment by AtlantisDe** [comment]
> > db.Aop.OnLogExecuting
> > 每个db.Queryable都会执行OnLogExecuting吗 ？我遇到了多次查询只输出了部分sql语句的情况 @AtlantisDe

这个我好想暂时没发现....你再调试下
