### ISSUE TITLE
经测试怎么还是没释放还是被占用状态 实在让我头疼 SQLiteConnection.ClearPool

### ISSUE THREAD

**Issue by AtlantisDe** [sunkaixuan/SqlSugar#417]
# 经测试怎么还是没释放还是被占用状态

#414 
```c#
 public void Dispose()
        {

            try
            {
                var sQLiteConnection = ((System.Data.SQLite.SQLiteConnection)this.Ado.Connection);
                System.Data.SQLite.SQLiteConnection.ClearPool(sQLiteConnection);
            }
```

**Comment by sunkaixuan** [comment]
System.Data.SQLite.SQLiteConnection.ClearAllPools();   用这个试试吧，还有开发工具打开数据库也无法释放

**Comment by AtlantisDe** [comment]
> System.Data.SQLite.SQLiteConnection.ClearAllPools(); 用这个试试吧，还有开发工具打开数据库也无法释放

这个方法我也测试了 一样无效...

**Comment by sunkaixuan** [comment]
找找是否有开发工具占用连接，或者定时任务之类的，或者本身SQLITE就这样的

**Comment by AtlantisDe** [comment]
> 找找是否有开发工具占用连接，或者定时任务之类的，或者本身SQLITE就这样的

# 按道理不会的 别的链接数据库软件 打开确实在链接 可是点击关闭时候就已经能把数据库释放掉了.

## 如这个软件 关闭后确实不会被占用 打开连接时候 删除就被占用 说明我们释放方法没对
## 如图
![avatar](https://cdn.layui.com/upload/2019_6/3712296_1560760012294_46513.png)

**Comment by AtlantisDe** [comment]
我去 可以了

 System.Data.SQLite.SQLiteConnection.ClearAllPools();

一定要在当前进程程序执行...
