### ISSUE TITLE
如果需要查询层级结构比较深的Model，怎么查询比较好？

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#418]
目前看了文档发现有两个做法：
1. 通过.Mapper
2. 通过属性导航

通过.Mapper，我看示例，只有两层结构，但是Model包括四到五层结构，不知道怎么处理！

通过属性导航，这个是满足我的结构的，发现是懒加载模式，所以在for数据时，是一个一个请求数据库的，所以有没有一次性加载所有数据？不是懒加载，这样就不用for数据库了。

**Comment by sunkaixuan** [comment]
目前这个方案只能用 mapper的手动模式

**Comment by sunkaixuan** [comment]
mapper.get可以防止多次请求库

**Comment by sunkaixuan** [comment]
cache.get

**Comment by Cloud33** [comment]
我找到另外一种方式！我的意思是请求多次没关系，关键在于，我可以控制他是把数据都请求给我，还是说懒加载（用的时候再取）
