### ISSUE TITLE
var t3 = db.Insertable(insertObj).ExecuteReutrnIdentity(); 这个方法建议，能否提供泛型的方式。

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#42]
var t3 = db.Insertable(insertObj).ExecuteReutrnIdentity(); 这个方法建议，能否提供泛型的方式。
如：
var t3 = db.Insertable(insertObj).ExecuteReutrnIdentity&lt;int&gt;();

**Comment by haibozhou1011** [comment]
var t3 = db.Insertable(insertObj).ExecuteReutrnIdentity<T>();

**Comment by sunkaixuan** [comment]
目前支持INT和LONG (ExecuteReutrnIdentity和ExecuteReutrnBigIdentity)

**Comment by haibozhou1011** [comment]
好的，之后可以支持一下吗？？因为主键很多情况下不是只有int，long，可能有guid，string类型。

**Comment by sunkaixuan** [comment]
GUID STRING这些不需要返回你实体里面就有了 ，ExecuteReutrnIdentity只是返回自添列ID

**Comment by sunkaixuan** [comment]
插入并返回实体 ,  只是自identity 添加到 参数的实体里面并返回 
var t3 = db.Insertable(insertObj).ExecuteCommandIdentityIntoEntity();

**Comment by sunkaixuan** [comment]
用上面的方法可以统一返回实体

**Comment by haibozhou1011** [comment]
好的，现在也是用这种方式。

**Comment by haibozhou1011** [comment]
ExecuteCommandIdentityIntoEntity与ExecuteReturnEntity 方法，区别在哪里？？？
