### ISSUE TITLE
已经无力吐槽这个ORM框架了。

### ISSUE THREAD

**Issue by yuzhigang** [sunkaixuan/SqlSugar#420]
```csharp
 public async Task<TEntity> UpdateAsync(TEntity entity)
        {
            await DbContext.Updateable(entity).ExecuteCommandAsync();
            return entity;
        }
``` 

在 SqlSugar.OracleDbMaintenance.<>c__DisplayClass74_0.<GetFieldComment>b__1(DbColumnInfo it)
   在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   在 SqlSugar.OracleDbMaintenance.GetFieldComment(String tableName, String filedName)
   在 SqlSugar.OracleDbMaintenance.GetColumnInfosByTableName(String tableName)
   在 SqlSugar.OracleDbMaintenance.<>c__DisplayClass70_0.<GetColumnInfosByTableName>b__0()
   在 SqlSugar.ReflectionInoCore`1.GetOrCreate(String cacheKey, Func`1 create)
   在 SqlSugar.ReflectionInoCacheService.GetOrCreate[V](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds)
   在 SqlSugar.OracleDbMaintenance.GetColumnInfosByTableName(String tableName, Boolean isCache)
   在 SqlSugar.DbMaintenanceProvider.<>c__DisplayClass5_0.<GetPrimaries>b__0()
   在 SqlSugar.ReflectionInoCore`1.GetOrCreate(String cacheKey, Func`1 create)
   在 SqlSugar.ReflectionInoCacheService.GetOrCreate[V](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds)
   在 SqlSugar.DbMaintenanceProvider.GetPrimaries(String tableName)
   在 SqlSugar.UpdateableProvider`1.GetPrimaryKeys()
   在 SqlSugar.UpdateableProvider`1.PreToSql()
   在 SqlSugar.UpdateableProvider`1._ExecuteCommand()
   在 SqlSugar.UpdateableProvider`1.<ExecuteCommandAsync>d__80.MoveNext()

越更新错误越多。 用了三个月，一半时间再查错误。
不更新有bug，更新了bug更多。

**Comment by AtlantisDe** [comment]
正常嘛 越做越好 bug 也会越来越多 哪个框架不都这样呢...只能慢慢修.

**Comment by yuzhigang** [comment]
基本更新插入都有bug，还别说新特性了。
用了三个月，处处是bug。这是让用户测bug来了吗？
我不怪作者，毕竟辛辛苦苦开源的，我怪自己选择错了。

**Comment by MonkSoul** [comment]
@yuzhigang 您没有选错SqlSugar，SqlSugar目前是为数不多的好ORM，可能5.0版本有些纰漏，但是您可以先用4.9.9.7版本，这个问题非常少。

**Comment by yuzhigang** [comment]
@MonkSoul ，兄弟，我是从三月份开始用的，给作者报告了至少两个bug。 从4.9.9.1一直用到5.0.0.7，没bug就不会更新了，一更新又是新的bug。
别的数据库稳不稳定不知道，我用的oracle，问题是很多。

**Comment by MonkSoul** [comment]
@yuzhigang 哦哦，Oracle这边我们用的少，都是MSSQL，Mysql比较多，也希望能够多多体谅，给作者一点时间，给中国开源一点时间，SqlSugar设计思想比市场上的Orm基本都要好，也非常感谢您能够百忙之中测出BUG，也给您项目带来困扰深感歉意，希望您能够继续使用SqlSugar，我相信会给您满意的答复的。

**Comment by yuzhigang** [comment]
耗费太多时间，抱歉，发了牢骚。说到底还是要解决问题。
测试用例写的太少。
版本发布太随意了。

**Comment by MonkSoul** [comment]
@yuzhigang 下次会注意的，也会越早越好，给作者点时间。

**Comment by AtlantisDe** [comment]
> @yuzhigang 哦哦，Oracle这边我们用的少，都是MSSQL，Mysql比较多，也希望能够多多体谅，给作者一点时间，给中国开源一点时间，SqlSugar设计思想比市场上的Orm基本都要好，也非常感谢您能够百忙之中测出BUG，也给您项目带来困扰深感歉意，希望您能够继续使用SqlSugar，我相信会给您满意的答复的。

这个是必须的 确实 市面上 来说 目前这个 ORM很可以的了 记得打赏下 给作者

**Comment by sunkaixuan** [comment]
我没人收过你一分钱，你要用就用，不用也没逼着你用，你想解决问题我是可以解决，你只要现成的这个我没有

**Comment by sunkaixuan** [comment]
你的错都 是来自 OracleDbMaintenance ，你只要把initkey设置成attribute，通过特性方式操作库 就不会执行 OracleDbMaintenance
