### ISSUE TITLE
请问是否有乐观锁的功能？

### ISSUE THREAD

**Issue by lindenrty2** [sunkaixuan/SqlSugar#422]
EF中可以定义更新时间/版本号之类的为更新凭据，如果更新数据时目标数据的指定列已经变化则更新会失败，SQLSuger是否有这个功能?文档中好像没找到。

**Comment by sunkaixuan** [comment]
https://github.com/sunkaixuan/SqlSugar/wiki/2.Updateable  拉到最下面
