### ISSUE TITLE
postgre数据库模糊查询小bug

### ISSUE THREAD

**Issue by 919946646** [sunkaixuan/SqlSugar#423]
测试数据库 PostgreSQL
数据表： tablename
其中一个字段：title
title字段的某个内容： 这是一个测试AAbbdd

使用方法:
string sql="select * from tablename WHERE 1=1 and title like '%AA%'";
var data=db.SqlQueryable<Entity.tablename>(sql).ToList();

问题：
字段里面有中英文混合内容时候，无法通过英文进行模糊查询，查询中文就能返回结果。
或者字段内容是纯中文或纯英文都没问题

**Comment by sunkaixuan** [comment]
数据库是这样我也没办法，你这个SQL最终还是交给库去执行

**Comment by 919946646** [comment]
可是数据库执行sql是正常的返回啊。也就是说直接执行sql语句返回是正确的结果 ------------------ 原始邮件 ------------------
发件人: "sunkaixuan"<notifications@github.com>
发送时间: 2019年6月18日(星期二) 下午4:13
收件人: "sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com>;
抄送: "919946646"<919946646@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sunkaixuan/SqlSugar] postgre数据库模糊查询小bug (#423)



数据库是这样我也没办法，你这个SQL最终还是交给库去执行
 
&mdash;
