### ISSUE TITLE
并发引起的问题，希望能指点一下

### ISSUE THREAD

**Issue by Yuyg77** [sunkaixuan/SqlSugar#424]
.netcore 发布时，同时大批量请求，不会访问数据库，会等待XX（根据并发量决定）秒,才会大量请求数据库，之前一直是等待，甚至有时候会超时，希望能给解答一下，或者指点一下，十分感谢
 
![image](https://user-images.githubusercontent.com/26400716/59676569-6f7faa80-91fa-11e9-88ae-ce5f44fa045d.png)

![image](https://user-images.githubusercontent.com/26400716/59676512-51b24580-91fa-11e9-8e67-60a7c96d41ce.png)

**Comment by sunkaixuan** [comment]
网站也会要编译时间,ORM第一次请请也会慢点

**Comment by Yuyg77** [comment]
我的意思可能没有表达清楚，是网站已经发布完成了，开始访问时，但批量并发，会出现那这个问题

**Comment by Yuyg77** [comment]
而且这个时间等待基本都是1分钟以上
