### ISSUE TITLE
postgre数据库模糊查询bug

### ISSUE THREAD

**Issue by 919946646** [sunkaixuan/SqlSugar#425]
**备注：同样的sql语句在数据库中直接执行返回是正常的。**

测试数据库 PostgreSQL
数据表： tablename
其中一个字段：title
title字段的某个内容： 这是一个测试AAbbdd

使用方法:
string sql="select * from tablename WHERE 1=1 and title like '%AA%'";
var data=db.SqlQueryable<Entity.tablename>(sql).ToList();

问题：
字段里面有中英文混合内容时候，无法通过英文进行模糊查询，查询中文就能返回结果。
或者字段内容是纯中文或纯英文都没问题

**备注：同样的sql语句在数据库中直接执行返回是正常的。**

**Comment by sunkaixuan** [comment]
先用db.ado.sqlquery<T>,已修复

**Comment by sunkaixuan** [comment]
后续会发布
