### ISSUE TITLE
支持Mysql 的Json字段吗？

### ISSUE THREAD

**Issue by 463728946** [sunkaixuan/SqlSugar#427]
大神！一直用你这个框架，最近有个项目有些字段想用Mysql的Json格式，初步试了一下好像不行，想跟你确认一下

**Comment by sunkaixuan** [comment]
是最新版本吗

**Comment by sunkaixuan** [comment]
如果实体是对象的话要加上     [SqlSugar.SugarColumn(IsJson = true)]
        public Order Order { get; set; }
