### ISSUE TITLE
ExecuteCommandIdentityIntoEntity与ExecuteReturnEntity 方法，区别在哪里？？？

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#43]
ExecuteCommandIdentityIntoEntity与ExecuteReturnEntity 方法，区别在哪里？？？

**Comment by sunkaixuan** [comment]
返回值不一样动点脑子大哥

**Comment by haibozhou1011** [comment]
看来你的做人有问题，我要是仅仅问你返回值不一样，那我就不会问你了，大哥，我肯定问题，具体哪些不一样啊！！

**Comment by sunkaixuan** [comment]
你F12不会看一下吗

        public virtual T ExecuteReturnEntity()
        {
            ExecuteCommandIdentityIntoEntity();
            return InsertObjs.First();
        }
