### ISSUE TITLE
Oracle 下查询函数 SqlFunc.HasValue 相关函数存在bug

### ISSUE THREAD

**Issue by ZeroMac** [sunkaixuan/SqlSugar#433]
SqlFunc.HasValue 在Oracle 下生成语句 列名<>'' && 列名 is not null 因为Oracle 空字符串问题引起查询条件恒为false

**Comment by sunkaixuan** [comment]
ORACLE不要用这个函数用 it.name!=null 或者it.name!=""

**Comment by ZeroMac** [comment]
是否考虑后续版本修复一下这个问题
