### ISSUE TITLE
升级到最新版5.0.0.8后错误信息

### ISSUE THREAD

**Issue by AjuPrince** [sunkaixuan/SqlSugar#436]
数据库：Sql Server2008R2
问题1：此连接不支持 MultipleActiveResultSets。（在数据库连接字符串里加上MultipleActiveResultSets=true|false）后还是会出现这个问题
问题2：
![image](https://user-images.githubusercontent.com/16829343/60075360-b79d5080-9757-11e9-964f-b9c23825f78d.png)
执行事务后，会出现锁表的现象

**Comment by sunkaixuan** [comment]
给我一个可以重现的DEMO我没重现出来

**Comment by ligg** [comment]
好像的确是有这个问题，sqlserver 2008 R2会出现，sqlserver 2012暂时还没有出现
随便写上10个查询的接口，每个接口里都是new SqlSugarClient  然后前端页面上load的时候直接调这10个接口，页面多刷几次就会出现，我换了4.9.9.10和5.0.0.13和5.0.0.15都一样

**Comment by SanQi2211** [comment]
到现在还是有这个问题
