### ISSUE TITLE
请求CSharpDataType增加TimeSpan类型

### ISSUE THREAD

**Issue by cqvol** [sunkaixuan/SqlSugar#438]
打算手动把time从原有DateTime改成TimeSpan,但CSharpDataType并没有这个类型

MySqlDbBind.MappingTypesConst.RemoveAll(w => w.Key == "time");
MySqlDbBind.MappingTypesConst.Add(new KeyValuePair<string, CSharpDataType>("time", CSharpDataType.TimeSpan));

**Comment by sunkaixuan** [comment]
添加了
