### ISSUE TITLE
看来你的做人有问题，我要是仅仅问你返回值不一样，那我就不会问你了，大哥，我肯定问你，具体哪些不一样啊！！

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#44]
看来你的做人有问题，我要是仅仅问你返回值不一样，那我就不会问你了，大哥，我肯定问你，具体哪些不一样啊！！

**Comment by haibozhou1011** [comment]
你写的东西是不错的，但是你也不要重伤人啊，你的文档也没有说这两个差别，我想我问一下，也不至于，要被你鄙视吧？？

**Comment by sunkaixuan** [comment]
你F12看一下不就知道了吗，除了返回值不一样没别的不一样    
 public virtual T ExecuteReturnEntity()
        {
            ExecuteCommandIdentityIntoEntity();
            return InsertObjs.First();
        }
