### ISSUE TITLE
文档网站拉至底部无限弹跳滚动

### ISSUE THREAD

**Issue by Imhven** [sunkaixuan/SqlSugar#441]
http://www.codeisbug.com/Doc/8/1150

![QQ图片20190629111218](https://user-images.githubusercontent.com/3889504/60379078-ee78ac80-9a5e-11e9-812c-f0f848d8e85e.png)

**Comment by AtlantisDe** [comment]
没毛病 我也发现了这个问题 我想给作者发个消息告诉他的 一忙又搞忘记了

不知道它用了什么代码 导致这样 无限跳动..很影响 查看文档

**Comment by sunkaixuan** [comment]
新官网在做了
