### ISSUE TITLE
实体与表映射出错。Bad IL format

### ISSUE THREAD

**Issue by ZhangGaoxing** [sunkaixuan/SqlSugar#444]
版本：.net core preview5
数据库：postgresql 11

我看到了一个错误相同但被关闭的issue，希望这个问题可以被尽快解决

**Comment by sunkaixuan** [comment]
preview5 暂时还不能用

**Comment by ZhangGaoxing** [comment]
问题没有解决却对issue进行关闭？

**Comment by ZhangGaoxing** [comment]
在本地已经解决此问题，我最近会提交一个PR
相关issue：https://github.com/dotnet/coreclr/issues/24330

**Comment by dj2792** [comment]
@ZhangGaoxing 如何解决呢？上个问题就是我提交的


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by zenglei286** [comment]
这个错误 和数据库列名 和属性的大小写不一致是不是有关系
