### ISSUE TITLE
关于主从表插入的问题

### ISSUE THREAD

**Issue by Cloud33** [sunkaixuan/SqlSugar#445]
关于主从表插入的问题，是否可以像EF一样，直接把这个主表（带子表信息）对象插入到数据库中？现在好像没办法做到，我现在是使用foreach 主表列表，插入主表数据，返回主表Id，然后更新到子表中，批量插入子表，有没有更好的方式？

**Comment by guliang21** [comment]
这问题楼主有好方法了么?

**Comment by Cloud33** [comment]
先使用ToSQL，生成SQL语句，然后再自己替换，一次性把语句提交到数据库，不是常规方式。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: guliang21<mailto:notifications@github.com>
发送时间: 2020年3月12日 10:19
收件人: sunkaixuan/SqlSugar<mailto:SqlSugar@noreply.github.com>
抄送: Jack Feng<mailto:userfl@live.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [sunkaixuan/SqlSugar] 关于主从表插入的问题 (#445)


这问题楼主有好方法了么?

―
