### ISSUE TITLE
批量插入5000条测试数据  出BUG  作者说了不用担心 我现在很担心啊

### ISSUE THREAD

**Issue by AtlantisDe** [sunkaixuan/SqlSugar#448]
### 批量插入数据量时候 出BUG
- 请参考这个文章
- - [提升SQLite数据插入效率低、速度慢的方法 - fugaoting的博客 - CSDN博客](https://blog.csdn.net/fugaoting/article/details/88732027)
- [使用事务操作SQLite数据批量插入，提高数据批量写入速度，源码讲解](https://www.cnblogs.com/wuhuacong/p/3310008.html)
- 看能解决这个批量处理问题吗?
- 用事务处理机制
批量插入数据 BUG  作者说了不用担心 
我现在很担心啊 

我测试插入5000条数据量 (少量不会出问题)

出现这样错误:
```C#
string or blob too big statement too long 

两个字段 guid 主键

body 内容 这里我测试时放入一个24k文本内容
插入 出现 挂了.
body = File.ReadAllText(@"D:\24k.txt", Encoding.UTF8)

```
具体请看图片

![avatar](https://cdn.layui.com/upload/2019_7/3712296_1562311140505_22413.png)
![avatar](https://cdn.layui.com/upload/2019_7/3712296_1562311073648_91723.png)

### 代码
- here is code
```C#
 System.Diagnostics.Stopwatch stopwatch = new System.Diagnostics.Stopwatch();
                    stopwatch.Reset();
                    stopwatch.Start();

                    using (var db = Aleseocore.Module.Aleseo.Database.Main.Base.GetInstance_demo_guid())
                    {

                        var t2 = db.Insertable(demo_Guiditems.ToArray()).ExecuteCommand();
                    }

                    stopwatch.Stop();
                    Console.WriteLine("成功导入{0}条数据 ，用时{1}秒。", demo_Guiditems.Count, stopwatch.Elapsed.TotalSeconds);

                    Console.WriteLine("执行完毕");
```

**Comment by sunkaixuan** [comment]
https://github.com/sunkaixuan/SqlSugar/wiki/f.Utilities 看pageeach用法，目前就SQLITE有长度问题，不过也有方案可以解决

**Comment by AtlantisDe** [comment]
> https://github.com/sunkaixuan/SqlSugar/wiki/f.Utilities 看pageeach用法，目前就SQLITE有长度问题，不过也有方案可以解决

成功导入10000条数据 ，用时7.6919321秒。  牛逼大了 终于 找到精髓了.

```c#
 db.Utilities.PageEach(demo_Guiditems, 100, list =>
{
 var t2 = db.Insertable(list).ExecuteCommand();
});
```

**Comment by AtlantisDe** [comment]
1.当有写操作时，其他读操作会被驳回

2.当有写操作时，其他写操作会被驳回

3.当开启事务时，在提交事务之前，其他写操作会被驳回

4.当开启事务时，在提交事务之前，其他事务请求会被驳回

5.当有读操作时，其他写操作会被驳回

6.读操作之间能够并发执行
