### ISSUE TITLE
SugarColumn(IsIgnore = true)并没有排除属性数据库操作

### ISSUE THREAD

**Issue by xiaogan18** [sunkaixuan/SqlSugar#45]
属性定义：
`[SugarColumn(IsIgnore = true)]
        public EntityState EntityState
        {
            get
            {
                return this.entityState;
            }
            set
            {
                this.entityState = value;
            }
        }`

数据库操作：
`DB.Insertable(listAdd.ToArray()).ExecuteCommand();`

异常：
捕捉到 System.Data.SqlClient.SqlException
  HResult=-2146232060
  Message=列名 'EntityState' 无效。
  Source=.Net SqlClient Data Provider
  ErrorCode=-2146232060
  Class=16
  LineNumber=2
  Number=207
  Procedure=""
  Server=175.16.8.56
  State=1
  StackTrace:
       在 SqlSugar.AdoProvider.ExecuteCommand(String sql, SugarParameter[] parameters)
       在 SqlSugar.InsertableProvider`1.ExecuteCommand()
       在 Nurse.BLL.CCAdapter.SaveRange[T](DBProxyContext DB, IEnumerable`1 list) 位置 e:\workplace\NurseNew\Nurse.BLL\DBProxy\CCAdapter.cs:行号 111
  InnerException:

**Comment by sunkaixuan** [comment]
这玩意儿是在BASE类里面的EntityState，不要用EF的实体

**Comment by xiaogan18** [comment]
我也没办法，旧代码改造，原来的entity里面就大量使用了这个字段。有没有办法排除它，不做数据库操作

**Comment by sunkaixuan** [comment]
var t6 = db.Insertable(insertObj).IgnoreColumns(it => it == "EntityState" ).ExecuteReturnIdentity();

**Comment by xiaogan18** [comment]
可以用特性排除吗

**Comment by sunkaixuan** [comment]
特性排除不了，因为是微软的类

**Comment by xiaogan18** [comment]
不是微软的类，entitybase是我自己定义的，其他entity都是继承自entitybase的

**Comment by sunkaixuan** [comment]
entitybase 继承了什么？

**Comment by xiaogan18** [comment]
entitybase没有继承了

**Comment by xiaogan18** [comment]
我发现，只有在进行批量操作的时候才会异常。单条数据的时候是没有问题的
