### ISSUE TITLE
定义字段长度

### ISSUE THREAD

**Issue by fangglx** [sunkaixuan/SqlSugar#452]
![image](https://user-images.githubusercontent.com/45784335/60853956-e7a52300-a230-11e9-9910-d9038015fe7d.png)
内容很长,请问我该如何定义类似于数据库中的text类型长度

**Comment by MonkSoul** [comment]
指定字段类型为 `text`即可，无需长度。

**Comment by fangglx** [comment]
> 字段指定类型为`text`即可，无需长度。

我该如何定义呢
![image](https://user-images.githubusercontent.com/45784335/61021186-fc212100-a3d2-11e9-82cc-2f809adae5cb.png)

这样吗
