### ISSUE TITLE
关于分布式事务的疑问

### ISSUE THREAD

**Issue by the404** [sunkaixuan/SqlSugar#456]
我看到SqlSugarClient中的分布式事务操作,代码应该类似于这种,是不是这样子呢?当然conn是可以无限扩展的,这种事务的话对比transactionscope有什么优缺点呢?

这种分布式事务和服务的分布式事务是完全不同的,只是一个服务对多个(不同机器或不同实例)数据库的事务操作
,而多服务的分布式事务是比如abc三个接口调用,c接口失败了,要回滚ab两个接口,那种回滚就不是这个类能完成的了

try{
     var conn1=new();
     var tran1 = conn1.begintransaction();
     conn1.docrud()xxxx;

     var conn2 = new();
     var tran2 = conn2.begintransaction();     
     conn2.docrud()xxxx;

    tran1.commit(); // 这里会出现问题,比如tran1 提交后,断网(想象成数据库2挂了)使得tran2提交失败了
    tran2.commit();
}
catch
{
     tran1.rollback();  // 这时候 tran1就回滚失败了,因为tran1已经commit,下面有错误截图
     tran2.rollback();
}
finaly{
    conn1.close();
    conn2.close();
}
![image](https://user-images.githubusercontent.com/5737075/61019494-f6284180-a3cc-11e9-858d-3e78c9492db6.png)

**Comment by the404** [comment]
基本我现在确认这个分布式事务是不ok的,应该还是用dtc,transactionscope 会更好,否则微软为什么要出一个windows服务强关联的transactionscope类呢

**Comment by MonkSoul** [comment]
通过Aop实现跨类，跨方法的事务处理。

**Comment by the404** [comment]
![image](https://user-images.githubusercontent.com/5737075/61020024-d72aaf00-a3ce-11e9-9611-ba0da05e00a9.png)

**Comment by the404** [comment]
其实transactionscope这个类也是个垃圾,首先只能在windows上用,而且不好用,非常脆弱,一般不会用

而成熟的两步提交,3步提交目前没看到.net的版本...

**Comment by sunkaixuan** [comment]
我这个是一个服务里面用的，如果是跨服务用CAP事务吧 SUGAR也支持 db.ado.connection 能拿 到连接对象 然后给db.ado.tran赋值就行了
