### ISSUE TITLE
Oracle执行MergeTable后再执行分页会崩溃

### ISSUE THREAD

**Issue by lindenrty2** [sunkaixuan/SqlSugar#458]
Oracle执行MergeTable后再执行分页会崩溃,原因是查询起别名以后不能用Select * ,必须用Select MergeTable.*

**Comment by lindenrty2** [comment]
发生问题的SQL如下:

SELECT * FROM (SELECT *,ROW_NUMBER() OVER(ORDER BY MergeTable.CreateDate desc) AS RowIndex  FROM 
(
  SELECT  CAST("S"."ID" AS VARCHAR2(4000)) AS "WAREHOUSEID" , "S"."WAREHOUSENO" AS "WAREHOUSENO" FROM "WMS_WAREHOUSE" s 
) MergeTable  
 WHERE ( "ISDEL" = 1 ) ) T WHERE RowIndex BETWEEN 1 AND 10

**Comment by sunkaixuan** [comment]
暂未重现

**Comment by uianqian** [comment]
var page = Db.Queryable<TB_TASK,TB_CATEGORY,TB_NODE>((sa, sb, sc) => new object[] {
                         JoinType.Left, sa.CATEGORYID==sb.ID,
                         JoinType.Left, sa.NODEID==sc.ID 
                     })
                      .Select((sa, sb, sc) => new
                      {
                          sa.ID,
                          sa.TASKAPPCONFIGJSON,
                          sa.TASKCREATEUSERID 
                      })
                      .MergeTable().AS("T")
                     .Where(GetWhere(searchStr));
                var Tempdb = page.OrderBy(pagination.sidx + strSort);
                var s2 = Tempdb.ToPageList(pagination.page, pagination.rows, ref pageCount);

多表查询的时候，进行分页，跟踪sql发现，分页的sql SELECT *,ROW_NUMBER() OVER(ORDER BY MergeTable.CreateDate desc) AS RowIndex  这时就会报错，改成 SELECT MergeTable.*,ROW_NUMBER() OVER(ORDER BY MergeTable.CreateDate desc) AS RowIndex 就没问题
