### ISSUE TITLE
实体类增加[SugarColumn(IsJson = true)]特性，更新某个列报错

### ISSUE THREAD

**Issue by feiyit** [sunkaixuan/SqlSugar#465]
实体类： 某个属性
[SugarColumn(IsJson = true)]
public List<SwGoodsImageJson> ImageList { get; set; }=new List<SwGoodsImageJson>();

更新某个列方法：
await Db.Updateable<Sw_goods>(m=>m.IsAudit==false).Where(m=>list.Contains(m.Guid)).ExecuteCommandAsync();

Error：
English Message : UpdateColumns no support IsJson
 Chinese Message : SetColumns方式更新不支持IsJson，你可以使用db.Updateable(实体)的方式更新

**Comment by feiyit** [comment]
Mysql

**Comment by sunkaixuan** [comment]
目前是不支持
