### ISSUE TITLE
.net core codefirst 字段默认值问题

### ISSUE THREAD

**Issue by xiexihui** [sunkaixuan/SqlSugar#479]
给字段设置默认值为 getdate()   在生成表时会自动添加两个单引号  ('getdate()')，导致添加数据不成功

[SugarColumn(IsNullable = false, ColumnDescription = "创建时间", ColumnDataType = "datetime", DefaultValue = "getdate()")]

**Comment by xiexihui** [comment]
[SugarColumn(IsNullable = false, ColumnDescription = "创建时间", ColumnDataType = "datetime", DefaultValue = "getdate()")]

**Comment by litdev** [comment]
复议，我也刚发现这个问题，正准备来Issues上来反馈呢
