### ISSUE TITLE
Oracle 执行多表查询MergeTable后抛出异常

### ISSUE THREAD

**Issue by uianqian** [sunkaixuan/SqlSugar#485]
Oracle多表mergeTable分页查询
` var page = Db.Queryable<TB_TASK,TB_CATEGORY,TB_NODE>((sa, sb, sc) => new object[] {
                         JoinType.Left, sa.CATEGORYID==sb.ID,
                         JoinType.Left, sa.NODEID==sc.ID 
                     })
                      .Select((sa, sb, sc) => new
                      {
                          sa.ID,
                          sa.TASKAPPCONFIGJSON,
                          sa.TASKCREATEUSERID 
                      })
                      .MergeTable().AS("T")
                     .Where(GetWhere(searchStr));
                var list = page.OrderBy(pagination.sidx + strSort)
                     .ToPageList(pagination.page, pagination.rows, ref pageCount);`
源码中  `mergeQueryable.AS(tableName).Select<T>("*"); `设置了查询分页默认为*,导致组装sql时按照sqlserver的写法进行分页查询，跟踪sql如下，oracle不支持此写法，目前解决是MergeTable.* 解决该问题。
`SELECT *,ROW_NUMBER() OVER(ORDER BY ID asc) AS RowIndex 
FROM  (SELECT  "SA"."ID" AS "ID" , "SA"."TASKAPPCONFIGJSON" AS "TASKAPPCONFIGJSON"  
   FROM "TB_TASK" 
   sa Left JOIN "TB_CATEGORY" sb ON ( "SA"."CATEGORYID" = "SB"."ID" )  
   Left JOIN "TB_NODE" sc ON ( "SA"."NODEID" = "SC"."ID" )  
   ) MergeTable  `

找到源码MergeTable `修改，临时解决，希望查看是否存在此bug`
`public virtual ISugarQueryable<T> MergeTable()
        {
            Check.Exception(this.MapperAction != null || this.MapperActionWithCache != null, "'Mapper’ needs to be written after ‘MergeTable’ ");
            Check.Exception(this.QueryBuilder.SelectValue.IsNullOrEmpty(), "MergeTable need to use Queryable.Select Method .");
            Check.Exception(this.QueryBuilder.Skip > 0 || this.QueryBuilder.Take > 0 || this.QueryBuilder.OrderByValue.HasValue(), "MergeTable  Queryable cannot Take Skip OrderBy PageToList  ");
            ToSqlBefore();
            var sql = QueryBuilder.ToSqlString();
            var tableName = this.SqlBuilder.GetPackTable(sql, "MergeTable");
            var mergeQueryable = this.Context.Queryable<ExpandoObject>();
            mergeQueryable.QueryBuilder.Parameters = QueryBuilder.Parameters;
            mergeQueryable.QueryBuilder.WhereIndex = QueryBuilder.WhereIndex + 1;
            mergeQueryable.QueryBuilder.JoinIndex = QueryBuilder.JoinIndex + 1;
            mergeQueryable.QueryBuilder.LambdaExpressions.ParameterIndex = QueryBuilder.LambdaExpressions.ParameterIndex;
            return mergeQueryable.AS(tableName).Select<T>("MergeTable.*");
        }`

**Comment by kennard-owen** [comment]
你好，我更改了源码，请问更改后怎么再项目中引用呢？

**Comment by uianqian** [comment]
下载官方的项目到本地，修改源码，引用你自己本地的项目。不能nuget，等bug修复之后再nuget吧

**Comment by uianqian** [comment]
可以下载源码，引用到项目中。等bug修复之后在nuget吧。


| |
零星
|
|
邮箱：uianqian@126.com
|

签名由 网易邮箱大师 定制

在2019年09月16日 13:19，kennard-owen 写道：

你好，我更改了源码，请问更改后怎么再项目中引用呢？
