### ISSUE TITLE
事务中如果有批量操作就直接提交事务了？

### ISSUE THREAD

**Issue by ChiyuanLu** [sunkaixuan/SqlSugar#487]
oracle中发现如果执行操作的几个表中有一个是用了批量插入的方法，执行完就直接把事务提交了。
mysql中不知道是没有这个问题还是我没有发现。
事务中是不能有这样批量提交的操作吗？

**Comment by yilei63** [comment]
我也遇到了与你一样的问题，请问解决了吗？

**Comment by ChiyuanLu** [comment]
> 我也遇到了与你一样的问题，请问解决了吗？

木有  循环插入了。。。。
