### ISSUE TITLE
where条件中包含删除语句被执行

### ISSUE THREAD

**Issue by inc-zz** [sunkaixuan/SqlSugar#489]
我有一些脚本是直接通过用户输入来配置的， 一部分查询条件的脚本在使用如 _db.QueryAble<Model>().where("1=1 DELETE FROM TABLE xxx ") 诸如此类的delete语句也一并被执行，是否有统一调配的防注入方式还是单独对诸如where或者tableName这样的自行做防注入处理？

**Comment by sunkaixuan** [comment]
全局过滤器 文档
