### ISSUE TITLE
查询日期比较问题

### ISSUE THREAD

**Issue by cfzping2019** [sunkaixuan/SqlSugar#494]
sqlserver 数据库，查询比较Date类型字段时，下面几种写法都会有问题

` var r68 = db.Queryable<OrderData>()
              .Where(b => b.OrderDate.ToString("yyyyMMdd").Equals("20190809"))    ////会抛异常
              .ToList();
            var r69 = db.Queryable<OrderData>()
              .Where(b => b.OrderDate.ToString("yyyy-MM-dd").Equals("2019-08-09"))    ////执行正常，但是取不到值
              .ToList();
            var r70 = db.Queryable<OrderData>()
              .Where(b => SqlFunc.DateIsSame(b.OrderDate, new DateTime(2019, 8, 9)))    //会抛异常
              .ToList();`

执行正确的如下：
 DateTime dateTime = new DateTime(2019, 8, 9);
            var r66 = db.Queryable<Pick_Batch>()
                .Where(b => SqlFunc.DateIsSame(b.PickDate, dateTime))
                .ToList();
            var r67 = db.Queryable<Pick_Batch>()
                .Where(b => SqlFunc.DateIsSame(b.PickDate, DateTime.Now.AddDays(-5)))
                .ToList();

可否修正上面的问题？

**Comment by uianqian** [comment]
linq表达式里面不支持原生的字符串转换，因为要映射成sql。 所以提供了sql.Func功能的扩展
