### ISSUE TITLE
mssql 包含with as 结果集怎么解决（sql 递归用到）

### ISSUE THREAD

**Issue by yuwencong** [sunkaixuan/SqlSugar#498]
这个怎么用SqlQueryable 执行下列类型语句
with cte
as 
(--父项 
select Id,ParentId from TeacherGroup where Id='DEAA63D1-4BEE-4FBA-9AB6-7B9012926C65'
union all 
--递归结果集中的下级 
select t.Id,t.ParentId from TeacherGroup as t 
inner join cte as c on t.ParentId = c.Id 
)

select stgr.*,usr.Account,usr.RealName from StudentTeacherGroupRelation  stgr
left join Sys_User usr on usr.Id=stgr.UserId
where stgr.TeacherGroupId in (select Id from cte)

**Comment by sunkaixuan** [comment]
太复杂还是写SQL吧 名者分2次操作
