### ISSUE TITLE
请问是否有方法从数据库取继承关系的树形数据并输出为Json

### ISSUE THREAD

**Issue by xqyi** [sunkaixuan/SqlSugar#5]
如数据表核心结构为ItemID、Parent_ItemID构造的父子关系数据，sqlsugar如何取该表数据并导出为Json，json格式为[{"ItemID":"xx","SubItem",[{"ItemID":"xx","SubItem":[...]}]}]

**Comment by sunkaixuan** [comment]
没有该方法

**Comment by qinxingnet** [comment]
这需要业务系统自已用json.net 之类的工具完成存取吧。不要在底层数据库仓储来进行，会很影响性能！！
