### ISSUE TITLE
Oracle数据库查询整表数据时 ToPageList方法sql异常，无法查出数据

### ISSUE THREAD

**Issue by lsunflower** [sunkaixuan/SqlSugar#500]
SqlSugar版本：
5.0.0.9

数据库版本：
12c

异常消息：
Oracle.ManagedDataAccess.Client.OracleException:“ORA-00923: 未找到要求的 FROM 关键字”

表达示：
var list = SqlContext.Queryable<A1BusinessProcessDesign>()
            .WhereIF(status == null, a => a.Status != 99)
            .OrderBy(a => a.CreateDate, OrderByType.Desc)
            .OrderBy(a => a.UpdateDate, OrderByType.Desc)
            .Select(a=>a)
            .ToPageList(current, pageSize, ref total);

生成的SQL为(参数已替换)：
SELECT *
  FROM (SELECT *,
               ROW_NUMBER() OVER(ORDER BY "CREATEDATE" DESC, "UPDATEDATE" DESC) AS RowIndex
          FROM "A1BUSINESSPROCESSDESIGN"
         WHERE ("STATUS" <> 99)) T
 WHERE RowIndex BETWEEN 1 AND 20

正确的SQL应为：
SELECT *
  FROM (SELECT **A.***,
               ROW_NUMBER() OVER(ORDER BY "CREATEDATE" DESC, "UPDATEDATE" DESC) AS RowIndex
          FROM "A1BUSINESSPROCESSDESIGN" **A**
         WHERE ("STATUS" <> 99)) T
 WHERE RowIndex BETWEEN 1 AND 20

**Comment by sunkaixuan** [comment]
.select("a.*") 或者 .Select(a=>a)这句删掉，后续我完善这一块
