### ISSUE TITLE
Ver5.0.0.9查询偶发性报错

### ISSUE THREAD

**Issue by blackxea** [sunkaixuan/SqlSugar#503]
在.Net Core中使用Queryable查询时，偶尔会出现
ArgumentNullException: Value cannot be null.
Parameter name: source

**Comment by kuyu05** [comment]
我也是这个问题，同样的5.0.0.9版本。
使用SaveableAsync的时候出现的

**Comment by penjay** [comment]
同样的问题，好像没有人维护了？？？

**Comment by h-xiaojun** [comment]
小弟是在使用Insertable时偶尔出现的。换成SQL插入也会出现

**Comment by sunkaixuan** [comment]
给个能重现的例子给我

**Comment by sunkaixuan** [comment]
目前发现问题是单例引起的，不要将sqlsugarclient静态化 把证NEWb同来试试，其它用户改过就好了
