### ISSUE TITLE
建议在Sugar中加入并发处理

### ISSUE THREAD

**Issue by zhigao99** [sunkaixuan/SqlSugar#504]
EF中有并发处理机制，而Sugar没有，建议在Sugar中增加，补齐短板，提高竟争力；
比如当用户的实体类型中有TimeStamp字段时，Sugar在更新时可以把TimeStamp字段当做条件查询，只有相等才能成功。

比如下面的语句:

exec sp_executesql N'UPDATE [dbo].[Students]
SET [StudentName] = @0
WHERE (([StudentId] = @1) AND ([RowVersion] = @2))
SELECT [RowVersion]
FROM [dbo].[Students]
WHERE @@ROWCOUNT > 0 AND [StudentId] = @1',N'@0 nvarchar(max) ,@1 int,@2 binary(8)',@0=N'Steve',@1=1,@2=0x00000000000007D1
go

在更新对象实例到数据库时，从使用先前从数据库取回RowVersion的值和主键作为条件来更新数据行，从而实现乐观并发控制。

参照：
https://www.cnblogs.com/zery/p/3269093.html

**Comment by sunkaixuan** [comment]
updateable 文档最下面

**Comment by pandaali** [comment]
> updateable 文档最下面

最近正好用到这块，检验过db.Updateable(data).IsEnableUpdateVersionValidation().IgnoreColumns(it => new { it.Timestamp }).ExecuteCommand();
，通过并发10个线程模拟高并发，希望实现计数累加，会出现不同线程同时更新成功的问题，导致累加出现问题
