### ISSUE TITLE
可以在 insert,delete update 加入拦截器吗？

### ISSUE THREAD

**Issue by 840900649** [sunkaixuan/SqlSugar#508]
现在已有Query 拦截器，如果 在insert 时候，我需要加入某个特殊字段 类似
db.QueryFilter.Add(
               new SqlFilterItem()
                {
                    FilterValue = filterDb => {
                        return new SqlFilterResult()
                        {
                            Sql = "TenantId=" + tenantId
                        };
                    }
});
改为
db.InsertFilter.Add(
               new SqlFilterItem()
                {
                    FilterValue = filterDb => {
                        return new SqlFilterResult()
                        {
                             TenantId=  tenantId,
                             AddUser=  addUser
                        };
                    }
});

**Comment by fantlz** [comment]
_db.Aop.OnExecutingChangeSql = (sql, pars) => //SQL执行前 可以修改SQL
{
}
可以用这个事件对sql和参数做修改实现
