### ISSUE TITLE
postgresql 的json和jsonb类型数据插入与修改，该如何做

### ISSUE THREAD

**Issue by bamboomemory** [sunkaixuan/SqlSugar#509]
Model中的字段我如下设计  
        /// <summary>
        /// Desc:附件
        /// Default:
        /// Nullable:True
        /// </summary>      
        [SugarColumn(ColumnDataType= "json")]     
        public string file { get; set; }

在执行插入数据的时候会报错 Npgsql.PostgresException (0x80004005): 42804: 字段 "file" 的类型为 json, 但表达式的类型为 text

**Comment by bamboomemory** [comment]
postgresql 某张表的某个字段为json或jsonb,该如何执行插入和修改呢，试了很多种方式，都不行，希望得到帮助……

**Comment by sunkaixuan** [comment]
[SugarColumn(ColumnDataType= "json")]     
    public 可以序列化的对象 file { get; set; } 例始 [1,2,3] 那么就是list<string>  如果是 {id:1} 那么就是一个类
