### ISSUE TITLE
根据ORACLE生成DBFIRST的实体类报错

### ISSUE THREAD

**Issue by terrydash** [sunkaixuan/SqlSugar#51]
数据库表比较多 几千张
每次生成3分钟左右保存
无奈获取表名一个个生成
报错信息
测试名称:	TestCreateClassName
测试全名:	JWXTService.Tests.UnitTest1.TestCreateClassName
测试源:	E:\GIT\教学质量数据统计平台\JWXTService\JWXTService\JWXTService.Tests\UnitTest1.cs:第 12 行
测试结果:	未通过
测试持续时间: 	0:03:36.5063797

结果 的堆栈跟踪:	
在 SqlSugar.Check.Exception(Boolean isException, String message, String[] args)
   在 SqlSugar.DbFirstProvider.ToClassStringList(String nameSpace)
   在 SqlSugar.DbFirstProvider.CreateClassFile(String directoryPath, String nameSpace)
   在 JWXTService.Tests.UnitTest1.TestCreateClassName() 位置 E:\GIT\教学质量数据统计平台\JWXTService\JWXTService\JWXTService.Tests\UnitTest1.cs:行号 32
结果 的消息:	
测试方法 JWXTService.Tests.UnitTest1.TestCreateClassName 引发了异常: 
SqlSugar.UtilExceptions: Table 'TDKCCJZHB' error,You can filter it with Db.DbFirst.Where(name=>name!="TDKCCJZHB" ) 
 Error message:ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
结果 的标准输出:	TDKCCJZHB

**Comment by sunkaixuan** [comment]
结果 的消息:
测试方法 JWXTService.Tests.UnitTest1.TestCreateClassName 引发了异常:
SqlSugar.UtilExceptions: Table 'TDKCCJZHB' error,You can filter it with Db.DbFirst.Where(name=>name!="TDKCCJZHB" )

**Comment by sunkaixuan** [comment]
个别表不支持过用WHERE过滤掉
