### ISSUE TITLE
数据实体float？ 类型从数据库读取数据出错

### ISSUE THREAD

**Issue by duyanming** [sunkaixuan/SqlSugar#52]
数据实体类型为 float？ 数据库 MySQL 5.7 字段类型是float 可空。从数据库查出来的数据不对。

**Comment by sunkaixuan** [comment]
用 db.first生成实体看一下， 数据库里面的float对应C#应该不是float

**Comment by duyanming** [comment]
数据实体类型 原来是 （float?） 可空类型  我改成（float） 就好了！我没有用db.first

**Comment by sunkaixuan** [comment]
数据库float 最正确的对应是C# double 不是float
