### ISSUE TITLE
Mysql版本5.7+版本，数据库类型Json，读取中文乱码

### ISSUE THREAD

**Issue by feiyit** [sunkaixuan/SqlSugar#524]
数据库：Mysql
版本：5.7+
数据库字段类型：Json

实体字典属性，增加Json特性
` [SugarColumn(IsJson = true)]
        public List<TableBody> TableJson { get; set; } = new List<TableBody>();`

保存的时候，Json字符串中有中文，保存到数据库显示中文

但是在读取的时候，就出现乱码了。

经过查询资料，在读取的时候，好像并没有使用原生的JSON函数去读取导致中文乱码。

https://bbs.csdn.net/topics/391902963
读取JSON字符串必须要使用mysql提供的原生的JSON函数去读取，跟常规的SQL读取如果有中文的话会产生乱码的问题！
1.建表
CREATE TABLE `test3` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `data` json DEFAULT NULL,
  `user_name` varchar(128) GENERATED ALWAYS AS (json_extract(`data`,'$.name')) VIRTUAL,
  `data2` json DEFAULT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=utf8;
2.插入数据
insert  into  test3 (data2)  values(json_object("name","中华人民共和国","birthday","2015-05-09"));
3.读取数据
SELECT json_extract(data2,'$.*') as data_value FROM test3

**Comment by Longzhiwu2015** [comment]
CHARSET=utf8mb4

**Comment by siterui** [comment]
同样问题，保存没问题，读取是乱码
