### ISSUE TITLE
插入list时，emoji被截断

### ISSUE THREAD

**Issue by siterui** [sunkaixuan/SqlSugar#525]
`List<entity> mylist =new List<entity>()`
`mylist.Add(myentity);`
`db.Insertable(mylist).ExecuteCommand();`
> 当myentity中的content字段，含有 emoji表情时，表情后面的内容将被截断
`db.Insertable(myentity).ExecuteCommand();`
> 当添加非集合时，不会出现截断情况

**Comment by sunkaixuan** [comment]
特性里面有个加密存储功能
