### ISSUE TITLE
db.Queryable<T> 方法BUG

### ISSUE THREAD

**Issue by huanglanjian** [sunkaixuan/SqlSugar#526]
用db.Queryable<对象>查询数据时，如果对象中有包含数据库没有的字段会报错，但经常会有数据库存的为枚举int4，而对象中需要另一个属性来解释这个枚举值

**Comment by yajore** [comment]
没有的字段你自己要筛选掉啊，不然就当成sql里面的列去查询了，肯定报错

`[SqlSugar.SugarColumn(IsIgnore = true)]
public string Avatar { get; set; }`
