### ISSUE TITLE
sqlSugarCore 5.0.0.10 PostgreSQL驱动多实体有SQL注入问题，单实体JSON类型字段报错

### ISSUE THREAD

**Issue by linbog** [sunkaixuan/SqlSugar#530]
版本：sqlSugarCore 5.0.0.10
我有一个JSON字段实体定义如下：
```csharp
[SugarColumn(IsJson = true, ColumnDataType = "json")]
public string[] Dependencies { get; set; }
```
数据库字段定义如下：

|列名|类型|长度|
|---|---|---|
|dependencies|json|0|

- 一次插入多条时，一般情况下可以插入，单拼出来的SQL中`Dependencies`某个值包含一个`'`（英文单引号）就会出现语法错误；
- 一次插入1条时报错`column "dependencies" is of type json but expression is of type text`；

**Comment by sunkaixuan** [comment]
已修复近期会发布
