### ISSUE TITLE
使用Aop  差异日志功能，出现Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by xiangxingze** [sunkaixuan/SqlSugar#533]
![image](https://user-images.githubusercontent.com/13271663/65582307-bb877b80-dfaf-11e9-8789-1f26fdc1919a.png)
![image](https://user-images.githubusercontent.com/13271663/65582339-cb9f5b00-dfaf-11e9-8605-767921e0c979.png)
也不会进入db.Aop.OnDiffLogEvent 方法
![image](https://user-images.githubusercontent.com/13271663/65582404-ed98dd80-dfaf-11e9-8d69-cabfbeead918.png)

**Comment by fantlz** [comment]
同样遇到了这个问题，差异日志里面更新之前会做一次查询，查询完就报空引用异常了

**Comment by sunkaixuan** [comment]
请给个能重现的DEMO因为我的GITHUB源码里面就有差异日志的DEMO并且能跑的通过

**Comment by xiangxingze** [comment]
> 同样遇到了这个问题，差异日志里面更新之前会做一次查询，查询完就报空引用异常了

你有解决好嘛？

**Comment by xiangxingze** [comment]
> 同样遇到了这个问题，差异日志里面更新之前会做一次查询，查询完就报空引用异常了
@sunkaixuan 
你的问题解决了嘛？是怎么解决的？
