### ISSUE TITLE
SqlServer创建表，给列设置默认值函数变成字符串

### ISSUE THREAD

**Issue by gb123123** [sunkaixuan/SqlSugar#534]
SqlServer默认值，比如GetDate()设置成默认值会变成  ‘GetDate()’，无法绑定函数

protected override string AddDefaultValueSql
 {
         get
         {
                return "alter table {0} ADD DEFAULT '{2}' FOR {1}";
         }
 }

这段代码‘{2}’的单引号要去掉

**Comment by sunkaixuan** [comment]
有添加默认值的方法

**Comment by gb123123** [comment]
哪个方法啊？
