### ISSUE TITLE
dotnet core 使用5.0.0.10版本出现关联查询实体映射的BUG

### ISSUE THREAD

**Issue by xwb2535** [sunkaixuan/SqlSugar#537]
查询写法，
  list = read.Queryable<Rights, UserRight>((r, ur) => new object[] {
        JoinType.Inner,r.Code==ur.RightCode}).Where((r, ur) => ur.UserCode == userId && r.IsUse == Model.IsUse.Using)
            .OrderBy((r, ur) => r.Sort)
                 .Select((r, ur) => new Rights
                 {
                     Code = r.Code,
                     ParentCode = r.ParentCode,
                     RightName = r.RightName,
                     Url = r.Url,
                     Sort = r.Sort,
                     CID = r.CID,
                     IsUse = r.IsUse,
                     PublicRights = r.PublicRights,
                     IsShow = r.IsShow,
                     Icon = r.Icon
                 }).ToList();

![Uploading image.png…]()

其中Rights 还有其他的几个字段未显示在这里赋值。
然后会发现很多字段么有赋值，或者赋值错误。 比如  ParentCode 和RightName 两个字段就是是null.

如果是单表查询没关联，中文什么都会出来。

**Comment by xwb2535** [comment]
![Uploading image.png…]()
图片希望上传解释的是 数据库有值

**Comment by xwb2535** [comment]
另外，4.9 的写法是没问题的，能读取到正确值。 dotnet core 2.0 里面用5.X版本也不行，现在在dotnet 3.0 里面也不行

**Comment by sunkaixuan** [comment]
基本功能是不会有BUG的 除非是特殊使用情况引起的，如果有问题写个控制台程序发给我
