### ISSUE TITLE
导步处理执行连接设置 MultipleActiveResultSets=true的问题

### ISSUE THREAD

**Issue by 83872689** [sunkaixuan/SqlSugar#538]
MultipleActiveResultSets=true; 异步执行多了就会 Invalid operation. The connection is closed.

**Comment by sunkaixuan** [comment]
异步划式下sqlsugarclient不能单例，并且要用完释放

**Comment by Andsirs** [comment]
> 
> 
> 异步划式下sqlsugarclient不能单例，并且要用完释放

看一下#574

**Comment by hjkcmb** [comment]
是需要改成MultipleActiveResultSets=false吗？还是要怎么释放？

**Comment by cnkker** [comment]
怎么解决这个问题的？我没有设置MultipleActiveResultSets这个属性？

**Comment by Cloud33** [comment]
我是用的时候new一个新的连接出来 就没有这个问题了
