### ISSUE TITLE
请问 多表连接的groupby 不能这样写么 ，运行时报错 er.Name 列明无效

### ISSUE THREAD

**Issue by WenRuonan** [sunkaixuan/SqlSugar#546]
t.EnrollDetails = _repository.DB.Queryable<GuestInfo, EnrollA>((gi, er) => new object[]
                  { JoinType.Inner, gi.EnrollID == er.ID && gi.OrderCode == t.OrderCode })
                  .Select((gi, er) => new EnrollDetail
                  {
                      OrderCode = t.OrderCode,
                      Price = gi.SinglePrice,
                      Name = er.Name,
                      EnrollNum = SqlFunc.Subqueryable<GuestInfo>().Where(s => s.OrderCode == t.OrderCode).Count(),

                  }).GroupBy(gi => new Tuple<decimal, string, string>(gi.Price, gi.OrderCode, gi.Name))
                  .Having(gi => gi.OrderCode == t.OrderCode).ToList();

**Comment by sunkaixuan** [comment]
new { Price,orderCode}
