### ISSUE TITLE
ToListAsync 类似方法存在死锁

### ISSUE THREAD

**Issue by hermanfeng** [sunkaixuan/SqlSugar#550]
ToListAsync 类似方法存在死锁 请把所有的await后面都加上.ConfigureAwait(false).
我被迫使用System.Threading.SynchronizationContext.SetSynchronizationContext(null)绕过这个bug

**Comment by Camliar** [comment]
对,我也碰到了.使用同步方法正常  SqlSugar5.0.0.10

**Comment by duyanming** [comment]
+1

**Comment by sunkaixuan** [comment]
请提供重现步骤，有重现步骤后发我邮箱
