### ISSUE TITLE
Queryable连续使用两次，第二次报错

### ISSUE THREAD

**Issue by guandy** [sunkaixuan/SqlSugar#559]
版本号4.9.9.11
`
var query = DbProvider.Queryable<BankEntity, CapitalEntity>(
                (b, c) => new object[] {
                    JoinType.Inner,b.QrfId == c.QrfId
                })
                .Select((b, c) => new BankQuery
                {
                    RentBankId = b.RentBankId,
                    RentBankPro = b.RentBankPro,
                    RentType = b.RentType,
                    BankNo = b.BankNo,
                    RentProp = b.RentProp,
                    RentBusi = b.RentBusi,
                    RentYyyymm = b.RentYyyymm,
                    RentStDate = b.RentStDate,
                    RentEdDate = b.RentEdDate,
                    QrfId = b.QrfId,
                    LesId = b.LesId,
                    RentSum = b.RentSum,
                    BankAcctno = b.BankAcctno,
                    ExeStatus = b.ExeStatus,
                    CompanyId = b.CompanyId,
                    IsSysData = b.IsSysData,
                    Quart = c.Quart,
                    Flat = c.Flat,
                    Flatbus = c.Flatbus,
                    Rise = c.Rise,
                }).MergeTable();

            var totalAmount = query.Sum(x => x.RentSum);

            var totalAmount2 = query.Sum(x => x.RentSum);
`

这句代码 var totalAmount2 = query.Sum(x => x.RentSum);报错

**Comment by sunkaixuan** [comment]
query.chole().Sum(x => x.RentSum);
