### ISSUE TITLE
codefirst 不同的表 相同的字段 相同的主键   则生成相同的约束名称  ,会失败

### ISSUE THREAD

**Issue by hlm750908** [sunkaixuan/SqlSugar#561]
,codefirst  ,这个主键 约束名称可以带上表名称吗 , 我不同的表 , 相同的字段名 结果都生成了pk_c1_c2,然后就失败了

**Comment by linfeng627** [comment]
同上

![image](https://user-images.githubusercontent.com/9949400/80672000-ff120d00-8add-11ea-9ae9-ec17622fbe5a.png)

![image](https://user-images.githubusercontent.com/9949400/80672029-1650fa80-8ade-11ea-9ae1-df213d030c2d.png)
