### ISSUE TITLE
动态组装查询表达式，有支持IN的子查询吗？

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#566]
![image](https://user-images.githubusercontent.com/10756986/67821516-43552e00-faf8-11e9-8acc-dd05506f5fec.png)
官方有找到这个地方有说明，但是产生的Exists 子查询，但是阿里云Adb数据库，对Exists 子查询性能很差，希望组装的是IN的子查询。
类似 select * from b where id in（select id from b where pid = 1）语句

**Comment by sunkaixuan** [comment]
效果是一样的并没封装
