### ISSUE TITLE
求助，sqlsugar支持codefirst模式下用同一实体类动态创建同结构不同名的表吗？

### ISSUE THREAD

**Issue by liruoyu2008** [sunkaixuan/SqlSugar#569]
sqlsugar支持codefirst模式下用同一实体类动态创建同结构不同名的表吗？比如表名+时间这种，设计日志系统的时候需要用到。

**Comment by sunkaixuan** [comment]
支持的  db.mappingtable.add 可以更改真实表名

**Comment by liruoyu2008** [comment]
这种方法确实可以利用映射的表名创建表，但只要添加任何列描述（注释），就会报异常（表或视图不存在），但表其实已创建好。猜测是添加注释时出错。4.9版本发现的此问题。
