### ISSUE TITLE
postgresql数据库dbfirst的时候，大写的表名和列名是无法映射的吗？

### ISSUE THREAD

**Issue by a554317330a** [sunkaixuan/SqlSugar#570]
Db.DbFirst.IsCreateAttribute().Where("TB_USER", "TB_USER_ROL", "TB_ROLE").CreateClassFile(filePath);

结果：
![image](https://user-images.githubusercontent.com/22444484/67932941-ce6d1b80-fbff-11e9-9901-5735a481d464.png)

数据库：
![image](https://user-images.githubusercontent.com/22444484/67932878-b4cbd400-fbff-11e9-8f96-16ba0682aa44.png)

**Comment by sunkaixuan** [comment]
近期会发布 用法如下 CurrentConnectionConfig.MoreSettings.PgSqlIsAutoToLower=false
