### ISSUE TITLE
DbMaintenance.CreateTable报错: 不能对数据类型int指定列宽

### ISSUE THREAD

**Issue by wenliang201314** [sunkaixuan/SqlSugar#572]
使用DbMaintenance.GetColumnInfosByTableName得到了列信息,然后使用DbMaintenance.CreateTable和刚刚得到的列信息创建一个新表,报错"不能对数据类型int指定列宽"

经过调查,一个int列的Length长度为4,需要手动将Length设置为0后,就能正常创建表了

**Comment by xxdqr** [comment]
我也是服了，人家这个是错，明显的是int不需要指定列宽，指定的是string类型的数据才能指定列宽。你理解的给int指定列宽不是此处的那个列宽，你理解的int类型列宽应该是：比如指定为2，就最大只能存储2位的？

**Comment by wenliang201314** [comment]
我说的就是通过DbMaintenance.GetColumnInfosByTableName方法得到的int列的列宽为4,导致创建表不成功.

GetColumnInfosByTableName方法对数字类型的列,列宽应该返回0
