### ISSUE TITLE
只查询一列，ToPageListAsync（x,x,x）报错

### ISSUE THREAD

**Issue by liuyang-1990** [sunkaixuan/SqlSugar#573]
**版本**
SqlSugar 5.0.0.10 

**描述**
ToPageListAsync（1,10,total）报错

**代码**
` RefAsync<int> total = 0;
 var result=await db.Queryable<Test>().Where(x => x.Id == 1).GroupBy(x => x.Name).Select(x => x.Name).ToPageListAsync(1, 10, total);`

**信息**
SqlSugarException: Queryable<String> Error ,String is invalid , need is a class,and can new().

**文件**
请参考https://github.com/liuyang-1990/SugarDemo

**Comment by sunkaixuan** [comment]
已修复近期会同步
