### ISSUE TITLE
where语句的条件重复

### ISSUE THREAD

**Issue by Andsirs** [sunkaixuan/SqlSugar#574]
var result0 = db.Updateable(updateObjext).AS("Order").WhereColumns(t => new { t.Id}).UpdateColumns(t => new { t.Name }).ExecuteCommand();  
会生成where name=@name and name=@name

问题定位：\Asp.Net\SqlSugar\Abstract\SqlBuilderProvider\UpdateBuilder.cs   ToSingleSqlString

**Comment by sunkaixuan** [comment]
这个应该是一个DB在多线程下使用引起的保证一个线程NEW出一个新的。
