### ISSUE TITLE
主从表生成sql语句

### ISSUE THREAD

**Issue by zhaozhaizhu** [sunkaixuan/SqlSugar#577]
var s12 = db.Queryable<Order>().Mapper(it=>it.Items,it=>it.Items.First().OrderId).Single(it=>it.Id==1);

SELECT [Id],[Name],[Price],[CreateTime],[CustomId] FROM [Order]  WHERE ( [Id] = @Id0 )
@Id0:1
SELECT [ItemId],[OrderId],[Price],[CreateTime] FROM [OrderDetail]  WHERE   OrderId IN ('1')
@ConditionalOrderId0:1
为什么不是

SELECT [Id],[Name],[Price],[CreateTime],[CustomId] FROM [Order]  WHERE ( [Id] = @Id0 )
@Id0:1
SELECT [ItemId],[OrderId],[Price],[CreateTime] FROM [OrderDetail]  WHERE   OrderId =1
@ConditionalOrderId0:1

**Comment by sunkaixuan** [comment]
性能是一样我这样只考虑到我代码的可维护度
