### ISSUE TITLE
连接oracle错误

### ISSUE THREAD

**Issue by hb-happy** [sunkaixuan/SqlSugar#578]
public class SqlSugarHelper
    {
        public static SqlSugarClient DB { get; set; }
        public SqlSugarHelper()
        {
 
                DB=new SqlSugarClient(new ConnectionConfig()
                {
                    ConnectionString = @"xxxxx",//必填, 数据库连接字符串
                    DbType = DbType.Oracle,        　//必填, 数据库类型
                    IsAutoCloseConnection = true,      //默认false, 时候知道关闭数据库连接, 设置为true无需使用using或者Close操作
                    InitKeyType = InitKeyType.SystemTable    //默认SystemTable, 字段信息读取, 如：该属性是不是主键，是不是标识列等等信息
                });
             
         }
    }
int updateNo = SqlSugarHelper.DB.Updateable<CimreSourceTest>(cimreSource).ExecuteCommand(); 

English Message : Connection open error . “OracleInternal.MTS.PSPEManager”的类型初始值设定项引发异常。
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：“OracleInternal.MTS.PSPEManager”的类型初始值设定项引发异常。.

**Comment by yilei63** [comment]
已经明确高速你连接字符串错误

**Comment by PanGuoDong** [comment]
连接字符串正确的情况下，可查看系统环境变量是否有问题。我通过删除tns_home环境变量解决
