### ISSUE TITLE
code first 建立字段时 IsNullable 问题

### ISSUE THREAD

**Issue by bute001** [sunkaixuan/SqlSugar#580]
对于某些字段能否根据字段类型来描述是否能为空
如 int? datetime? 默认为 IsNullable = true

或者能否增加属性控制全部的字段默认为 IsNullable = true而不是IsNullable = false

**Comment by TwSoft** [comment]
不知道作者怎么想的，默认规则确实是存在问题，虽然自己可以全局去配置。
感觉现在作者响应很不及时了。

**Comment by bute001** [comment]
> 不知道作者怎么想的，默认规则确实是存在问题，虽然自己可以全局去配置。
> 感觉现在作者响应很不及时了。

请问全局配置如何实现.
