### ISSUE TITLE
使用多库时，除了第一个配置其它的aop日志没有显示

### ISSUE THREAD

**Issue by h619633675** [sunkaixuan/SqlSugar#582]
当我尝试使用多库后，aop 日志并没有完全记录并打印出我想要的 sql。它只打印出使用第一个连接配置时的 sql， 第二个就一点都没有打印

               List<ConnectionConfig> list = new List<ConnectionConfig>()
               {
                    new SqlSugar.ConnectionConfig()
                    {
                        ConfigId = BaseDBConfig.MysqlConfigIdDefault,
                        ConnectionString = BaseDBConfig.MysqlDefualtConnection,
                        DbType = SqlSugar.DbType.MySql,
                        IsAutoCloseConnection = true,
                        InitKeyType = SqlSugar.InitKeyType.SystemTable
                    },
                    new SqlSugar.ConnectionConfig()
                    {
                        ConfigId = BaseDBConfig.MysqlConfigIdTemp,
                        ConnectionString = BaseDBConfig.MysqlDefualtConnection,
                        DbType = SqlSugar.DbType.MySql,
                        IsAutoCloseConnection = true,
                        InitKeyType = SqlSugar.InitKeyType.SystemTable
                    },
               };
               _sqlSugarClient = new SqlSugar.SqlSugarClient(list);

               _sqlSugarClient.Aop.OnLogExecuting = (sql, pars) =>
               {
                   Console.WriteLine(sql + "\r\n" + _sqlSugarClient.Utilities.SerializeObject(pars.ToDictionary(it => it.ParameterName, it => it.Value)));
                   Console.WriteLine();
               };

这是另外一段切换库的,因为另外一个是非固定个数库名所以会有修改连接字符串的操作
                if (b != null)
                {
                    _sqlSugarClient.ChangeDatabase(BaseDBConfig.MysqlConfigIdTemp);
                    _sqlSugarClient.CurrentConnectionConfig.ConnectionString = string.Format(BaseDBConfig.MysqlTempConnection, b.B2);
                }

**Comment by sunkaixuan** [comment]
CHANGE DATABASEf需要客外赋值或者在  ConnectionConfig 里面设置AOP

**Comment by hjkcmb** [comment]
在 ConnectionConfig 里面设置AOP好像无效，还是只有第一个库有日志。
必须每次CHANGE DATABASE后再次赋值，是BUG还是就是这样设计的？
