### ISSUE TITLE
close() 和 dispose() 执行后 仍可以继续数据库操作 是正常释放了吗？

### ISSUE THREAD

**Issue by timzhangliang** [sunkaixuan/SqlSugar#584]

**Comment by sunkaixuan** [comment]
if (base._DbConnection == null)
                {
                    try
                    {
                        base._DbConnection = new SqlConnection(base.Context.CurrentConnectionConfig.ConnectionString);
                    }
                    catch (Exception ex)
                    {
                        Check.Exception(true, ErrorMessage.ConnnectionOpen, ex.Message);
                    }
                } 只是重新NEW了 dispose后你在用
