### ISSUE TITLE
sqlite 密码链接字符串

### ISSUE THREAD

**Issue by g376861363** [sunkaixuan/SqlSugar#588]
```
Db = new SqlSugarClient(new ConnectionConfig()
            {                
                ConnectionString = @"Data Source=G:\test.db;Version=3;Password=xxxxx;",
                DbType = DbType.Sqlite,
                InitKeyType = InitKeyType.Attribute,
                IsAutoCloseConnection = true,
            });
```
SqlSugar.SqlSugarException:“English Message : Connection open error . Keyword not supported: 'version'.
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Keyword not supported: 'version'..”

**Comment by qxa792** [comment]
.netstandard版本的sqlite不支持关键词Version和Password
