### ISSUE TITLE
你好，最近在一个系统，前期功能不多时候，没有什么问题，后期功能多了，频繁出现一个错误。

### ISSUE THREAD

**Issue by haibozhou1011** [sunkaixuan/SqlSugar#59]
你好，最近在做一个系统，前期功能不多时候，没有什么问题，后期功能多了，频繁出现一个错误。

“There is already an open DataReader associated with this Connection which must be closed first.”

[用的是MySql，后来我Google一下，说是MySql一个bug（[https://www.bbsmax.com/A/B0zqYggnzv/](https://www.bbsmax.com/A/B0zqYggnzv/)），说MySql同一时刻只允许有一个连接被打开读取数据。

请问你有遇到过类似的问题？

**Comment by haibozhou1011** [comment]
不是用的主动关闭链接，而是采用的自动关闭！

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Doc/8/1155

**Comment by haibozhou1011** [comment]
这个我也看了，关键是，我封装了一个Repository 模式，用Autofac依赖注入。没有 [http://www.codeisbug.com/Doc/8/1155](http://www.codeisbug.com/Doc/8/1155) 那么简单。
