### ISSUE TITLE
mysql对tinyint的取值问题

### ISSUE THREAD

**Issue by JohnnyWoong** [sunkaixuan/SqlSugar#595]
数据库中的值无论为0还是1,取出来的值都是0
修改数据类型为int则能正常取值
![image](https://user-images.githubusercontent.com/5661094/70795544-0361b600-1ddb-11ea-9107-79ccef1c4a7b.png)

**Comment by stonezhu870** [comment]
连接字符串中加入TreatTinyAsBoolean=false;
