### ISSUE TITLE
.net core 控制台程序，数据库链接超时. Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool

### ISSUE THREAD

**Issue by sxsean1** [sunkaixuan/SqlSugar#596]
.net core 控制台程序，开启几百个线程处理，在linux环境下，报这个错误。如果是开启几个线程，就正常。

报的错误内容
Connection open error . Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached..

**Comment by sxsean1** [comment]
同样程序，在windows 运行时没问题的，只有在linux 下

**Comment by sunkaixuan** [comment]
我记得linux需要有什么补丁的 对数据库版本也有要求

**Comment by sxsean1** [comment]
数据库版本 sqlserver2016  ，如果数据库是sqlserver2008确实需要打补丁

**Comment by fzh5201413** [comment]
mysql5.7 需要打什么补丁呢
