### ISSUE TITLE
.netcore3.1

### ISSUE THREAD

**Issue by zhenhunfan** [sunkaixuan/SqlSugar#600]
我在.netcore3.1里调用方法时，报错：
SqlSugar.SqlSugarException:“English Message : Entity mapping error.Bad IL format.
Chinese Message : 实体与表映射出错。Bad IL format.”

**Comment by wangsidong177** [comment]
升级到.netcore3.1，使用的是sqlserver，发现数据库nvarchar映射到实体类string时报错，求解决方案。
报错实体类映射失败，int映射时不会出现问题

**Comment by xushenchen** [comment]
表示：升级到最新版本，使用.NET CORE 3.1 原有的库和表，现在都很正常。
