### ISSUE TITLE
Saveable().ExecuteReturnList() 批量更新或插入返回的列表没有主键

### ISSUE THREAD

**Issue by iam993** [sunkaixuan/SqlSugar#601]
如题，Saveable(Entity).ExecuteReturnEntity() 是正常的，返回的实体里有带自增主键 Id，而 Saveable(List).ExecuteReturnList()，List中不带主键Id的实体，返回的所有实体都不带自增主键 Id。

**Comment by sunkaixuan** [comment]
技术上实现不了
