### ISSUE TITLE
多表查询unknown column

### ISSUE THREAD

**Issue by derily** [sunkaixuan/SqlSugar#604]
`FROM A JOIN B on A.code=B.code JOIN C on B.id=c.id
Queryable<A,B,C>((a,b,c)=>new object[]{JoinType.Left,a.code==c.code,JoinType.Left,b.id==c.id})`

**Unknown column 'c.code' in 'on clause'**

**Comment by sunkaixuan** [comment]
不要混着一起写，SUGAR就是查询一个LIST集合，你把集合用变量接收在和现有变量用LINQ
