### ISSUE TITLE
参数化查询的时候类型转换

### ISSUE THREAD

**Issue by 1060877180** [sunkaixuan/SqlSugar#608]
使用参数化参数的时候，int类型生成的SQL会增加单引号，这样会损失性能

**Comment by sunkaixuan** [comment]
请给具体代码 ，暂时没发现你说的情况

**Comment by 1060877180** [comment]
晚一些，我这边本地测试正常的，上线才有问题。重现要测试一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sunkaixuan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上6:01
收件人:&nbsp;"sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com&gt;;
抄送:&nbsp;"李江"<1060877180@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sunkaixuan/SqlSugar] 参数化查询的时候类型转换 (#608)




请给具体代码 ，暂时没发现你说的情况

**Comment by 1060877180** [comment]
代码
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; List<SugarParameter&gt; parameters = new List<SugarParameter&gt;() {


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; new SugarParameter("@id",1,System.Data.DbType.Int32),




&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; };


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var s = myStudyAppDBRepository.Factory.Ado.SqlQuery<AccountEntity&gt;("select * from account where id=@id", parameters);





SQL:&nbsp; &nbsp; &nbsp;select * from account where id='1'
最终拼出来的SQL没有按照指定参数类型拼接




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sunkaixuan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 晚上6:01
收件人:&nbsp;"sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com&gt;;
抄送:&nbsp;"李江"<1060877180@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sunkaixuan/SqlSugar] 参数化查询的时候类型转换 (#608)




请给具体代码 ，暂时没发现你说的情况
