### ISSUE TITLE
SqlSugar.SqlSugarException:“English Message : Entity mapping error.Bad IL format. Chinese Message : 实体与表映射出错。Bad IL format.”

### ISSUE THREAD

**Issue by shupming** [sunkaixuan/SqlSugar#609]
我用单元测试 .net Code 3.0  会报实体映射失败   SqlSugar.SqlSugarException:“English Message : Entity mapping error.Bad IL format  ,然后我降到2.0  就不会了

**Comment by sunkaixuan** [comment]
SQLSUGAR版本低了
