### ISSUE TITLE
更新数据的时候异常

### ISSUE THREAD

**Issue by 1060877180** [sunkaixuan/SqlSugar#612]
我这边这个异常 序列包含一个以上的匹配元素    
 在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)   
 在 SqlSugar.UpdateableProvider`1.Init()     在 SqlSugar.SqlSugarProvider.CreateUpdateable[T](T[] UpdateObjs) 
 在 SqlSugar.SqlSugarProvider.Updateable[T](T[] UpdateObjs)
观察 xWGJMtRepository.Factory.Context.MappingTables 的值[{"EntityName":"ApiRequestRecordEntity","DbTableName":"ApiRequestRecord","DbShortTaleName":null},
{"EntityName":"ApiRequestDataEntity","DbTableName":"ApiRequestData","DbShortTaleName":null},
{"EntityName":"ApiRequestDataEntity","DbTableName":"ApiRequestData","DbShortTaleName":null}]

里面的ApiRequestDataEntity 居然重复添加了

然后他源码这里用的是UpdateableProvider.init 方法中使用 this.Context.MappingTables.SingleOrDefault 导致抛出异常，这是BUG吗

**Comment by sunkaixuan** [comment]
写个可以重现的控置台的DEMO发我邮箱

**Comment by zz110** [comment]
这个问题很频繁呀

**Comment by zz110** [comment]
System.InvalidOperationException: 序列包含一个以上的匹配元素
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 SqlSugar.UpdateableProvider`1.Init()
   在 SqlSugar.SqlSugarProvider.CreateUpdateable[T](T[] UpdateObjs)
   在 SqlSugar.SqlSugarProvider.Updateable[T](T[] UpdateObjs)
   在 SqlSugar.SqlSugarProvider.Updateable[T](T UpdateObj)
   在 SqlSugar.SqlSugarProvider.Updateable[T](Object updateDynamicObject)
   在 System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   在 SqlSugar.SqlSugarClient.Updateable[T](Object updateDynamicObject)
   在 JiYun.ClientDbContext.Service.Service`2.modify(TParams input, Expression`1 expression, Expression`1 columns)
