### ISSUE TITLE
为什么Count()会生成两次查询语句呢，能修改下吗？sql server2008

### ISSUE THREAD

**Issue by QishengRan** [sunkaixuan/SqlSugar#617]
SELECT COUNT(1) FROM (SELECT [Id],[Nickname],[CreateDate] FROM [Members]  WHERE ( [Id] > @Id0 )) CountTable

**Comment by sunkaixuan** [comment]
在不影响性能的情况下我生成SQL会考虑到一处多用，你这语句在MSSQL中对性能没有影响
