### ISSUE TITLE
使用sqlSugarCore5.0.0.11在linux环境下自动创建sqlite数据库报错问题:提示路径为空

### ISSUE THREAD

**Issue by tbqtbq100** [sunkaixuan/SqlSugar#619]
![QQ图片20200106163034](https://user-images.githubusercontent.com/49091555/71805728-e2bb1200-30a1-11ea-9a0d-938af4a537ca.png)
发现在sqlsugar SqliteDbMaintenance.cs 文件CreateDatabase方法中创建sqlite库文件路径只支持windows环境路径匹配

**Comment by Nickeysoft** [comment]
在Mac环境下也出现错误，看了下源码，应该是解析路径的时候只考虑了Windows环境
