### ISSUE TITLE
如何保存byte[]数组到数据库，不定长

### ISSUE THREAD

**Issue by rote667668** [sunkaixuan/SqlSugar#63]
新手用SqlSugar，请帮助我谢谢！

定义了个数组
[SugarColumn(IsNullable = true)]
        public byte[] Histo { get; set; }
直接给他赋值了别的数组 Histo = new byte[10]{1,2.3,4,5,6,7,8,9,10}
然后执行sqlClient.Insertable<TestResult>(dbTestRst).ExecuteCommandAsync();发现Histo这个数据列并没有数据是空的，我应该如何操作数组写入数据库？

**Comment by rote667668** [comment]
用的是SQLite

**Comment by lpyedge** [comment]
base64编码成字符串存到数据库.取得以后在base64解码

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rote667668** [comment]
@lpyedge 我每条数据10K的byte，每条都要这样转，岂不是很影响效率

**Comment by lpyedge** [comment]
效率？你每秒读写能超过多少次？如果读写次数不高的话这点效率损失基本可以忽略.要看使用场景的.否则你就要用缓存来读写了.话说回来，都用sqlite了基本可以肯定你那边不会有效率问题的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rote667668** [comment]
@lpyedge 说的很有道理  我先这么试试，以后不行了再研究，谢谢你
