### ISSUE TITLE
Queryable的where中用位运算作为条件，mysql 使用的是And，应该用&

### ISSUE THREAD

**Issue by jkdeadwolf** [sunkaixuan/SqlSugar#634]
var sql=dbOper.Queryable<Test>().Where(it => (it.NotifyMode & 2) == 2).ToSql()
输出的sql语句是 ( `NotifyMode` AND 2 ) =2 )   ，这里And是逻辑运算，不是位运算

**Comment by liuliyang123** [comment]
C#中的位运算是否需要转化成数据库的位运算。可以修改二元运算操作 中修改相应的代码

**Comment by jkdeadwolf** [comment]
Updateable().SetColumns 也有同样问题，就是需要把C#的位运算转换为数据库的位运算，目前看转换出的SQL是数据库的逻辑运算。  该怎么处理。
