### ISSUE TITLE
Select中使用SqlFunc.DateValue的问题

### ISSUE THREAD

**Issue by liyifei21** [sunkaixuan/SqlSugar#648]
实体如下
public class Student:Person
    {
        [JsonIgnore]
        public int StudentId { get; set; }

        public int SchoolId { get; set; }
        public DateTime CreateTime { get; set; }

        public DateTime? Birth { get; set; }
        public int? TestId { get; set; }

    }

DateType dateType = DateType.Hour;

使用查询Select如下
var sql =Db.Queryable<Student>().Select(s=>SqlFunc.DateValue(s.CreateTime, dateType)).ToSql();
生成的sql如下：
SELECT  **4(`CreateTime`)**  FROM `Student`  

使用GroupBy如下：
sql = Db.Queryable<Student>().GroupBy(s => SqlFunc.DateValue(s.CreateTime, dateType)).ToSql();
生成sql如下：
SELECT `StudentId`,`SchoolId`,`CreateTime`,`Birth`,`TestId`,`Name`,`Age` FROM `Student` GROUP BY  Hour(`CreateTime`)  

Select中生成的sql明显是不对的

**Comment by HanaForward** [comment]
恕我直言，没看出来有啥问题啊
