### ISSUE TITLE
对于PostgreSQL的支持，未区分大小写

### ISSUE THREAD

**Issue by peach5460** [sunkaixuan/SqlSugar#649]
根据PostgreSQL的描述，当表名或者字段名中存在大小写时，PostgreSQL是严格区分大小写的。
而我用SoEasyPlatform生成的代码，执行时SQL语句内的字段和表名全部都是小写，导致执行时抛出异常，找不到对应的表和字段。

我找了很久，似乎没发现有属性设置开关来设置是否（不要将大写表名字段名转为小写）。
请问，作者是否有解决方案

**Comment by peach5460** [comment]
我查到代码里的逻辑，感觉不对
代码里面，先将表名和字段名tolower（），然后在结果的左右两边加引号

实际上按照规则，如果加引号，那么里面的内容PostgreSQL数据库是不会将它转为小写的。
所以你这里的逻辑应该是，要么两端加引号就不要tolower（），如果tolower（）就不要加引号

**Comment by sunkaixuan** [comment]
最新版本支持2种模式，在configconnection里面设置
