### ISSUE TITLE
Code First Sqlite:Db.CodeFirst.InitTables

### ISSUE THREAD

**Issue by yufeiyunsui** [sunkaixuan/SqlSugar#652]
SQLite Error 1: 'AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY'.

`    [SugarColumn(IsNullable = false, IsPrimaryKey = true, IsIdentity = true)]
        public long Id { get; set; }`

去掉  IsIdentity = true 即可生成表,否则报错.

**Comment by zqstdy** [comment]
只支持int类型吧

**Comment by sunkaixuan** [comment]
错误是驱动抛出来的按提示来就好
