### ISSUE TITLE
Mysql 8.0.15  连接字符串不支持 “port” 关键字问题？？

### ISSUE THREAD

**Issue by chenzhenghong** [sunkaixuan/SqlSugar#655]
ConnectionString = "server=localhost;user id=xxx;password=xxx;**port=3308**;persistsecurityinfo=True;database=xxx",

发的异常:“SqlSugar.SqlSugarException”(位于 SqlSugar.dll 中)
“SqlSugar.SqlSugarException”类型的异常在 SqlSugar.dll 中发生，但未在用户代码中进行处理
English Message : Connection open error . Keyword not supported: 'port'.

**Comment by sunkaixuan** [comment]
驱动更新到最新

**Comment by akimusume** [comment]
是不是DbType写错了，官网上复制下来的默认是SqlServer

**Comment by dorisoy** [comment]
这是一个很老的问题了，换组件发自我的华为手机-------- 原始邮件 --------发件人： akibayashi <notifications@github.com>日期： 2021年1月8日周五 11:12收件人： donet5/SqlSugar <SqlSugar@noreply.github.com>抄送： mschen_ <czhcom@163.com>, Author <author@noreply.github.com>主    题： Re: [donet5/SqlSugar] Mysql 8.0.15  连接字符串不支持 “port” 关键字问题？？ (#655)

是不是DbType写错了，官网上复制下来的默认是SqlServer
