### ISSUE TITLE
需要引用ManagedDataAccess.dll

### ISSUE THREAD

**Issue by Jean711** [sunkaixuan/SqlSugar#666]
项目已经引入ManagedDataAccess.dll，版本为4.121.2.0，是从一个成功连接的项目拷贝过来的。
在新的项目中连接数据库时就报错。图片如下。
![am8_20200330143212799](https://user-images.githubusercontent.com/6488728/77882373-72342380-7293-11ea-9a2e-10f27add0f7c.jpg)

**Comment by wangx036** [comment]
也遇到这个问题，已解决，各位参考下。
整个解决方案下，所有引用了sqlsugar的项目，都引用Oracle.ManagedDataAccess。
我是这样解决的
