### ISSUE TITLE
关于语言表联查耗时长？（.net sqlsugar 精英学习群）

### ISSUE THREAD

**Issue by a83302493** [sunkaixuan/SqlSugar#667]
查询语句为
 var  data= Db.Queryable<Sys_Language, Sys_LanguageType, Sys_LanguageParams>((s1,s2,s3)=>new object[]
            {
                JoinType.Left, s2.ID==s1.LanguageTypeID,
                JoinType.Left, s3.ID==s1.LanguageParamsID

            }).WhereIF(typename.Count>0, (s1, s2,s3) => typename.Contains(s2.NameCode)).Select((s1, s2,s3) => new Sys_LanguageAndType { Sys_Language = s1, 
                Sys_LanguageType = s2 ,Sys_LanguageParams=s3}).ToList();
            return data;
[languagedata.zip](https://github.com/sunkaixuan/SqlSugar/files/4406564/languagedata.zip)

**Comment by sunkaixuan** [comment]
列名重复
