### ISSUE TITLE
请问，ado.SqlQuery<t>(sql,new{}) 怎么支持 in @para 这种语法

### ISSUE THREAD

**Issue by neozhu** [sunkaixuan/SqlSugar#672]
Dapper dot net:
string[] names = new string[] {"ruby","rails","scruffy","rubyonrails"};
var tags = dataContext.Query<Tags>(@"
select * from Tags 
where Name in @names
order by Count desc", new {names});

SqlSugar 好像还不支持，能否考虑加一下

**Comment by sunkaixuan** [comment]
ado.SqlQuery<t>(sql).addparameters(new{})

**Comment by sunkaixuan** [comment]
string[] names = new string[] {"ruby","rails","scruffy","rubyonrails"};
var tags = dataContext.Query(@"
select * from Tags
where Name in (@NAMEs)
 
这样写参数传个数组 要用()包里起来
