### ISSUE TITLE
更新匿名对象 如果字段类型为bool时失败

### ISSUE THREAD

**Issue by cd-zhang2020** [sunkaixuan/SqlSugar#673]
使用文档里面的方法
var t13 = db.Updateable<Student>(new { IsDeleted=true }).ExecuteCommandAsync();
更新时，生成的sql语句里面IsDeleted始终等于False，数据库为sqlserver

**Comment by sunkaixuan** [comment]
语法不对吧

**Comment by cd-zhang2020** [comment]
![image](https://user-images.githubusercontent.com/39512639/78654179-c2942c80-78f6-11ea-90b0-97429876bc59.png)
语法应该没错啊

**Comment by cd-zhang2020** [comment]
谢谢，知道什么原因了，属性上不能加  [JsonIgnore]
