### ISSUE TITLE
建议增加缓存KEY自定义扩展

### ISSUE THREAD

**Issue by JonneyDong** [sunkaixuan/SqlSugar#680]
希望作者能ISugarQueryable 增加 WithCacheKey 函数. 并且 可以自主自定义扩展 CacheKeyBuider 相关功能. 可以让使用者 自主自定义每个操作指定缓存 KEY操作, 在分布式, 多系统协作时更好, 因为内置的缓存KEY比较随机

**Comment by sundayisblue** [comment]
不是有接口么，自己实现
