### ISSUE TITLE
Oracle 自增使用异步方法插入返回无法返回自动ID

### ISSUE THREAD

**Issue by wangq2008** [sunkaixuan/SqlSugar#686]
在实体的ID列已经设置了     
 [SugarColumn(IsPrimaryKey = true, OracleSequenceName = "ACCOUNT_SEQUENCE")]
在插入的时候使用同步方法ExecuteReturnIdentity()能返回正确的自增ID，但使用异步方法ExecuteReturnIdentityAsync(),却返回是0，值不正确。版本为sqlSugarCore 5.0.0.13，情况与https://github.com/sunkaixuan/SqlSugar/issues/493 一样。这个问题没有修复就关闭了。再次提出来，引起重视

**Comment by sunkaixuan** [comment]
新测是可以的，你可以在我GITHUB DEMO上的插入改成异步测试一下，具体什么原因你没获取可能哪个细节不一样

**Comment by sunkaixuan** [comment]
还有一点批量插入是不支持返回 ID的，目前技术实现不了

**Comment by wangq2008** [comment]
刚从Github上下载的，insert Demo修改为异步方法返回ID，里面返回就是0，同步方法就返回ID。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sunkaixuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午4:49
收件人:&nbsp;"sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com&gt;;
抄送:&nbsp;"用户昵称王强"<365508785@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sunkaixuan/SqlSugar] Oracle 自增使用异步方法插入返回无法返回自动ID (#686)





 
新测是可以的，你可以在我GITHUB DEMO上的插入改成异步测试一下，具体什么原因你没获取可能哪个细节不一样
