### ISSUE TITLE
联表查询的byte[]类型的字段报错

### ISSUE THREAD

**Issue by AelousDing** [sunkaixuan/SqlSugar#690]
我使用3个表做查询，其中有个表里面有个字节数组的列，我使用byte[]类型定义其对应实体中的属性。查询之后出错。我查看了输出的sql，select里面没有对应的数据列名称，然后报错，如下图。
![5b765ef7c9c62756a2878b65b1cc4bd](https://user-images.githubusercontent.com/10691040/79836235-7828aa80-83e2-11ea-8dac-b7b02f01c8f1.png)

![ff15dc130fdfcaa536b4bc36b4a2e15](https://user-images.githubusercontent.com/10691040/79836112-52030a80-83e2-11ea-856a-0fed6df4dca1.png)

**Comment by vxueshan** [comment]
这个问题后来怎么样了？

**Comment by fengjuanchensha** [comment]
我后来就没有使用联表查询，分别查询，在程序中处理的
