### ISSUE TITLE
数据库类型映射实体类型，未考虑tinyint(1)为bool

### ISSUE THREAD

**Issue by jol5** [sunkaixuan/SqlSugar#692]
![image](https://user-images.githubusercontent.com/28615922/79962812-1ee07a00-84bb-11ea-88c0-c1ead3c48c86.png)
问题：
1.生成实体会导致tinyint(1) 为byte，而不是bool

**Comment by 840900649** [comment]
![TIM图片20200428215055](https://user-images.githubusercontent.com/23233480/80495337-5f983180-899a-11ea-8971-b66f28ae412f.png)

在postgresql中，因为实体是bool类型，但是数据库实际是 bit1] 所以查询会出现类型错误。

**Comment by 840900649** [comment]
不过问题找到了，是我从mysql转换数据到postgresql时，把bit 转换成了varchar

**Comment by 840900649** [comment]
老大，建议生成初始数据时，不要全加入必填。好难受，初始化时候字段时notnull 一条数据都录不进去。被迫每次更新都需要修改源代码。。。。

**Comment by 840900649** [comment]
类：/Infrastructure/SqlSugarAccessory  CopyEntityInfo  函数 增加 大概第199行
 说明：解决可为空类型
 源代码：
     columns.Add(item);
 新代码：
 if (item.PropertyInfo.PropertyType.IsGenericType && item.PropertyInfo.PropertyType.GetGenericTypeDefinition() == typeof(Nullable<>))
                    {
                        item.IsNullable = true;
                    }
else if (item.PropertyInfo.Name!="Id"&&item.PropertyInfo.PropertyType.Name.IndexOf("string",StringComparison.OrdinalIgnoreCase)>-1)
                    {
                        item.IsNullable = true;
                    }

**Comment by cnkker** [comment]
我也有这个问题
