### ISSUE TITLE
更新实体时，设置了忽略Null值字段，实体中的一个可空枚举属性，还是会被更新成0

### ISSUE THREAD

**Issue by sclynton** [sunkaixuan/SqlSugar#698]
如题，这个大家有遇到过吗？比如Student实体有一个字段StudentStatus? Status;我在更新时这个字段设置了Null ,因为我不想更新这个字段，更新时设置.IgnoreColumns(true)，但最终还是会将表里的Status设置为0.       抓头！！！我用Mysql数据库。最近更新了SqlSugar的版本还是没有解决。

**Comment by zonecolour** [comment]
我也发现了这个问题, 我一个实体中有一个字段是 IsJson的自定义实体类字段, 我设置了IgnoreColumns(ignoreAllNullColumns:true), 但是更新的时候, 这个自定义的实体字段的值就变成了 "{null}"字符串, 被更新了

**Comment by zonecolour** [comment]
看了源码，UpdateableProvider.cs 下的SetUpdateItemByEntity方法，原文是
 if (columnInfo.PropertyType.IsEnum())
                {
                        columnInfo.Value = Convert.ToInt64(columnInfo.Value);
                }
                if (column.IsJson)
                {
                    columnInfo.Value = this.Context.Utilities.SerializeObject(columnInfo.Value);
                }
这里我打了个补丁，就是判断null值而已，不知道会不会引发其他问题：
 if (columnInfo.PropertyType.IsEnum())
                {
                    if (columnInfo.Value == null) {
                        columnInfo.Value = null;
                    }
                    else {
                        columnInfo.Value = Convert.ToInt64(columnInfo.Value);
                    }
                }
                if (column.IsJson)
                {
                    columnInfo.Value = columnInfo.Value == null ? null : this.Context.Utilities.SerializeObject(columnInfo.Value);
                }
