### ISSUE TITLE
union all  异常

### ISSUE THREAD

**Issue by yeibl** [sunkaixuan/SqlSugar#700]
union all  ,多个ISugarQueryable union  最后一个定义的 ISugarQueryable  会覆盖前面的ISugarQueryable  
 比如

` 
 var changeQuery = _db.Queryable<t_course_change_batch, t_course_batch_item, t_course_change>((a, b, c) => new object[] {
                JoinType.Inner,a.id==b.batch_id&&a.deletemark==0,
               JoinType.Inner,b.exchange_id==c.id&&b.course_change_type==CourseChangeType.change
            }).Select((a, b, c) => new BatchInfoView
            {
                batch_id = a.id,
                apply_reason = a.apply_reason,
                create_by = a.create_by,
                create_time = a.create_time,
                course_change_type = b.course_change_type,
                state = c.state,
                batch_item_id = b.id,
                exchange_id = c.id,
                targe_teacher_id = c.change_teacher_id
            }).MergeTable().Select(s => s);

            var insteadQuery = _db.Queryable<t_course_change_batch, t_course_batch_item, t_course_instead>((e, f, g) => new object[] {
                JoinType.Inner,e.id==f.batch_id&&e.deletemark==0,
                JoinType.Inner,f.exchange_id==g.id&&f.course_change_type==CourseChangeType.instead
            }).Select((e, f, g) => new BatchInfoView
            {
                batch_id = e.id,
                apply_reason = e.apply_reason,
                create_by = e.create_by,
                create_time = e.create_time,
                course_change_type = f.course_change_type,
                state = g.state,
                batch_item_id = f.id,
                exchange_id = g.id,
                targe_teacher_id = g.instead_teacher_id
            }).MergeTable().Select(s=>s);

            var noProcessdureQuery = _db.Queryable<t_course_change_batch, t_course_batch_item>((j, k) => new object[] {
                JoinType.Inner,j.id==k.batch_id&&j.deletemark==0&&k.course_change_type==  CourseChangeType.none
            }).Select((j, k) => new BatchInfoView
            {
                batch_id = j.id,
                apply_reason = j.apply_reason,
                create_by = j.create_by,
                create_time = j.create_time,
                course_change_type = k.course_change_type,
                state = CourseChangeState.none,
                batch_item_id = k.id,
                exchange_id = 0,
            }).MergeTable().Select(s => s);

            var result = _db.UnionAll( changeQuery, insteadQuery, noProcessdureQuery).Where(whereExpression);
`
出来的sql是这样 
`
SELECT
	`batch_id`
FROM
	(
		SELECT
			*
		FROM
			(
				SELECT
					`j`.`id` AS `batch_id`,
					`j`.`apply_reason` AS `apply_reason`,
					`j`.`create_by` AS `create_by`,
					`j`.`create_time` AS `create_time`,
					`k`.`course_change_type` AS `course_change_type`,
					@constant2 AS `state`,
					`k`.`id` AS `batch_item_id`,
					@constant3 AS `exchange_id`
				FROM
					`t_course_change_batch` j
				INNER JOIN `t_course_batch_item` k ON (
					(
						(`j`.`id` = `k`.`batch_id`)
						AND (
							`j`.`deletemark` = @deletemark0Union1
						)
					)
					AND (
						`k`.`course_change_type` = @course_change_type1Union1
					)
				)
			) MergeTable
		UNION
			SELECT
				*
			FROM
				(
					SELECT
						`j`.`id` AS `batch_id`,
						`j`.`apply_reason` AS `apply_reason`,
						`j`.`create_by` AS `create_by`,
						`j`.`create_time` AS `create_time`,
						`k`.`course_change_type` AS `course_change_type`,
						@constant2 AS `state`,
						`k`.`id` AS `batch_item_id`,
						@constant3 AS `exchange_id`
					FROM
						`t_course_change_batch` j
					INNER JOIN `t_course_batch_item` k ON (
						(
							(`j`.`id` = `k`.`batch_id`)
							AND (
								`j`.`deletemark` = @deletemark0Union2
							)
						)
						AND (
							`k`.`course_change_type` = @course_change_type1Union2
						)
					)
				) MergeTable
			UNION
				SELECT
					*
				FROM
					(
						SELECT
							`j`.`id` AS `batch_id`,
							`j`.`apply_reason` AS `apply_reason`,
							`j`.`create_by` AS `create_by`,
							`j`.`create_time` AS `create_time`,
							`k`.`course_change_type` AS `course_change_type`,
							@constant2Union3 AS `state`,
							`k`.`id` AS `batch_item_id`,
							@constant3Union3 AS `exchange_id`
						FROM
							`t_course_change_batch` j
						INNER JOIN `t_course_batch_item` k ON (
							(
								(`j`.`id` = `k`.`batch_id`)
								AND (
									`j`.`deletemark` = @deletemark0Union3
								)
							)
							AND (
								`k`.`course_change_type` = @course_change_type1Union3
							)
						)
					) MergeTable
	) unionTable
WHERE
	(`state` = @state0)
`

**Comment by liuliyang123** [comment]
.MergeTable().Select(s => s); 这一段基本上是多余的
