### ISSUE TITLE
Sum(@fields).ObjToDecimal()  转换类型后值一直为0

### ISSUE THREAD

**Issue by qingapp** [sunkaixuan/SqlSugar#704]
Sum(@fields).ObjToDecimal()  转换类型后值一直为0，Sum（）返回object值是有的，换过多个版本试了下都这样，不知道是不是ObjToDecimal（）转换有bug？

**Comment by sunkaixuan** [comment]
应该是有数位数转decimal出错了，你以把具体的拿出来给我看看

**Comment by liuliyang123** [comment]
Decimal double 等值 在运算之后特别容易溢出（小数点后N多位）需要round 函数转一下就有数了。
