### ISSUE TITLE
oracle数据库批量更新的场景出错

### ISSUE THREAD

**Issue by stonezhu870** [sunkaixuan/SqlSugar#706]
数据库Oracle
SqlSugar版本：
![image](https://user-images.githubusercontent.com/3832691/80916544-f6466300-8d8b-11ea-8b96-7a4f352d2934.png)

场景：
数据库表msg_queue的主键使用的raw(16)，使用sqlsugar批量更新对象中的某个列。
程序中Id使用的类型是：
public byte[] Id { get; set; }

更新时使用：
db.Updateable(pageList).UpdateColumns(it => new { it.Status, it.ModifyTime }).ExecuteCommand();

报错信息为：
Begin
UPDATE "MSG_QUEUE" SET "STATUS"=N'2',"MODIFY_TIME"=to_date('2020-05-03 22:08:19', 'YYYY-MM-DD HH24:MI:SS')  WHERE  "ID"=0x4E5D5D9CD42348F7A4529B9A168244F6;
UPDATE "MSG_QUEUE" SET "STATUS"=N'2',"MODIFY_TIME"=to_date('2020-05-03 22:08:19', 'YYYY-MM-DD HH24:MI:SS')  WHERE  "ID"=0x4E6FFBF5839746859BBDFD283BF34691;
End;

ORA-06550: 第 2 行, 第 126 列:
PL/SQL: ORA-00972: 标识符过长
ORA-06550: 第 2 行, 第 1 列:
PL/SQL: SQL Statement ignored

请问是不是在批量更新的情况下，对raw类型支持得不是太好？

**Comment by weile0769** [comment]
还真有人碰到我一样的问题，我都等了1年了，这个BUG哈

**Comment by stonezhu870** [comment]
> 还真有人碰到我一样的问题，我都等了1年了，这个BUG哈

现在我先改成了每次更新一条的方式。。。

**Comment by liuliyang123** [comment]
看来用hextoraw 将0x4E6FFBF5839746859BBDFD283BF34691 转成raw类型 也许可以解决。
