### ISSUE TITLE
4.x版本现在nuget引用了.net 4.5的Newtonsoft.Json导致无法在.net 4.0下使用

### ISSUE THREAD

**Issue by kll8926** [sunkaixuan/SqlSugar#717]
因为程序要兼容xp，.net 版本只能到4.0，原来4.x版本sqlsugar是可以直接引用后生成启动的，现在引用了.net 4.5的Newtonsoft.Json导致无法在.net 4.0生成了

**Comment by sunkaixuan** [comment]
4.X版本一直是用的.NET 4.0的JSON.NET
