### ISSUE TITLE
Select(x=>new A())时，如果A里面有一个B类型的属性，则查询会出错

### ISSUE THREAD

**Issue by DavideYang125** [sunkaixuan/SqlSugar#725]
示例代码如下：
    public class TestA
    {
        public string title { get; set; }
        public TestB TB { get; set; }
    }
    public class TestB
    {
        public string Title { get; set; }
    }
`var temp = db.Queryable<Student>().Select(x => new TestA()
            {
                title = x.Name,
                TB = new
               TestB()
                { Title = x.Name }
            }).FirstAsync();
` 
Student表里面的列有id和Name。
调试了Sqlsugar代码，
 发现在AdoProvider中的方法GetDataReaderAsync里，生成的sql命令是这样的：
`SELECT  `Name` AS `title` , `Name` AS `Title` , `Title` AS `TestB.Title`  FROM `Student`    ORDER BY NOW()  LIMIT 0,1`

拿到Navicat上执行，结果如下：
 Unknown column 'Title' in 'field list'

**Comment by demon28** [comment]
没人重视这个问题吗

**Comment by cuihuakeji** [comment]
是呀，新版本不行，我发现老的版本（如：5.0.8.9）是可以执行的
