### ISSUE TITLE
SqlFunc.If 生产sql出错

### ISSUE THREAD

**Issue by keke9007** [sunkaixuan/SqlSugar#726]
await Db.Queryable(Db.Queryable<TaskModel>()
                .Where(_ => _.IsDel == false)
                .WhereIF(!string.IsNullOrEmpty(title), _ => _.Title.Contains(title))
                .Select(t => new TaskModel
                {
                    Id = t.Id,
                    Title = t.Title,
                    SiteCount = SqlFunc.Subqueryable<TaskSiteModel>().Where(ts => ts.Id == t.Id & ts.IsDel == false).Count(),
                    SiteFinishCount = SqlFunc.Subqueryable<TaskSiteModel>().Where(ts => ts.Id == t.Id & ts.IsDel == false & ts.State == TaskSiteState.Complete).Count()
                }))
                .Select(t => new TaskModel
                {
                    Id = t.Id,
                    Title = t.Title,
                    SiteCount = t.SiteCount,
                    SiteFinishCount = t.SiteFinishCount,
                    State = SqlFunc.IF(t.SiteFinishCount == 0).Return(0).ElseIF(t.SiteCount == t.SiteFinishCount).Return(2).End(1)
                })
                .Skip((page - 1) * pagesize)
                .Take(pagesize)
                .ToListAsync();
生成的sql
SELECT  
`Id` AS `Id` , 
`Title` AS `Title` , 
`SiteCount` AS `SiteCount` ,
 `SiteFinishCount` AS `SiteFinishCount` , 
 ( CASE  WHEN ( `SiteFinishCount` = @SiteFinishCount4 )  THEN  @Const5   WHEN ( `SiteCount` = `SiteFinishCount` )  THEN  @Const6  ELSE  @Const7  END ) AS `State`  
 FROM  (
 SELECT  `Id` AS `Id` , 
 `Title` AS `Title` ,
 (SELECT COUNT(*) FROM `ttaskeSite` WHERE (( `Id` = `t`.`Id` ) AND ( `IsDel` = @IsDel2 ))) AS `SiteCount` ,
 (SELECT COUNT(*) FROM `ttaskeSite` WHERE ((( `Id` = `t`.`Id` ) AND ( `IsDel` = @IsDel3 )) AND ( `State` = @State4 ))) AS `SiteFinishCount`  
 FROM `tTasks` t  WHERE ( `IsDel` = @IsDel0 )  
 AND  (`Title` like concat('%',@MethodConst1,'%'))  
 ) t  t     LIMIT 0,10

多了一个t

**Comment by sunkaixuan** [comment]
不支持2个SELECT持写法

**Comment by sunkaixuan** [comment]
或以用.select().mrgetable().select
