### ISSUE TITLE
AOP  跟踪SQL 写法有误

### ISSUE THREAD

**Issue by linkdream1** [sunkaixuan/SqlSugar#729]
官网 教程 AOP  跟踪SQL 写法有误，不能输出 带参数值的 sql;
http://www.codeisbug.com/Doc/8/1163
http://www.codeisbug.com/Doc/8/1140

原版：
//用来打印Sql方便你调式    
db.Aop.OnLogExecuting = (sql, pars) =>
            {
                Console.WriteLine(sql + "\r\n" + 
                db.Utilities.SerializeObject(pars.ToDictionary(it => it.ParameterName, it => it.Value)));
                Console.WriteLine();
            }; 

//修改后更好的体验：
db.Aop.OnLogExecuting = (sql, pars) =>
            {
            foreach (SugarParameter par in pars)
            {
                sql = sql.Replace(par.ParameterName,
                    par.Value == null ? "" : ("'" + par.Value.ToString() + "'"));
            }
            Debug.WriteLine(sql);
            Debug.WriteLine("");
            };

**Comment by sunkaixuan** [comment]
我这个只是写个例子让你明白怎么用的
