### ISSUE TITLE
db.SqlQueryable<TResult>(sql).ToPageListAsync()

### ISSUE THREAD

**Issue by sunclove** [sunkaixuan/SqlSugar#730]
执行这样语句时 db.SqlQueryable<TResult>(sql).ToPageListAsync()  出现查询报错，
例如  sql = 'select * from tablea' ; db.SqlQueryable<student>(sql).ToPageListAsync() 
  然而在查询发现，执行的语句有两条，
第一条查count 时   .... from tablea  没问题，
第二条查list 时  .... from  student ，此时我的查询不是tablea 吗

**Comment by zhan520g** [comment]
我也遇到了,唉
