### ISSUE TITLE
init mapping 空对象引用

### ISSUE THREAD

**Issue by zhaolongboy** [sunkaixuan/SqlSugar#731]
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SqlSugar.SqlSugarProvider.<>c__DisplayClass70_0.<InitMappingInfo>b__0(MappingTable it)
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   在 SqlSugar.SqlSugarProvider.InitMappingInfo(EntityInfo entityInfo)
   在 SqlSugar.SqlSugarProvider.InitMappingInfo(Type type)
   在 SqlSugar.SqlSugarProvider.InitMappingInfo[T]()
   在 SqlSugar.SqlSugarProvider.Queryable[T]()
   在 SqlSugar.SqlSugarClient.Queryable[T]()

**Comment by zhaolongboy** [comment]
有人遇到过这个问题吗？ 使用的版本是5.0.0.8，是mappingtable 报错吗

**Comment by sunkaixuan** [comment]
请写上重现代码

**Comment by zhaolongboy** [comment]
抱歉我没重现，原帖是日志记录的stack trace
