### ISSUE TITLE
 关于SugarHelper.db.Updateable更新不了数据

### ISSUE THREAD

**Issue by ly-sfer** [sunkaixuan/SqlSugar#732]
最近发现个问题   var edit = SugarHelper.db.Updateable(orderModel).ExecuteCommand();使用该方法进行修改操作  返回的edit =1  但是数据库中的数据并没有修改

异步中日志
2020-05-28 09:29:52.926 异步订单修改前_2376:orderModel.state结果:ok
2020-05-28 09:29:52.930 异步订单修改_2376:结果:1
2020-05-28 09:29:52.936 异步订单修改后_2376:orderModel.state结果:processing

代码如下
           BaseUtils.nWriteLog("异步订单修改前_" + logIndex.ToString() + ":", "orderModel.state结果:" + orderModel.state + "", logPath);
                        var edit = SugarHelper.db.Updateable(orderModel).ExecuteCommand();
                        BaseUtils.nWriteLog("异步订单修改_" + logIndex.ToString() + ":", "结果:" + edit + "", logPath);
                        orderModel = SugarHelper.Query.InWhere<Model.Also_TradeList>("orderNo = '" + orderNo + "'");
                        BaseUtils.nWriteLog("异步订单修改后_" + logIndex.ToString() + ":", "orderModel.state结果:" + orderModel.state + "", logPath);

**Comment by ly-sfer** [comment]
代码如下
                        BaseUtils.nWriteLog("异步订单修改前_" + logIndex.ToString() + ":", "orderModel.state结果:" + orderModel.state + "", logPath);
                        var edit = SugarHelper.db.Updateable(orderModel).ExecuteCommand();
                        BaseUtils.nWriteLog("异步订单修改_" + logIndex.ToString() + ":", "结果:" + edit + "", logPath);
                        orderModel = SugarHelper.Query.InWhere<Model.Also_TradeList>("orderNo = '" + orderNo + "'");
                        BaseUtils.nWriteLog("异步订单修改后_" + logIndex.ToString() + ":", "orderModel.state结果:" + orderModel.state + "", logPath);

**Comment by sunkaixuan** [comment]
这个没力法给你答案请给出详细的重现步骤，或者代码
