### ISSUE TITLE
【实体自动填充】 视图:实体类  视图继承实体，在自动填充下，数据中带下划线字段无法填充，但是没有下划线的可以

### ISSUE THREAD

**Issue by jol5** [sunkaixuan/SqlSugar#733]
1.例子 
 var list = db.Queryable<Student, School>((st, sc) => new object[] {
        JoinType.Left,st.SchoolId==sc.Id})
      .Select<ViewModel>().ToList();
       
//sql   
SELECT  [st].[ID] AS [id] , 
          [st].[Name] AS [name] ,  
          [sc].[Name] AS [schoolName]/*ORM自动识别出这一列*/  
          FROM [STudent] st 
          Left JOIN School sc ON ( [st].[SchoolId] =[sc].[Id])
       

//class
public class Student{
  public int ID{get;set;}
  public string FullName{get;set;}   // 无法填充-----（库内名字为 full_name）
}
   
//class
public class ViewModel : Student{
  public int ID{get;set;}
  public string schoolName{get;set;}//类名+Name
  public string schoolFullName{get;set;}//可以映射

}

2.sql语句正常，就是所继承的实体类，无法填充数据库原始指端带 下划线 的字段
3.不继承可（就是把所有字段复制到view中）

**Comment by sunkaixuan** [comment]
实体类中如果叫 FULLNAME那么你就要写成  实体类名+FULLNAME
