### ISSUE TITLE
当ColumnName与类属性名称定义不一致时，查询实体映射失败

### ISSUE THREAD

**Issue by a156845044** [sunkaixuan/SqlSugar#736]
实体定义示例;
        [SugarColumn(ColumnName = "app_id")]
        public long AppId { get; set; }

在指令栏位查询时 （ db.Queryable<TEntity>().Select(selector) ） 实体无法映射。

在源码断点跟踪时发现，生成的sql 语句使用了实体的Member.Name 
例如： select appId from app
实际上数据库想要的是  select app_id from app
备注：使用的是sqlserver 数据库

实际项目中，由于客户对命名规范有要求，必须使用“小写 + 下划线命名”的方式，而C# 属性在定义时这种命名又不被允许。

**Comment by sunkaixuan** [comment]
你这个具体是什么要写清楚 selector 不然无法定位

**Comment by a156845044** [comment]
抱歉，刚看到回复，是这样。
例如：
实体定义
`  
    /// <summary>
    /// 示例
    /// </summary>
    [SugarTable("sys_config")]
    public class SysConfig 
    {
        /// <summary>
        /// 主键
        /// </summary>
        [SugarColumn(ColumnName = "id", IsPrimaryKey = true, IsIdentity = false)]
        public long Id { get; set; }

        /// <summary>
        /// 父级id
        /// </summary>
        [SugarColumn(ColumnName = "parent_id")]
        public long ParentId { get; set; }

        /// <summary>
        /// 配置项
        /// </summary>
        [SugarColumn(ColumnName = "config_key")]
        public string ConfigKey { get; set; }
    }`

查询示例：
`var list=   db.Queryable<SysConfig >().Select(it => new SysConfig { Id = it.Id, ParentId= it.ParentId,ConfigKey=it.ConfigKey}).ToList();`

生成的sql:
`SELECT  [id] AS [Id] , [parent_id] AS [ParentId] , [config_key] AS [ConfigKey]  FROM [sys_config]  `
![image](https://user-images.githubusercontent.com/6487297/86203044-82131a80-bb96-11ea-948a-98d78d19946d.png)

这种带下划线的字段会映射失败，值全是null

希望得到的sql:
`SELECT  [id] AS [id] , [parent_id] AS [parent_id] , [config_key] AS [config_key]  FROM [sys_config] `

![image](https://user-images.githubusercontent.com/6487297/86203108-b555a980-bb96-11ea-9c4d-615e90a225b2.png)


pr 中只是临时解决了这个问题，如果你有其他更好的方法可以不采用。望更新。

**Comment by zhan520g** [comment]
带下划线的字段不会失败的，已经在使用了。

**Comment by zhan520g** [comment]
数据库是mysql

**Comment by a156845044** [comment]
我用的是.net core 5.x版本，数据库使用的是sqlserver， 大佬可以使用我实体定义的方式实验一下，确实遇到了这个问题。

**Comment by a156845044** [comment]
问题是出在生成sql的时候我的数据库里是带下划线的，而as的时候是按照实体属性名来重命名。具体的映射逻辑没有去看，不好乱猜，我提的pr中是将as取值改为了 sqlcolum这个问题就好了
