### ISSUE TITLE
Updateable(updateobj).As(tablename) 没有生效

### ISSUE THREAD

**Issue by shinyrabbit** [sunkaixuan/SqlSugar#75]
版本4.6
当SugarTable的名称和实体类的名臣不一致的时候，使用Updateable(XX).As(XX)是替换表名没有生效

**Comment by idantony** [comment]
我们这边当使用SugarTable在实体上面标注后，不用写As也能更新
`[SugarTable("Address")]
    public class AddressEntity : ModelContext`

**Comment by shinyrabbit** [comment]
我这儿是需要替换表名的，例如[SugarTable("Address")] public class AddressEntity
Updateable(AddressEntity).As(“AddressTable2”) 这时候是更新不了的
