### ISSUE TITLE
能否增加插入更新功能upsert?以及大数据处理能力？

### ISSUE THREAD

**Issue by yzpopulation** [sunkaixuan/SqlSugar#76]
能否增加插入更新功能upsert?
比如我要导出1000W 数据 导出成csv 每1000条做个切分，直接tolist内存吃不消，用分页每次都要查询影响效率，原生的 可以循环读取，避免崩溃，但是需要手动添加到指定大小的 list 然后生成csv，

**Comment by sunkaixuan** [comment]
这个功能自已扩展一下
