### ISSUE TITLE
emoji 单个对象添加正常，多个对象批量添加会报错，大佬，看看

### ISSUE THREAD

**Issue by zhan520g** [sunkaixuan/SqlSugar#769]

**Comment by zhan520g** [comment]
已设置数据库为utf8mb4, 用sql语句插入emoji正常

**Comment by gavinguohub** [comment]
兄台，你这个问题解决了吗？我也遇到了这个问题，单挑插入是正常的，批量插入就报错Incorrect string value: '\xF0\x9F\x91\x8C' for column 'xxx' at row 1.
是框架的确有这个问题还是我使用的姿势不正确？

**Comment by zhan520g** [comment]
没有,好像是数据库设置问题。着实有点难解。&nbsp; 我有个库又可以批量插入。另外一个库死活不行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gavin"<notifications@github.com&gt;; 
发送时间: 2020年8月12日(星期三) 下午2:05
收件人: "sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com&gt;; 
抄送: "张操"<172610800@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sunkaixuan/SqlSugar] emoji 单个对象添加正常，多个对象批量添加会报错，大佬，看看 (#769)





 
兄台，你这个问题解决了吗？我也遇到了这个问题，单挑插入是正常的，批量插入就报错Incorrect string value: '\xF0\x9F\x91\x8C' for column 'xxx' at row 1.
 是框架的确有这个问题还是我使用的姿势不正确？

**Comment by sanchez0623** [comment]
为啥关闭了哦？
我现在遇到一个情况，数据库，用到的表，用到的字段 都设置了utf8mb4，但一张表的字段可以插入表情，另一张表的字段却一插入表情就报错，这是为啥？
