### ISSUE TITLE
如何让查询和保存  可以轻松让 逗号分隔的数据，映射成 List或者数组呢？

### ISSUE THREAD

**Issue by jol5** [sunkaixuan/SqlSugar#776]
数据库字段  roles=> 1,2,3,4
实体属性：List<int> Roles {get;set;}

可以正常CURD

**Comment by withsalt** [comment]
这种不应该是自己写业务逻辑吗，或者自己在查询的时候map

**Comment by liuliyang123** [comment]
数据库就是string 类型，自己再定义个属性就行了。
