### ISSUE TITLE
SqlFunc.Subqueryable 的.any不能select字段，生成的是select * 会不会影响性能？

### ISSUE THREAD

**Issue by huguodong** [sunkaixuan/SqlSugar#778]
query.Where(it => SqlFunc.Subqueryable<OrderApproval>().Where(u => u.OrderId == it.Id && u.UserId == userid).Any());

如果在any方法前面加select，运行的时候会报错，不加的话生成的语句是select *

**Comment by GUANGFANCHEN** [comment]
不会，相当于Exists

**Comment by dangzhensheng** [comment]
any看输出语句是用了count判断的，个人觉得不合理，自己改写个查询1条数据再判断
