### ISSUE TITLE
SqlSugarClient  单例问题

### ISSUE THREAD

**Issue by zhouwangfeng2007** [sunkaixuan/SqlSugar#784]
在最新版本的5.0.0.14版本以后，是不是SqlSugarClient 可以是单例了？

**Comment by zhouwangfeng2007** [comment]
因为我测试了一下  framework和netcore下，最新版本的5.0.0.14都没有数据库连接单例情况下的异常了。

**Comment by zhouwangfeng2007** [comment]
一个简单的问题也不回答，直接关闭了？

**Comment by sunkaixuan** [comment]
改了统一提交地址 http://www.codeisbug.com/Home/Doc?typeId=1213

**Comment by sunkaixuan** [comment]
目前单例还是不能很好支持，尽量不要用单例，我这边技术也没办法做到单例安全运行
