### ISSUE TITLE
指定库的函数,比如Use("DB1") ,这个好实现吗

### ISSUE THREAD

**Issue by TomLiu-GitHub** [sunkaixuan/SqlSugar#785]
一般企业管理软件ERP之类的都会有多公司多账套库的概念
而程序一般会从主库,如下图主库是`UFSystem`
来读取用户的数据在哪个库.
![image](https://user-images.githubusercontent.com/32833966/87620501-5032b400-c751-11ea-83c7-4399a4cd6cb3.png)
那么我需要根据用户来Use("UFDATA_001_2019")...来操作指定的库.
我是小白,请问这个好实现吗?谢谢大佬
我现在是 一堆的SqlSugarClient和直接sql里写use,因为要用原生sql写use,很多SqlSugar的功能特性都没能用上, 如果能使用use来指定库就省很多事情了

**Comment by liuliyang123** [comment]
两个思路，一个是改连接字符串，另一个是用mappertable，动态指定库名表名。

**Comment by TomLiu-GitHub** [comment]
谢谢你,这个思路等于没说.

**Comment by liuliyang123** [comment]
第二种都没试过呢

**Comment by TomLiu-GitHub** [comment]
已自己实现了Use
