### ISSUE TITLE
Where()内对Nullable<T>类型的实体字段使用GetValueOrDefault()方法时报错，以及Select用法的一个奇怪现象

### ISSUE THREAD

**Issue by liruoyu2008** [sunkaixuan/SqlSugar#789]
### 版本

.Net Framework  4.5

SqlSugar 5.0.0.9

### 代码

```c#
    try
    {
        using (var dal = new SqlSugarClient(config))
        {
            List<AQXM_NAME> res = dal.Queryable<AQXM_NAME>()
                .Where(it => itemID == it.XDJSFLID.GetValueOrDefault().ToString())
                .Select(it => new AQXM_NAME { AQXM_ID = it.AQXM_ID, XM_NAME = it.XM_NAME })
                .ToList();
            return res;
        }
    }
    catch (Exception ex)
    {
        LogProvider.Write(ex.Message, LogMessageType.Error, ex);
        return new List<AQXM_NAME>();
    }
```

### 实体

```c#
public class AQXM_NAME
{
    /// <summary>
    /// 编码ID
    /// </summary>
    [SugarColumn(ColumnName = "ID")]
    public long AQXM_ID { get; set; }

    /// <summary>
    /// 项点名称
    /// </summary>
    public string XM_NAME { get; set; }

    /// <summary>
    /// 安全检索分类（关联安全检索分类表）
    /// </summary>
    public long? XDJSFLID { get; set; }

    ///==========其他属性省略============///
}
```

### 报错1

English Message : Expression parsing does not support the current function GetValueOrDefault.There are many functions available in the SqlFunc class, for example, it=>SqlFunc.HasValue(it.Id)

Chinese Message : 拉姆达解析不支持当前函数GetValueOrDefault，SqlFunc这个类里面有大量函数可用,也许有你想要的，例如： it=>SqlFunc.HasValue(it.Id)"}

### 报错2

当我将GetValueOrDefault()去掉，直接使用 it.XDJSFLID.GetValueOrDefault().ToString() 后，没有报错，查询通过，但是查出来的两个字段，XM_NAME存在值，而AQXM_ID始终是默认0。若我将Select用法改一下，返回匿名类，或直接Select<AQXM_NAME>().ToString()，就没有这个问题。

### 疑问

从数据库中查询出来的字段若对应 Nullable<T> 类型，是否只能用SqlFunc函数进行判断而不能使用GetValueOrDefault()？以及当前若不支持，是否后续会考虑实现？

**Comment by liuliyang123** [comment]
GetValueOrDefault 是你自定义 扩展方法吧，不支持解析的

**Comment by liruoyu2008** [comment]
> GetValueOrDefault 是你自定义 扩展方法吧，不支持解析的

这个方法是可空类型的BCL自带方法啦。不过你谢谢你，我已经找到办法了，sugar自带的SqlFunc有对应的替代方法。
