### ISSUE TITLE
Postgresql数据库，做模糊查询时生成的Like语句的值会区分大小写，是否可以支持ILIKE

### ISSUE THREAD

**Issue by capfhz** [sunkaixuan/SqlSugar#791]
Postgresql数据库，做模糊查询时生成的Like语句的值会区分大小写，是否可以支持ILIKE

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Doc/8/1162

**Comment by kenzouno1** [comment]
Link not found. Are you can update new link document?

**Comment by kenzouno1** [comment]
> http://www.codeisbug.com/Doc/8/1162


Link not found. Are you can update new link document?
