### ISSUE TITLE
建议增加SqlFunc扩展方法对应字符串大小与和大小等于的判断

### ISSUE THREAD

**Issue by lpyedge** [sunkaixuan/SqlSugar#792]
好多情况下有字符串类型有规律的字段,比如需要做小于等于之类的判断操作,sql语法是支持的.
但是linq语法本身不支持,但是SqlFunc又没有对应的扩展方法.希望考虑加入对应方法.

**Comment by lpyedge** [comment]
没有其他人有这个需求么？奇怪？

**Comment by sunkaixuan** [comment]
SQLFUNC有自定义扩展功能
