### ISSUE TITLE
插入decimal类型的字段时，会精度丢失

### ISSUE THREAD

**Issue by zuozhiwen** [sunkaixuan/SqlSugar#8]
这是sql跟踪生成的代码
@ProductMonthRate decimal(2,2)
@ProductMonthRate=0.71

最后表中的值
ProductMonthRate
1
0
1
1
1
1
1

表中定义的是
ProductMonthRate decimal(18, 0) 允许为NULL

**Comment by sunkaixuan** [comment]
decimal(18, 2)
