### ISSUE TITLE
AddQueue where 中使用函数未转换

### ISSUE THREAD

**Issue by HeLinSpace** [sunkaixuan/SqlSugar#801]
![QQ图片20200807151117](https://user-images.githubusercontent.com/38428011/89619298-50415200-d8c0-11ea-885d-d7e8e31f424a.png)
![image](https://user-images.githubusercontent.com/38428011/89619314-56cfc980-d8c0-11ea-838c-34958b546604.png)

_baseSqlSugarClient.Queryable<Lgd_Debt>().Where(s => !s.IsDelete&&s.AreaId.StartsWith("3202")).AddQueue();

报错信息：必须声明标量变量“@MethodConst0”

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
