### ISSUE TITLE
Group 后Select/Having 都不支持SqlFunc.AggregateCount

### ISSUE THREAD

**Issue by lovesans** [sunkaixuan/SqlSugar#808]
SqlSugar版本5.0,Mysql 5.7
`Db.Queryable<LineModel>()
                .GroupBy(p => p.LineCode)
                .Select(p => new { p.LineCode, V = SqlFunc.AggregateCount(p.LineCode) })
                .ToList();`
错误信息：
English Message : Expression parsing does not support the current function AggregateCount. There are many functions available in the SqlFunc class, for example, it=>SqlFunc.HasValue(it.Id)
Chinese Message : 拉姆达解析不支持当前函数AggregateCount，SqlFunc这个类里面有大量函数可用,也许有你想要的，例如： it=>SqlFunc.HasValue(it.Id)”

使用GroupBy().Having()也是这种提示，完全按照文档里的例子写的也不行
`var group = Db.Queryable<LineModel>()
                .GroupBy(it => it.LineId)
                .Having(it => SqlFunc.AggregateCount(it.LineId) > 10)
                .Select(it => new { id = SqlFunc.AggregateCount(it.LineId) })
                .ToList();`

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
