### ISSUE TITLE
请问是否支持持久性sql

### ISSUE THREAD

**Issue by makyo5** [sunkaixuan/SqlSugar#81]
您好。我粗略的看了文档。
但是，想问问，是否支持持久性的sql？比如hibernate那种，使用xml（或者json）来保存sql语句。因为我们的项目的sql查询比较多。

**Comment by chenmfly** [comment]
SmartSQL，你可以参考一下！

**Comment by makyo5** [comment]
谢谢楼上。非常有用。

**Comment by sunkaixuan** [comment]
有日志功能可以拿到每次执行的SQL

**Comment by makyo5** [comment]
sunkaixuan，麻烦看看我在文档园提的问题。
有一个问题无法解决，看了http://www.codeisbug.com/Doc/8/1140，也不知道如何跟踪出sql语句。
