### ISSUE TITLE
用DbMaintenance.CreateTable 时候，创建表是，列的备注信息没有加上。

### ISSUE THREAD

**Issue by henq** [sunkaixuan/SqlSugar#813]
1. 大牛，创建表 db.DbMaintenance.CreateTable(table.DbTableName, columns);，备注信息没有加上。
2. 添加列注释功能没有实现。 db.DbMaintenance.AddTableRemark(table.DbTableName, table.TableDescription);
3. 我想为Sqlsugar贡献点代码，需要怎么申请加入开发组吗？

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
