### ISSUE TITLE
Chinese Message : 实体与表映射出错。Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by zz110** [sunkaixuan/SqlSugar#814]
Chinese Message : 实体与表映射出错。Object reference not set to an instance of an object.

**Comment by zz110** [comment]
异常调用代码 
var monthlyVolumeObj = dbContext.Ado.SqlQuery<MonthlyVolume>(sql, new { year_dim = currentYear, month_dim = 8 }); 

折中方案
                    var monthlyVolumeObj = dbContext.Ado.SqlQueryDynamic(sql, new { year_dim = currentYear, month_dim = 8 }); 
                    List<MonthlyVolume> monthlyVolume = new List<MonthlyVolume>();
                    foreach (dynamic item in monthlyVolumeObj)
                    {
                        monthlyVolume.Add(new MonthlyVolume { month_dim = item.month_dim, volume = item.volume });
                    }

**Comment by zz110** [comment]
异常调用代码
`
var monthlyVolumeObj = dbContext.Ado.SqlQuery<MonthlyVolume>(sql, new { year_dim = currentYear, month_dim = 8 }); 
`


折中方案
`


                    var monthlyVolumeObj = dbContext.Ado.SqlQueryDynamic(sql, new { year_dim = currentYear, month_dim = 8 }); 
                    List<MonthlyVolume> monthlyVolume = new List<MonthlyVolume>();
                    foreach (dynamic item in monthlyVolumeObj)
                    {
                        monthlyVolume.Add(new MonthlyVolume { month_dim = item.month_dim, volume = item.volume });
                    }

`

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
