### ISSUE TITLE
动态连表貌似不支持

### ISSUE THREAD

**Issue by 656511385** [sunkaixuan/SqlSugar#816]
先判断在进行连接
JoinType.Left,(flag==1?H.unitId==DA.dataId2:H.seatID==DA.dataId2)&&DA.isDel==0&&DA.isAllot==1&&DA.daType==3
现在会报异常The SqlFunc.IIF(arg1,arg2,arg3) , (H.unitId == DA.dataId2) argument  do not support 
还是有其它不麻烦的方式可以实现？

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
