### ISSUE TITLE
跨库连表查询是否支持

### ISSUE THREAD

**Issue by 656511385** [sunkaixuan/SqlSugar#817]
没有在文档上看到跨库连表的语法

**Comment by liuliyang123** [comment]
做好动态 表名映射就行了，dblink 或者 linkserver  该怎么查表 就怎么映射表名就行。

**Comment by 656511385** [comment]
谢谢，已解决

**Comment by 656511385** [comment]
> 做好动态表名映射就行了，dblink或linkserver该怎么查表就怎么映射表名就行。

谢谢,已解决

**Comment by 656511385** [comment]
> 做好动态表名映射就行了，dblink或linkserver该怎么查表就怎么映射表名就行。

谢谢,已解决
