### ISSUE TITLE
使用 SqlQueryable函数执行一条查询重复的sql语句，排序无效

### ISSUE THREAD

**Issue by uniwind** [sunkaixuan/SqlSugar#818]
sql="select * from TelephoneBook where number in (select number from TelephoneBook group by number having count(number) > 1) order by number ASC"

mysql数据库，使用var list = SqlQueryable<T>(sql).ToList()执行该sql语句，排序无效。

**Comment by sunkaixuan** [comment]
用db.ado.sqlquery

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
