### ISSUE TITLE
在同一个异步方法里，使用Sqlsugar执行操作，部分成功，部分失败

### ISSUE THREAD

**Issue by kevincwj2008** [sunkaixuan/SqlSugar#819]
使用了读写分离配置，在Service里注入了SqlsugarClient，在一个方法里执行查询能成功，查询出来数据后进行一系列的处理，然后删除某个日期的数据并重新写入，这时再删除的时候报错：“SqlSugar.SqlSugarException: English Message : Connection open error . 用户 'sa' 登录失败。
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：用户 'sa' `登录失败。.”，不管是否使用事务都会出现这个错误

`private async Task StatisticsFaultOuageFromOutage(DateTime date) 
{
            var startTime = date.Date;
            var endTime = startTime.AddDays(1);
            var outageList = await _dbContext.Db.Queryable<Outage, Outage_Line>((o, ol) => new object[] { JoinType.Right, o.Id == ol.OutageId })
                            .Where(o => o.Type == (int)Enum_OutageType.Fault && o.StartTime >= startTime && o.StartTime < endTime).OrderBy(o => o.StartTime).Select((o, ol) => new
                            { ol.LineId, o.Area, o.Reason, o.StartTime }).ToListAsync();
            if (outageList == null || outageList.Count == 0)
                return;
            var allLines = await _powerSupplyLineService.GetAll();
            var allTransformerUserNumber = await _powerSupplyLineService.GetAllTransformerUserNumber();
            var statisticsInputList = new List<Statistics_FaultOutage>();
            Statistics_FaultOutage tempFaultOutageInput;
            foreach (var item in outageList)
            {
                var currentLine = allLines.FirstOrDefault(l => l.Id == item.LineId);
                var companyName = currentLine.Company[0].Name;
                var faultType = (int)GetFaultTypeByReason(item.Reason);
                var lineName = currentLine.Name + GetOutageWholeLine(item.Area, item.Reason);
                tempFaultOutageInput = statisticsInputList.FirstOrDefault(c => c.Company == companyName && c.FaultType == faultType && c.Line == lineName);
                if (tempFaultOutageInput != null)
                {
                    tempFaultOutageInput.OutageNumber++;
                    continue;
                }
                var currentTransformerUserNumber = allTransformerUserNumber.FirstOrDefault(n => n.LineId == item.LineId);
                var currentEarlyWarning = await _powerSupplyLineService.GetEarlyWarning(item.LineId, startTime);
                tempFaultOutageInput = new Statistics_FaultOutage
                {
                    Id = Guid.NewGuid(),
                    Date = startTime,
                    Line = lineName,
                    FaultType = faultType,
                    Company = companyName,
                    LineNature = AttributeHelper.GetRemark(currentLine.AssetsNature),
                    RepeatedNumber = _dbContext.Db.Queryable<Outage, Outage_Line>((o, ol) => new object[] { JoinType.Right, o.Id == ol.OutageId })
                                .Where((o, ol) => ol.LineId == item.LineId && o.Type == faultType && o.StartTime >= startTime.AddDays(-29) && o.StartTime < endTime).Count(),
                    OutageNumber = 1,
                    TransformerNumber = currentTransformerUserNumber != null ? currentTransformerUserNumber.TransformerNumber : 0,
                    PowerUserNumber = currentTransformerUserNumber != null ? currentTransformerUserNumber.UserNumber : 0,
                    Remark = GetFaultRemarkByReason(item.Reason),
                    EarlyWarning = currentEarlyWarning.earlyWarningType.HasValue ? (int)currentEarlyWarning.earlyWarningType.Value : default(int?),
                    EarlyWarningRemark = currentEarlyWarning.earlyWarningRemark,
                    CreateTime = item.StartTime
                };
                statisticsInputList.Add(tempFaultOutageInput);
            }
            var allCompany = await _powerSupplyCompanyService.GetAll();
            var dataNow = DateTime.Now;
            statisticsInputList = statisticsInputList.Join(allCompany, s => s.Company, c => c.Name, (s, c) => new { Company = c, DataInput = s }).OrderBy(c => c.DataInput.FaultType).ThenBy(c => c.Company.Path).ThenBy(c => c.DataInput.CreateTime).Select((c, index) => {
                c.DataInput.CreateTime = dataNow.AddSeconds(index);
                c.DataInput.Company = c.DataInput.Company.Replace("国网", "").Replace("供电公司", "").Replace("供电中心", "");
                return c.DataInput;
            }).ToList();
            //var result = _dbContext.Db.UseTran(() =>
            //{
                _dbContext.Db.Deleteable<Statistics_FaultOutage>().Where(c => c.Date == startTime).ExecuteCommand();
                _dbContext.Db.Insertable(statisticsInputList).ExecuteCommand();
            //});
            //if (!result.Data)
            //    _logger.LogError(result.ErrorMessage);
        }`

但是我将读写分离功能去掉，就能够执行成功

**Comment by kevincwj2008** [comment]
`SQLite error (5): database is locked in "INSERT INTO `TestLong`  `

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
