### ISSUE TITLE
查询日期问题

### ISSUE THREAD

**Issue by LuGuangguang** [sunkaixuan/SqlSugar#820]
使用的是core 版本的5.0.0.14，数据库是Sqlite,结构如下
![图片](https://user-images.githubusercontent.com/34500722/93155736-520cf980-f739-11ea-99fc-64eb12176f76.png)
想要符合范围的数据，编码如下

![图片](https://user-images.githubusercontent.com/34500722/93157226-69011b00-f73c-11ea-94d9-56199c302d5c.png)
在查询条件符合的情况下，依旧查不到任何数据

**Comment by liuliyang123** [comment]
用错方法了sqlfunc.todate 是转换成C# 的时间类型，你判断的是数据库字段，如果要对时间取到天 自己写扩展函数

**Comment by LuGuangguang** [comment]
> 
> 
> 用错方法了sqlfunc.todate 是转换成C# 的时间类型，你判断的是数据库字段，如果要对时间取到天 自己写扩展函数

好的，谢谢。用短期日格式解决了
