### ISSUE TITLE
使用SqlSugar5.0批量插入时怎么返回-1了？

### ISSUE THREAD

**Issue by jindongbin** [sunkaixuan/SqlSugar#821]
int index = await db.Insertable(listEntity.ToArray()).ExecuteCommandAsync();
这个index=-1,但是插入成功了。
没有自增长字段，主键是guid。

**Comment by jindongbin** [comment]
接上文，打印出来的sql语句是这样的。
BEGIN
INSERT INTO "TABLE1"  ("ID","RID","PID")
 SELECT N'rde698b7cfcb749ba861c3ff0b949eafa' AS "ID",N'20656a4246e04558b214561210efa1a0' AS "RID",N'p78eaddb38f1e4fa69cdf419a12ee17f6' AS "PID" FROM DUAL  
UNION ALL 
 SELECT N'r871a57fb8bb647b48272df5312b72766' AS "ID",N'20656a4246e04558b214561210efa1a0' AS "RID",N'p3679b0dc47d94a7bb89c578fa025ab92' AS "PID" FROM DUAL 
 ;
END;

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
