### ISSUE TITLE
联合分页查询同步正常异步报错

### ISSUE THREAD

**Issue by h619633675** [sunkaixuan/SqlSugar#823]
当使用异步的分页查询时，生成的 sql 语句 copy 出来是可以正常运行的。但是在程序中只执行到查数量就终止运行而报错了。
而切换成同步的分页查询时，联合查询就能够正常执行下去。

**Comment by neozhu** [comment]
看你的代码，通常分页查询 分两步，先要 count() 总记录数，再执行分页查询。如果用类库的方法应该不会有问题

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
