### ISSUE TITLE
Select后Where查不出数据，我试了下EF可以，不知道是不支持还是....??

### ISSUE THREAD

**Issue by MrLuoJi** [sunkaixuan/SqlSugar#825]
![捕获](https://user-images.githubusercontent.com/40336788/93983842-ab1e0280-fdb5-11ea-899d-d3da6f5c8439.PNG)

**Comment by neozhu** [comment]
可能是实体对象userinfo和表的关系没对应上，你可以换 context.ado.SqlQuery<UserInfo>() 试试

**Comment by MrLuoJi** [comment]
好的，我去试一试

**Comment by sunkaixuan** [comment]
.Select(xxx).MergeTable().Where 这样就可以了

**Comment by MrLuoJi** [comment]
好的，我试了下可以
