### ISSUE TITLE
CodeFirst表别名使用库名称+表名称只能创建一次,后续无法修改

### ISSUE THREAD

**Issue by 656511385** [sunkaixuan/SqlSugar#826]
注解[SugarTable("HouseFeaturedTbl")]这样写就没有问题，后续修改和添加的字段都会执行
如果注解这样写[SugarTable("operationdb.dbo.HouseFeaturedTbl")]已经创建表,后续的字段修改都不会执行了，报异常说数据库已存在该表HouseFeaturedTbl
按第一种写法的话[SugarTable("HouseFeaturedTbl")]不加库名称，跨库联表查询就不行了

**Comment by sunkaixuan** [comment]
可以用使用自定义特性的AOP动态改变 ，如果用CODEFIRST就不加AOP处理，如果查询添加AOP处理


http://www.codeisbug.com/home/Doc?typeId=1182

**Comment by sunkaixuan** [comment]
或者查询用这种方式

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
