### ISSUE TITLE
默认值的问题

### ISSUE THREAD

**Issue by Vix1994** [sunkaixuan/SqlSugar#830]
sqlserver环境下给datetime设定了默认值getdate()

在字段映射的时候尝试添加[SugarColumn(IsOnlyIgnoreInsert = true)]属性，可以成功插入，并且数据库里值也是有的，但是在最后的ExecuteReturnEntity返回的实体的日期值为null。

`[SugarColumn(IsOnlyIgnoreInsert = true)]
        public DateTime CreateTime { get; set; }`
`Db.Insertable(feedback).ExecuteReturnEntity()`

这个目前能解决吗？

**Comment by sunkaixuan** [comment]
如果是自增列用isidentity=true，不能用  IsOnlyIgnoreInsert

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
