### ISSUE TITLE
SqlSugarCore在postgre数据库下面bug多多

### ISSUE THREAD

**Issue by ieeve** [sunkaixuan/SqlSugar#832]
运行环境： .net Core3.1 
数据库：PostgerSql
出错说明：**浮点数类型**转换错误。

           var list1 = db.Ado.SqlQuery<PgSqlTest.Models.test1>("select * from test1");
            var list = db.Queryable<PgSqlTest.Models.test1>().ToList();

执行结果中，如果数据库字段为**浮点数类型**，那么返回的浮点数值错误。
经测试，此问题只在.netCore下产生，.netFramework4.5正常

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
