### ISSUE TITLE
Pgsql 数据库 DbContext 设置了PgSqlIsAutoToLower=false 使用Mapper时 mapperFiled 没有忽略大小写，

### ISSUE THREAD

**Issue by 1haoyu** [sunkaixuan/SqlSugar#833]
Pgsql 数据库 DbContext 设置了PgSqlIsAutoToLower=false 使用Mapper时 mapperFiled 没有忽略大小写，希望及时修复一下BUG

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1213 统一提交入口
