### ISSUE TITLE
PostgreSQL 设置IsJson 查询不出数据

### ISSUE THREAD

**Issue by 1haoyu** [sunkaixuan/SqlSugar#834]
[SugarColumn(IsJson =true,ColumnDataType ="json")]
       public List<Sys_Actions> Auth { get; set; } = new List<Sys_Actions>();

查询 Auth 对象 为 null

**Comment by sunkaixuan** [comment]
给我一个控制台demo 吧 这种很难讲清楚 qq 610262374

**Comment by sunkaixuan** [comment]
统一BUG 提交入口 http://www.codeisbug.com/Home/Doc?typeId=1213
