### ISSUE TITLE
sqlite 更新至5.0.0.19  含有byte[] 实体集合 批量插入导致新的异常

### ISSUE THREAD

**Issue by Exception-King** [sunkaixuan/SqlSugar#841]
SQL logic error or missing database
hex literal too big: 0x62706C6973743030D2010203045F1018434B4368617457617465726D61726B4D65737361676549445F1013434B4368617457617465726D61726B54696D6511156D2341D7AD8B1F8652FC080D283E41000000000000010100000000000000050000000000000000000000000000004A

**Comment by sunkaixuan** [comment]
给个DEMO吧 发 ，我这边重现不了

**Comment by Exception-King** [comment]
https://github.com/Exception-King/sqlsugarTest 一个测试demo

**Comment by sunkaixuan** [comment]
已找到方案 ，请关就 http://www.codeisbug.com/Home/Doc?typeId=1213 版本发布

**Comment by sunkaixuan** [comment]
GITHUB的源码已经上传了，你可以下源码搞个DLL测试一下，NUGET需要过些时间才会发布新版本

**Comment by Exception-King** [comment]
目前没测出问题
