### ISSUE TITLE
新增IsJson字段升级表失败

### ISSUE THREAD

**Issue by mutu01** [sunkaixuan/SqlSugar#843]
数据库：sqlserver

在实体定义中添加List<KeyValuePair<int,string>>内容，已经标识未IsJson=true升级失败。

SqlSugar.SqlSugarException:“序列不包含任何元素”

**Comment by sunkaixuan** [comment]
你这个是新表吗

     public class x1xx {
            [SugarColumn(IsPrimaryKey =true,IsIdentity =true)]
             public int id { get; set; }
            [SugarColumn(IsJson =true,ColumnDataType ="nvarchar(1000)")]
            public List<KeyValuePair<int, string>> x { get; set; }
        }
    db.CodeFirst.InitTables(typeof(x1xx));

            db.Insertable(new x1xx() { x = new List<KeyValuePair<int, string>>()
            {

              new KeyValuePair<int, string>(1,"a")
            }
            }).ExecuteCommand();

          var x=  db.Queryable<x1xx>().ToList();

我这个例子是可以成功的

**Comment by mutu01** [comment]
不是新表。

**Comment by sunkaixuan** [comment]
表一定是要 sqlsugar codefirst 建出来的，然后你在添加字段就可以了

**Comment by mutu01** [comment]
使用sqlsugar codefirst 创建的表，后面添加字段的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sunkaixuan"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 下午2:32
收件人: "sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com&gt;; 
抄送: "DU"<duwx@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sunkaixuan/SqlSugar] 新增IsJson字段升级表失败 (#843)





 
表一定是要 sqlsugar codefirst 建出来的，然后你在添加字段就可以了

**Comment by sunkaixuan** [comment]
你在把现有的这个字段删掉，试试，或者给我一个能重现的DEMO

**Comment by sunkaixuan** [comment]
如果还有问题请在这个地址统一提问 http://www.codeisbug.com/Home/Doc?typeId=1213
