### ISSUE TITLE
拼接兰姆达使WhereIF失效

### ISSUE THREAD

**Issue by 18454760539** [sunkaixuan/SqlSugar#844]
[SqlSugarTest.zip](https://github.com/sunkaixuan/SqlSugar/files/5388693/SqlSugarTest.zip)

**Comment by sunkaixuan** [comment]
你的代码等于这样
        var x = SalesRouteExpression(test); //这个方法无论如何都会执行的因为你不执行怎么把参数传进来
            var sql = db.Queryable<CodeFirstTable1>().WhereIF(st == 1, x).ToSql();//这样可以看到SQL，条件并没有加进来

**Comment by 18454760539** [comment]
也就是说会执行，但是并不会影响到查询结果

**Comment by sunkaixuan** [comment]
是这样的
