### ISSUE TITLE
我正在调查freesql抄袭sqlsugar事件

### ISSUE THREAD

**Issue by tonyqus** [sunkaixuan/SqlSugar#845]
由于dotnetcore/NPOI的缘故，我已启动对NCC组织全面独立调查，我注意到他们的commit history有明显异常，想打听下freesql之前有没有什么瓜吗？我是社区吃瓜爱好者

**Comment by sunkaixuan** [comment]
前期有借鉴sqlsugar的地方，一些类名和架构，语法也比较接近，其它的我也没有太关注
