### ISSUE TITLE
sqlsugar orm  应用发布之后系统无法连接数据库 Unable to connect to any of the specified MySQL hosts.

### ISSUE THREAD

**Issue by yeibl** [sunkaixuan/SqlSugar#846]
场景：程序发布
环境：linux (centos 7)  .net core 2.2 ,mysql5.7（阿里云rds） ,sqlsugar 4.9.8.1
问题：程序发布之后，数据无法连接(有时会)，过几分钟后面自动又可以链接 提示 ，
Unable to connect to any of the specified MySQL hosts.\"HResult\":-2146233088

**Comment by sunkaixuan** [comment]
这个是没连上数据库

**Comment by sunkaixuan** [comment]
偶发性错误可以参考这个http://www.codeisbug.com/Home/Doc?typeId=1224
