### ISSUE TITLE
SqlSugar 4.9.9.10 在联想小新 Air 15（ AMD4800U版本） Win10家庭版上连接数据库抛出异常

### ISSUE THREAD

**Issue by bennywolf** [sunkaixuan/SqlSugar#851]
相同的代码运行在Intel CPU上正常。
下载源代码后，异常抛出在AdoProvider.cs文件第135行语句
this.Connection.Open();
提示信息如下：
System.AccessViolationException
  HResult=0x80004003
  Message=尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>

**Comment by sunkaixuan** [comment]
解决方法：管理员运行：netsh winsock reset

**Comment by sunkaixuan** [comment]
如果还不能解决看下这2个种字符串写法
 string connectionstring1 = "Data Source=127.0.0.1;Initial Catalog=YRB;User ID=sa;Password=sa;Persist Security Info=True";
string connectionstring2 = "Data Source=.;Initial Catalog=YRB;User ID=sa;Password=sa;Persist Security Info=True";
如果第二种好的 ，把启动设置成AnyCpu 方式启动

**Comment by bennywolf** [comment]
以上方法都实验过了，无效。后来定位问题出在 System.Data.SQLite.dll 上，从102版本更新到113版本后问题解决
