### ISSUE TITLE
代码里面没有注释

### ISSUE THREAD

**Issue by zengxiuhao** [sunkaixuan/SqlSugar#852]
类，接口，方法里面没有注释，可以添加一下吗？

**Comment by sunkaixuan** [comment]
方法 类接 口英文都没有缩写 不明白的可以问我

**Comment by akimusume** [comment]
xml注释还是有必要的，不仅仅是用来表明标识符的字面意思，还需要解释具体用处和内在逻辑。比如我们知道Enumerable.First()在没有结果的时候会抛出异常，如果要返回null应该用FirstOfDefault，那Queryable().First()方法会抛出异常吗？比如DbColumnInfo.TableId和Scale是干嘛用的？比如Db.IsSystemTablesConfig是干嘛用的？

毕竟教程式文档没法面面俱到，而且这种内在逻辑写在注释里比写文档里方便多了，xml注释也能自动生成api文档，生成之后直接挂在官网，不是很好吗

**Comment by xueshiji** [comment]
故意不给的，好收你咨询费
