### ISSUE TITLE
sqlsugar支持实体trigger吗？

### ISSUE THREAD

**Issue by lijinan** [sunkaixuan/SqlSugar#853]
即实体的某个属性值发生改变，则调用对应业务逻辑

**Comment by sunkaixuan** [comment]
可以参考http://www.codeisbug.com/Home/Doc?typeId=1204 差异日志的例子

**Comment by sunkaixuan** [comment]
当数据库发生变化可以监控

**Comment by lijinan** [comment]
看了一下，aop的方式可以注入实现
但业务逻辑过多的情况下，耦合性太强
我看能不能改造一下
