### ISSUE TITLE
Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'

### ISSUE THREAD

**Issue by lijingpan** [sunkaixuan/SqlSugar#854]
作者你好，是否有将Microsoft.Data.SqlClient替换System.Data.SqlClient的意向吗

**Comment by sunkaixuan** [comment]
暂时不考虑，我都选择了比较大众的功能相当对比完善的驱动

**Comment by sunkaixuan** [comment]
引用slqsugarcore不需要你引用任何驱动

**Comment by winlj** [comment]
> 作者你好，是否有将Microsoft.Data.SqlClient替换System.Data.SqlClient的意向吗

请问楼主这个错误你是怎么解决的呢？
