### ISSUE TITLE
连接字符串中使用DataDirectory时会报错

### ISSUE THREAD

**Issue by H3317** [sunkaixuan/SqlSugar#855]
连接字符串中使用DataDirectory后，
连接字符串@"DataSource=|DataDirectory|\DataBase\SqlSugar4xTest.sqlite"
使用db.DbMaintenance.CreateDatabase();会报错
   路径不能为空字符串或全为空白。
   在 System.IO.Directory.CreateDirectory(String path)
   在 SqlSugar.FileHelper.CreateDirectory(String directoryPath)
   在 SqlSugar.SqliteDbMaintenance.CreateDatabase(String databaseName, String databaseDirectory)
   在 SqlSugar.DbMaintenanceProvider.CreateDatabase(String databaseDirectory)

**Comment by sunkaixuan** [comment]
http://www.codeisbug.com/Home/Doc?typeId=1222



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunkaixuan/SqlSugar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午2:14
收件人:&nbsp;"sunkaixuan/SqlSugar"<SqlSugar@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[sunkaixuan/SqlSugar] 连接字符串中使用DataDirectory时会报错 (#855)





 
连接字符串中使用DataDirectory后，
 连接字符串@"DataSource=|DataDirectory|\DataBase\SqlSugar4xTest.sqlite"
 使用db.DbMaintenance.CreateDatabase();会报错
 路径不能为空字符串或全为空白。
 在 System.IO.Directory.CreateDirectory(String path)
 在 SqlSugar.FileHelper.CreateDirectory(String directoryPath)
 在 SqlSugar.SqliteDbMaintenance.CreateDatabase(String databaseName, String databaseDirectory)
 在 SqlSugar.DbMaintenanceProvider.CreateDatabase(String databaseDirectory)

**Comment by MostHated** [comment]
I just wanted to share that I am having this issue as well, but the fix specified on that page didn't seem to help for some reason.
