### ISSUE TITLE
达梦数据库问题

### ISSUE THREAD

**Issue by wbz-hot** [sunkaixuan/SqlSugar#857]
![image](https://user-images.githubusercontent.com/27388711/102035485-6ffefe80-3dfb-11eb-9022-6d97164f8b6c.png)
字段别名是不是忘了写，查询有问题

**Comment by sunkaixuan** [comment]
你把具体的错误方法发出来，达构获取列是用的这个方法

   private List<DbColumnInfo> GetColumnInfosByTableName(string tableName)
        {
            string sql = "select * from " + SqlBuilder.GetTranslationTableName(tableName) + " WHERE 1=2 ";
            var oldIsEnableLog = this.Context.Ado.IsEnableLogEvent;
            this.Context.Ado.IsEnableLogEvent = false;
            using(DbDataReader reader = (DbDataReader) this.Context.Ado.GetDataReader(sql))
            {
                this.Context.Ado.IsEnableLogEvent = oldIsEnableLog;
                List<DbColumnInfo> result = new List<DbColumnInfo>();
                var schemaTable = reader.GetSchemaTable();
                foreach (System.Data.DataRow row in schemaTable.Rows)
                {
                    DbColumnInfo column = new DbColumnInfo()
                    {
                        TableName = tableName,
                        DataType = row["DataType"].ToString().Replace("System.", "").Trim(),
                        IsNullable = (bool) row["AllowDBNull"],
                        IsIdentity = (bool) row["IsIdentity"],
                        ColumnDescription = GetFieldComment(tableName, row["ColumnName"].ToString()),
                        DbColumnName = row["ColumnName"].ToString(),
                        //DefaultValue = row["defaultValue"].ToString(),
                        IsPrimarykey = GetPrimaryKeyByTableNames(tableName).Any(it => it.Equals(row["ColumnName"].ToString(), StringComparison.CurrentCultureIgnoreCase)),
                        Length = row["ColumnSize"].ObjToInt(),
                        Scale = row["numericscale"].ObjToInt()
                    };
                    result.Add(column);
                }
                return result;
            }
        }

**Comment by sunkaixuan** [comment]
已修改后面版本会修复
