### ISSUE TITLE
update error，Please help me，thanks

### ISSUE THREAD

**Issue by SirHi** [sunkaixuan/SqlSugar#858]
![image](https://user-images.githubusercontent.com/34530046/102456987-fe35e780-407c-11eb-850c-46ebbba489eb.png)

ORA-06550: 第 3 行, 第 1 列: \nPLS-00103: 出现符号 \"END\"在需要下列之一时：\n ( begin case\n   declare exit for goto if loop mod null pragma raise return\n   select update while with &lt;an identifier>\n   &lt;a double-quoted delimited-identifier> &lt;a bind variable> &lt;&lt;\n   continue close current delete fetch lock insert open rollback\n   savepoint set sql execute commit forall merge pipe purge

**Comment by sunkaixuan** [comment]
UpdateColumns(t=>new{t.updateid,t.updatetime,t.last_time,t.remove_time})

**Comment by SirHi** [comment]
> UpdateColumns(t=>new{t.updateid,t.updatetime,t.last_time,t.remove_time})

Is this true for all update operations？

**Comment by sunkaixuan** [comment]
看文档 http://www.codeisbug.com/Home/Doc?typeId=1191
