### ISSUE TITLE
字典数据插入数据失败

### ISSUE THREAD

**Issue by netstart188** [sunkaixuan/SqlSugar#88]
文档上说4.6.4.8支持了不加泛型的字典,我用的版本是4.6.4.9插入失败。
 var dt = new Dictionary<string, object>();
            dt.Add("ID", "a3cb0c94-3b72-4e14-931d-f03589f2f6a0");
            dt.Add("UserName", "wanwan");
            dt.Add("Password", "202CB962AC59075B964B07152D234B70");
            dt.Add("Name", "wav");
            dt.Add("Position", "");
db.Context.Insertable(dt).AS("wy_user_copy").ExecuteReturnIdentity();
问题出在表名并没有更改过来！！

**Comment by sunkaixuan** [comment]
已修改节后上班前同步到GITHUB

**Comment by jkdeadwolf** [comment]
我用的4.8.5 版本还是有这个问题。

签代码下来看了下。是下面这段代码有点问题。
因为 Dictionary<string, object>的类名是  Dictionary`2 ，其中的`符号，被如下判断的SqlTranslationLeft【Mysql】的转义符命中，导致表名映射不起作用。
麻烦再核实下，是不是这样
-----------------------------
       public virtual string GetTranslationTableName(string name)
        {
            Check.ArgumentNullException(name, string.Format(ErrorMessage.ObjNotExist, "Table Name"));
            if (name.IsContainsIn("(", ")", SqlTranslationLeft))
            {
                return name;
            }
