### ISSUE TITLE
实体映射出错

### ISSUE THREAD

**Issue by volkd** [sunkaixuan/SqlSugar#9]
调用方法:
            using (var dbcon = Dao.DbConfig.GetDbInstance())
            {
                result = dbcon.SqlQuery<ChengZhangPH>(sql);
            }
生成的sql:
            select * from (select ROW_NUMBER() OVER(ORDER BY  cast(TT.HuoDongExp2 as int)  desc, cast(TT.HuoDongExp1 as int) desc) AS 'RowNumber', * from (  select t.[ID],  t.[CTime],   [WeiXinUnionID], WxName, HuoDongExp1, HuoDongExp2 , ( CASE WHEN wx.HeadImgUrl=''  THEN  'aaa'  ELSE  wx.HeadImgUrl +'aaa' END)  ImgUrl,  (       CASE WHEN HuoDongExp2 is null  THEN   cast(HuoDongExp1 as int)     ELSE cast(HuoDongExp2 as int) * 50 + cast(HuoDongExp1 as int) END     ) zongsu   from HD_HuoDongInfo as t with(nolock)   left join WeiXinUserInfo wx on t.WeiXinUnionID=wx.UnionID  where t.[HuoDongId] = 51 and  t.State = 1 and typeid = 1   ) as tt) as ttt
出现的错误
        [SqlSugarException]: 错误信息：实体映射出错。
错误详情：指定的转换无效。
   在 SqlSugar.Check.Exception(Boolean isException, String message, String[] args)
   在 SqlSugar.SqlSugarTool.DataReaderToList[T](Type type, IDataReader dr, String fields, Boolean isClose)
   在 SqlSugar.SqlSugarClient.SqlQuery[T](String sql, List`1 pars)
   在 SqlSugar.SqlSugarClient.SqlQuery[T](String sql, Object whereObj)

**Comment by sunkaixuan** [comment]
result = dbcon.SqlQuery<T>("--001 \r\n"+sql); 这样试试 sqlquery

是根据T 的 fullName 加上   sql的前50个字符 做缓存KEY，如果你的T对应了多个SQL 加上你SQL前五十字符串又完全一模一样，并且查询的列不一样可能会出现你说的情况。
