### ISSUE TITLE
插入数据库默认值问题

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#93]
版本：4.6.4.8，数据库：sqlite
---------------------------------
在实体类上加 [SugarColumn(IsOnlyIgnoreInsert=true)] 这个标记后，插入确实会插入数据库默认值
但是如果这个标记的字段赋值了也是插入数据库默认值，不知道是不是一个BUG

**Comment by sunkaixuan** [comment]
这个没办法处理的 因为要走数据库默认值 就需要写不插入这个字段
