### ISSUE TITLE
批量插入包含文件目录会造成插入失败

### ISSUE THREAD

**Issue by guandy** [sunkaixuan/SqlSugar#95]
形成的SQL如下。其它第一条数据ConfigValue 的数据为：“d:\buscon\template\”
`INSERT `GS_CONFIGITEM`  (`ConfigId`,`ConfigKey`,`ConfigType`,`ConfigValue`,`Remark`,`IsVaild`,`EditTime`,`EditUser`,`CreateTime`,`CreateUser`,`GroupType`,`CompanyId`,`IsSysData`,`IsMould`)
 SELECT N'4e41fcca826549f8a1b461dc2de69349' AS `ConfigId`,N'modelconpath        ' AS `ConfigKey`,N'WebConstantConfig' AS `ConfigType`,N'd:\buscon\template\' AS `ConfigValue`,N'同步' AS `Remark`,N'1' AS `IsVaild`,NULL AS `EditTime`,NULL AS `EditUser`,'2018-09-07 15:09:19.254' AS `CreateTime`,N'admin' AS `CreateUser`,N'1' AS `GroupType`,N'56dce150-0642-4af1-a57f-206b7a8dddcd' AS `CompanyId`,N'0' AS `IsSysData`,N'0' AS `IsMould`	
UNION ALL 
 SELECT N'b5e1d5cc44874e58a51e11fc61478b6c' AS `ConfigId`,N'TalentType' AS `ConfigKey`,N'WebConstantConfig' AS `ConfigType`,N'TalentType' AS `ConfigValue`,N'同步' AS `Remark`,N'1' AS `IsVaild`,NULL AS `EditTime`,NULL AS `EditUser`,'2018-09-07 15:09:19.254' AS `CreateTime`,N'admin' AS `CreateUser`,N'1' AS `GroupType`,N'56dce150-0642-4af1-a57f-206b7a8dddcd' AS `CompanyId`,N'0' AS `IsSysData`,N'0' AS `IsMould``

报错：You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' AS `Remark`,N'1' AS `IsVaild`,NULL AS `EditTime`,NULL AS `EditUser`,'2018-09-0' at line 2

**Comment by sunkaixuan** [comment]
var insertObj = new Student() { Name = @"d:\buscon\template\", CreateTime = Convert.ToDateTime("2010 -1-1"), SchoolId = 1 };

            //Insert reutrn Insert Count
            var t2 = db.Insertable(insertObj).ExecuteCommand();

            //Insert reutrn Identity Value
            var t3 = db.Insertable(insertObj).ExecuteReturnIdentity();
 没有重现看看是不是用法有问题
