### ISSUE TITLE
SqlFunc.DateIsSame 查询不到数据

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#96]
版本：4.6.4.8，数据库：sqlite，mssql（mysql没试过）
db.Queryable<Student>().Where(it => SqlFunc.DateIsSame(it.CreateTime, DateTime.Now)).ToList();
很确认数据库有当天数据，查出来是空

**Comment by KFine001** [comment]
经大量测试，怀疑问题出现在年月日的长度上，比如2018-09-07和2018-9-7不认为是同一天

**Comment by sunkaixuan** [comment]
数据库格式要标准时间格式 已修复
