### ISSUE TITLE
db.Ado.UseTran 事务问题

### ISSUE THREAD

**Issue by KFine001** [sunkaixuan/SqlSugar#97]
版本：4.6.4.8，数据库：sqlite

有一段业务逻辑
1、插入A表数据
2、循环一个ID数组
          |- 获取B表数据
          |- 声明List，model，赋值加入List
          |- list批量插入C表
3、修改D表某一个字段

如果这段逻辑写到 db.Ado.UseTran 里就报错 database is locked , 同时数据库是能查询不能插入修改删除，关闭VS后恢复正常

把 db.Ado.UseTran 去掉运行正常

**Comment by sunkaixuan** [comment]
并非SQLSUGAR问题 检查代码是否线程安全
